export const distribuidoraOptions = [
  { value: '82', label: 'ADURIZ DISTRIBUCIÓN, S.L.' },
  { value: '83', label: 'AFRODÍSIO PASCUAL ALONSO, S.L.' },
  { value: '84', label: 'AGRI ENERGÍA ELÉCTRICA, S.A.' },
  { value: '85', label: 'AGRUPACIÓN DISTRIBUIDORA DE ESCUER, S.L.' },
  { value: '86', label: 'ALARCÓN NAVARRO EMPRESA ELÉCTRICA, S.L.' },
  { value: '87', label: 'ALCONERA DE ELECTRICIDAD, S.L.U.' },
  { value: '88', label: 'ALGINET DISTRIBUCIÓN ENERGÍA ELÉCTRICA, S.L.' },
  { value: '89', label: 'ALSET ELÉCTRICA, S.L.' },
  { value: '90', label: 'ANSELMO LEÓN DISTRIBUCIÓN, S.L.' },
  { value: '91', label: 'ANTOLINA RUIZ RUIZ, S.L.U.' },
  { value: '92', label: 'ARAGONESA DE ACTIVIDADES ENERGÉTICAS, S.A. (AAESA)' },
  { value: '93', label: 'ARAMAIOKO ARGINDAR BANATZILEA, S.A.' },
  { value: '94', label: 'AURORA GINER REIG, S.L.' },
  { value: '95', label: 'BARRAS ELÉCTRICAS GALAICO-ASTURIANAS S.A.' },
  { value: '96', label: 'BASSOLS ENERGÍA, S.A.' },
  { value: '97', label: 'BERRUEZA, S.A.' },
  { value: '5', label: 'BLAZQUEZ, S.L.' },
  { value: '98', label: 'C. MARCIAL CHACON E HIJOS, S.L.' },
  { value: '99', label: 'CARDENER DISTRIBUCIÓ ELÈCTRICA, S.L.U' },
  { value: '100', label: 'CATENERIBAS, S.L.' },
  { value: '101', label: 'CENTRAL ELÉCTRICA DE POZO LORENTE, S. L.' },
  { value: '102', label: 'CENTRAL ELÉCTRICA INDUSTRIAL, S.L.' },
  { value: '103', label: 'CENTRAL ELÉCTRICA MITJANS, S.L.' },
  { value: '104', label: 'CENTRAL ELÉCTRICA SAN ANTONIO, S.L.' },
  { value: '72', label: 'CENTRAL ELÉCTRICA SAN FRANCISCO, S.L.' },
  { value: '105', label: 'CENTRAL ELÉCTRICA SESTELO Y CIA, S.A.' },
  { value: '106', label: 'COELCA REDES, S.L.U.' },
  { value: '107', label: 'COMPAÑÍA DE ELECTRICIDAD DEL CONDADO, S.A.' },
  { value: '108', label: 'COMPAÑÍA DE ELECTRIFICACIÓN, S.L.' },
  { value: '109', label: 'COMPAÑÍA ELÉCTRICA DE FEREZ, S.L.' },
  { value: '110', label: 'COMPAÑÍA MELILLENSE DE GAS Y ELECTRICIDAD, S.A.' },
  { value: '111', label: 'COOPERATIVA ELÉCTRICA ALBORENSE, S.A.' },
  { value: '112', label: 'COOPERATIVA POPULAR DE FLUIDO ELÉCTRICO DE CAMPRODON, S.C.C.L.' },
  { value: '113', label: 'DECAIL ENERGÍA, S.L.' },
  { value: '114', label: 'DELGICHI, S.L.' },
  { value: '8', label: 'DIELEC GUERRERO LORENTE, S.L.' },
  { value: '66', label: 'DIELENOR, S.L.' },
  { value: '383', label: 'DIELESUR, S.L.' },
  { value: '65', label: 'DIELESUR, S.L.' },
  { value: '115', label: 'DISELSOT, S.L.U.' },
  { value: '9', label: 'DISTRIBUCIONES ALNEGA, S.L.' },
  { value: '125', label: 'DISTRIBUCIONES DE ENERGÍA ELÉCTRICA DEL NOROESTE, S.L.' },
  { value: '126', label: 'DISTRIBUCIONES ELÉCTRICAS DE GISTAÍN S.L.' },
  { value: '127', label: 'DISTRIBUCIONES ELÉCTRICAS DE POZUELO, S.A.' },
  { value: '128', label: 'DISTRIBUCIONES ELÉCTRICAS DEL ERIA, S.L.' },
  { value: '129', label: 'DISTRIBUCIONES ELÉCTRICAS PORTILLO, S.L.' },
  { value: '130', label: 'DISTRIBUCIONES ELÉCTRICAS TALAYUELAS, S.L.' },
  { value: '116', label: 'DISTRIBUCIÓN DE ELECTRICIDAD VALLE DE SANTA ANA, S.L.' },
  { value: '117', label: 'DISTRIBUCIÓN ELÉCTRICA CATRALENSE, S.L.U.' },
  { value: '118', label: 'DISTRIBUCIÓN ELÉCTRICA CREVILLENT, S.L.U.' },
  { value: '119', label: 'DISTRIBUCIÓN ELÉCTRICA DE ALCOLECHA, S.L.' },
  { value: '120', label: 'DISTRIBUCIÓN ELÉCTRICA DE CALLOSA DE SEGURA, S.L.U.' },
  { value: '121', label: 'DISTRIBUCIÓN ELÉCTRICA DEL TAJUÑA, S.L.U.' },
  { value: '122', label: 'DISTRIBUCIÓN ELÉCTRICA EL POZO DEL TÍO RAIMUNDO, S.L.U.' },
  { value: '123', label: 'DISTRIBUCIÓN ELÉCTRICA LAS MERCEDES, S.L.' },
  { value: '124', label: 'DISTRIBUCIÓN ENERGIA ELÉCTRICA DE PARCENT, S.L.' },
  { value: '131', label: 'DISTRIBUIDORA DE ELECTRICIDAD LARRAÑAGA, S.L.' },
  { value: '11', label: 'DISTRIBUIDORA DE ELECTRICIDAD MARTOS MARIN, S.L.' },
  { value: '134', label: 'DISTRIBUIDORA DE ENERGIA ELÉCTRICA ENERQUINTA, S.L.' },
  { value: '135', label: 'DISTRIBUIDORA DE ENERGIA ELÉCTRICA ENRIQUE GARCÍA SERRANO, S.L.' },
  { value: '136', label: 'DISTRIBUIDORA DE ENERGIA ELÉCTRICA TORRECILLAS VIDAL, S.L.' },
  { value: '132', label: 'DISTRIBUIDORA DE ENERGÍA ELÉCTRICA DE DON BENITO, S.L.U.' },
  { value: '133', label: 'DISTRIBUIDORA DE ENERGÍA ELÉCTRICA DEL BAGES, S.A.' },
  { value: '137', label: 'DISTRIBUIDORA ELÉCTRICA ALBATERENSE NUESTRA SEÑORA DE LA LUZ, S.L.U.' },
  { value: '138', label: 'DISTRIBUIDORA ELÉCTRICA BRAVO SAEZ, S.L.' },
  { value: '139', label: 'DISTRIBUIDORA ELÉCTRICA CARRIÓN, S.L.' },
  { value: '140', label: 'DISTRIBUIDORA ELÉCTRICA D ALBATARREC, S.L.' },
  { value: '141', label: 'DISTRIBUIDORA ELÉCTRICA DE ARDALES, S.L.' },
  { value: '142', label: 'DISTRIBUIDORA ELÉCTRICA DE CASAS DE LAZARO, S.A.' },
  { value: '143', label: 'DISTRIBUIDORA ELÉCTRICA DE GAUCIN, S.L.' },
  { value: '144', label: 'DISTRIBUIDORA ELÉCTRICA DE MELIANA, S.L.U.' },
  { value: '145', label: 'DISTRIBUIDORA ELÉCTRICA DE MELÓN, S.L.' },
  { value: '146', label: 'DISTRIBUIDORA ELÉCTRICA DE MONESTERIO, S.L.' },
  { value: '147', label: 'DISTRIBUIDORA ELÉCTRICA DE MONTOLIU, S.L. U.' },
  { value: '148', label: 'DISTRIBUIDORA ELÉCTRICA DE RELLEU, S.L.' },
  { value: '149', label: 'DISTRIBUIDORA ELÉCTRICA DEL PUERTO DE LA CRUZ, S.A.' },
  { value: '150', label: 'DISTRIBUIDORA ELÉCTRICA DEL SIL, S.L.' },
  { value: '151', label: 'DISTRIBUIDORA ELÉCTRICA GRANJA DE TORREHERMOSA, S.L.' },
  { value: '152', label: 'DISTRIBUIDORA ELÉCTRICA ISABA, S.L.U.' },
  { value: '153', label: 'DISTRIBUIDORA ELÉCTRICA LOS BERMEJALES, S.A.' },
  { value: '154', label: 'DISTRIBUIDORA ELÉCTRICA NAVASFRIAS, S.L.' },
  { value: '155', label: 'DISTRIBUIDORA ELÉCTRICA NIEBLA, S.L.' },
  { value: '156', label: 'DISTRIBUIDORA ELÉCTRICA VALLE DE ANSÓ, S.L.' },
  { value: '157', label: 'E. SAAVEDRA, S.A.' },
  { value: '158', label: 'EBROFANAS, S.L.' },
  { value: '159', label: 'EDFA CASABLANCA DISTRIBUIDORA, S.L.U.' },
  { value: '160', label: 'EDISTRIBUCIÓN REDES DIGITALES, S.L.' },
  { value: '161', label: 'EL PROGRESO DEL PIRINEO, S.L.' },
  { value: '162', label: 'ELEC-VALL BOI, S.L.' },
  { value: '163', label: 'ELECTRA ALTO MIÑO DISTRIBUIDORA DE ENERGÍA, S.L.' },
  { value: '164', label: 'ELECTRA ALVARO BENITO, S.L.' },
  { value: '165', label: 'ELECTRA AUTOL, S.A.' },
  { value: '166', label: 'ELECTRA AVELLANA, S.L.' },
  { value: '167', label: 'ELECTRA CALDENSE, S.A.' },
  { value: '168', label: 'ELECTRA CASTILLEJENSE, S.A.' },
  { value: '17', label: 'ELECTRA CONILENSE, S.L.U.' },
  { value: '169', label: 'ELECTRA CUNTIENSE, S.L.' },
  { value: '170', label: 'ELECTRA DE CABALAR, S.L.' },
  { value: '171', label: 'ELECTRA DE CARBAYIN, S.A.' },
  { value: '172', label: 'ELECTRA DE SANTA COMBA, S.L.' },
  { value: '173', label: 'ELECTRA DE ZAS, S.L.' },
  { value: '174', label: 'ELECTRA DEL GAYOSO, S.L.' },
  { value: '175', label: 'ELECTRA DEL LLOBREGAT ENERGIA, S.L.' },
  { value: '176', label: 'ELECTRA DEL NARAHIO, S.A.' },
  { value: '177', label: 'ELECTRA DO FOXO, S.L.' },
  { value: '178', label: 'ELECTRA JOSÉ ANTONIO MARTINEZ, S.L.' },
  { value: '179', label: 'ELECTRA LA HONORINA, S.L.' },
  { value: '18', label: 'ELECTRA LA LOMA, S.L.' },
  { value: '180', label: 'ELECTRA LA ROSA, S.L.' },
  { value: '181', label: 'ELECTRA ORBAICETA, S.L.' },
  { value: '182', label: 'ELECTRA REDENERGIA, S.L.' },
  { value: '183', label: 'ELECTRA SALTEA, S.L.' },
  { value: '184', label: 'ELECTRA SAN BARTOLOMÉ, S.L.' },
  { value: '19', label: 'ELECTRA SAN CRISTOBAL, S.L.' },
  { value: '20', label: 'ELECTRA SIERRA MAGINA, S.L.' },
  { value: '185', label: 'ELECTRA TUDANCA, S.L.' },
  { value: '186', label: 'ELECTRA VALDIVIELSO, S.A.' },
  { value: '187', label: 'ELECTRA VALDIZARBE DISTRIBUCIÓN, S.L.U.' },
  { value: '188', label: 'ELECTRADISTRIBUCIÓ CENTELLES, S.L.' },
  { value: '36', label: 'ELECTRICIDAD DE PUERTO REAL, S.A. (EPRESA)' },
  { value: '37', label: 'ELECTRICIDAD HIJATE, S.L.' },
  { value: '256', label: 'ELECTRICIDAD LA ASUNCIÓN, S.L.' },
  { value: '38', label: 'ELECTRICIDAD PASTOR, S.L.' },
  { value: '257', label: 'ELECTRICITAT L AURORA, S.A.' },
  { value: '258', label: 'ELECTRO DISTRIBUCIÓN DE ALMODÓVAR DEL CAMPO, S.A.' },
  { value: '259', label: 'ELECTRO DISTRIBUIDORA CASTELLANO LEONESA, S.A.' },
  { value: '260', label: 'ELECTRO ESCARRILLA, S.L.' },
  { value: '261', label: 'ELECTRO MANZANEDA, S.L.' },
  { value: '262', label: 'ELECTRO MOLINERA DE VALMADRIGAL, S.L.' },
  { value: '263', label: 'ELECTRO SALLENT DE GALLEGO, S.L.' },
  { value: '264', label: 'ELECTROHARINERA BELSETANA, SOCIEDAD COOPERATIVA' },
  { value: '189', label: 'ELÉCTRICA ABENGIBRENSE DISTRIBUCIÓN, S.L.' },
  { value: '190', label: 'ELÉCTRICA ARANGARONA, S.L.U.' },
  { value: '191', label: 'ELÉCTRICA BAÑESA, S.L.' },
  { value: '69', label: 'ELÉCTRICA BELMEZANA, S.A.' },
  { value: '192', label: 'ELÉCTRICA CAMPOSUR, S.L.' },
  { value: '193', label: 'ELÉCTRICA CONQUENSE DISTRIBUCIÓN, S.A.U.' },
  { value: '194', label: 'ELÉCTRICA CORVERA, S.L.' },
  { value: '195', label: 'ELÉCTRICA COSTUR, S.L.,' },
  { value: '196', label: 'ELÉCTRICA CUROS, S.L.' },
  { value: '197', label: 'ELÉCTRICA DE ALBERGUERIA, S.A' },
  { value: '198', label: 'ELÉCTRICA DE ALGIMIA DE ALFARA DISTRIBUIDORA, S.L.U.' },
  { value: '199', label: 'ELÉCTRICA DE BARBASTRO, S.A.' },
  { value: '200', label: 'ELÉCTRICA DE BARCIADEMERA, S.L.' },
  { value: '201', label: 'ELÉCTRICA DE BIAR DISTRIBUCIÓN, S.L.U.' },
  { value: '202', label: 'ELÉCTRICA DE CABAÑAS, S.L.' },
  { value: '203', label: 'ELÉCTRICA DE CANILES, S.L.' },
  { value: '204', label: 'ELÉCTRICA DE CANTOÑA, S.L.' },
  { value: '205', label: 'ELÉCTRICA DE CASTRO CALDELAS, S.L.' },
  { value: '206', label: 'ELÉCTRICA DE CATOIRA, S.L.U.' },
  { value: '207', label: 'ELÉCTRICA DE CHERA DISTRIBUIDORA, S.L' },
  { value: '208', label: 'ELÉCTRICA DE DURRO, S.L.' },
  { value: '209', label: 'ELÉCTRICA DE ERISTE, S.L.' },
  { value: '210', label: 'ELÉCTRICA DE GRES, S.L.' },
  { value: '211', label: 'ELÉCTRICA DE GUADASSUAR DISTRIBUCIÓN, S.L.U.' },
  { value: '212', label: 'ELÉCTRICA DE GUIXES, S.L.' },
  { value: '213', label: 'ELÉCTRICA DE JAFRE, S.A.' },
  { value: '214', label: 'ELÉCTRICA DE LA SERRANÍA DE RONDA, S.L' },
  { value: '215', label: 'ELÉCTRICA DE LIJAR,S.L.' },
  { value: '216', label: 'ELÉCTRICA DE MALCOCINADO, S.L.U.' },
  { value: '217', label: 'ELÉCTRICA DE MOSCOSO, S.L.' },
  { value: '218', label: 'ELÉCTRICA DE SUDANELL, S.L.' },
  { value: '219', label: 'ELÉCTRICA DE TENTUDIA, S.A.' },
  { value: '220', label: 'ELÉCTRICA DE VALDRIZ, S.L.' },
  { value: '221', label: 'ELÉCTRICA DE VER, S.L.' },
  { value: '222', label: 'ELÉCTRICA DEL EBRO, S.A.' },
  { value: '223', label: 'ELÉCTRICA DEL GUADALFEO, S.L.' },
  { value: '224', label: 'ELÉCTRICA DEL HUEBRA, S.L.' },
  { value: '225', label: 'ELÉCTRICA DEL MONTSEC, S.L.' },
  { value: '226', label: 'ELÉCTRICA DEL OESTE DISTRIBUCIÓN, S.L.U.' },
  { value: '227', label: 'ELÉCTRICA GILENA, S.L.U.' },
  { value: '228', label: 'ELÉCTRICA HERMANOS CASTRO RODRÍGUEZ, S.L.' },
  { value: '229', label: 'ELÉCTRICA LA VICTORIA DE FUENCALIENTE, S.A.' },
  { value: '64', label: 'ELÉCTRICA LATORRE, S.L.' },
  { value: '230', label: 'ELÉCTRICA LOS LAURELES, S.L.' },
  { value: '231', label: 'ELÉCTRICA LOS MOLINOS, S.L.' },
  { value: '232', label: 'ELÉCTRICA LOS PELAYOS, S.A.' },
  { value: '233', label: 'ELÉCTRICA MESTANZA R.V., S.L.' },
  { value: '234', label: 'ELÉCTRICA MORO BENITO, S.L.' },
  { value: '235', label: 'ELÉCTRICA MUNICIPAL DE SANTA COLOMA DE QUERALT S.L.' },
  { value: '236', label: 'ELÉCTRICA NUESTRA SEÑORA DE LOS SANTOS, S.L.' },
  { value: '237', label: 'ELÉCTRICA SAGRADO CORAZÓN DE JESÚS, S.L.' },
  { value: '238', label: 'ELÉCTRICA SALAS DE PALLARS, S.L.' },
  { value: '80', label: 'ELÉCTRICA SAN GREGORIO, S.L.' },
  { value: '239', label: 'ELÉCTRICA SAN JOSE OBRERO, S.L.' },
  { value: '240', label: 'ELÉCTRICA SAN MARCOS, S.L.' },
  { value: '241', label: 'ELÉCTRICA SAN SERVAN, S.L.' },
  { value: '242', label: 'ELÉCTRICA SANTA CLARA, S.L.' },
  { value: '243', label: 'ELÉCTRICA SANTA MARTA Y VILLALBA, S.L.' },
  { value: '244', label: 'ELÉCTRICA SEROSENSE DISTRIBUIDORA, S.L.' },
  { value: '245', label: 'ELÉCTRICA SERRALLO, S.L.U.' },
  { value: '246', label: 'ELÉCTRICA VAQUER, S.A.' },
  { value: '247', label: 'ELÉCTRICAS COLLADO BLANCO, S.L.' },
  { value: '248', label: 'ELÉCTRICAS DE BENUZA, S.L.' },
  { value: '249', label: 'ELÉCTRICAS DE VALLANCA, S.L.' },
  { value: '250', label: 'ELÉCTRICAS DE VILLAHERMOSA, S.A.' },
  { value: '251', label: 'ELÉCTRICAS HIDROBESORA, S.L.' },
  { value: '252', label: 'ELÉCTRICAS LA ENGUERINA, S.L.' },
  { value: '253', label: 'ELÉCTRICAS PITARCH DISTRIBUCIÓN, S.L.U.' },
  { value: '254', label: 'ELÉCTRICAS SANTA LEONOR, S.L.' },
  { value: '255', label: 'ELÉCTRICAS TUEJAR, S.L.' },
  { value: '265', label: 'EMDECORIA, S.L.' },
  { value: '39', label: 'EMILIO PADILLA E HIJOS, S.L.' },
  { value: '266', label: 'EMPRESA DE ALUMBRADO ELÉCTRICO DE CEUTA DISTRIBUCIÓN, S.A.U.' },
  { value: '267', label: 'EMPRESA DE ELECTRICIDAD SAN JOSÉ, S.A.' },
  { value: '268', label: 'EMPRESA ELÉCTRICA DE JORQUERA, S.L.' },
  { value: '269', label: 'EMPRESA ELÉCTRICA DE SAN PEDRO, S.L.' },
  { value: '270', label: 'EMPRESA ELÉCTRICA DEL CABRIEL, S.L.' },
  { value: '271', label: 'EMPRESA ELÉCTRICA MARTIN SILVA POZO, S.L.' },
  { value: '272', label: 'EMPRESA MUNICIPAL DE DISTRIBUCIÓ DENERGIA ELECTRICA DALMENAR, S.L.U.' },
  { value: '273', label: 'EMPRESA MUNICIPAL DE DISTRIBUCIÓ DENERGIA ELÈCTRICA DE PONTS, S.L.' },
  { value: '274', label: 'EMPRESA MUNICIPAL DENERGÍA ELÉCTRICA TORRES DEL SEGRE, S.L.' },
  { value: '275', label: 'ENERFRIAS, S.L.' },
  { value: '276', label: 'ENERGÉTICA DE ALCOCER, S.L.U.' },
  { value: '277', label: 'ENERGÍA DE MIAJADAS, S.A.' },
  { value: '79', label: 'ENERGÍA ELÉCTRICA DE OLVERA, S.L.U' },
  { value: '278', label: 'ENERGÍAS DE ARAGÓN I, S.L.U. (EASA)' },
  { value: '279', label: 'ENERGÍAS DE BENASQUE, S.L.' },
  { value: '280', label: 'ENERGÍAS DE LA VILLA DE CAMPO, S.L.U.' },
  { value: '281', label: 'ENERGÍAS DE PANTICOSA, S.L.' },
  { value: '282', label: 'ENERGÍAS DEL ZINQUETA SL' },
  { value: '283', label: 'ESTABANELL Y PAHISA ENERGÍA, S.A.' },
  { value: '284', label: 'FELIPE BLÁZQUEZ, S.L.' },
  { value: '285', label: 'FLUIDO ELÉCTRICO MUSEROS DISTRIBUCIÓN ELÉCTRICA, S.L.U.' },
  { value: '286', label: 'FUCIÑOS RIVAS, S.L.' },
  { value: '287', label: 'FUENTES Y COMPAÑÍA, S.L.' },
  { value: '288', label: 'FUERZAS ELÉCTRICAS BOGARRA, S.A.' },
  { value: '289', label: 'GESTIÓN DEL SERVICIO ELÉCTRICO HECHO, S.L.' },
  { value: '290', label: 'GLORIA MARISCAL, S.L.' },
  { value: '43', label: 'GRACIA UNZUETA HIDALGO E HIJOS, S.L.' },
  { value: '291', label: 'GRUPO DE ELECTRIFICACIÓN RURAL DE BINEFAR Y COMARCA, S.COOP., R. L.' },
  { value: '292', label: 'HELIODORA GÓMEZ, S.A.' },
  { value: '293', label: 'HELIODORO CHAFER, S.L.' },
  { value: '294', label: 'HEREDEROS DE CARLOS OLTRA, S.L.' },
  { value: '68', label: 'HEREDEROS DE EMILIO GAMERO, S.L.' },
  { value: '295', label: 'HEREDEROS DE GARCÍA BAZ, S.L.' },
  { value: '296', label: 'HEREDEROS DE MARIA ALONSO CALZADA-VENTA DE BAÑOS, S.L.' },
  { value: '297', label: 'HERMANOS CABALLERO REBOLLO, S.L.' },
  { value: '298', label: 'HIDROCANTÁBRICO DISTRIBUCIÓN ELÉCTRICA, S.A.' },
  { value: '308', label: 'HIDROELECTRICA EL CARMEN REDES, S.L.' },
  { value: '299', label: 'HIDROELÉCTRICA COTO MINERO DISTRIBUCIÓN, S.L.U.' },
  { value: '300', label: 'HIDROELÉCTRICA DE ALARAZ, S.L.' },
  { value: '301', label: 'HIDROELÉCTRICA DE CATALUNYA, S.L.' },
  { value: '302', label: 'HIDROELÉCTRICA DE LARACHA, S.L.' },
  { value: '303', label: 'HIDROELÉCTRICA DE SILLEDA, S.L.' },
  { value: '304', label: 'HIDROELÉCTRICA DEL ARNEGO, S.L.' },
  { value: '305', label: 'HIDROELÉCTRICA DEL CABRERA, S.L.' },
  { value: '306', label: 'HIDROELÉCTRICA DEL GUADIELA I, S.A.' },
  { value: '307', label: 'HIDROELÉCTRICA DOMÍNGUEZ, S.L.' },
  { value: '62', label: 'HIDROELÉCTRICA EL CERRAJON, S.L.' },
  { value: '309', label: 'HIDROELÉCTRICA GÓMEZ, S.L.' },
  { value: '310', label: 'HIDROELÉCTRICA JOSÉ MATANZA GARCÍA, S.L.' },
  { value: '311', label: 'HIDROELÉCTRICA SAN BUENAVENTURA, S.L.' },
  { value: '312', label: 'HIDROELÉCTRICA SANTA TERESA, S.L.' },
  { value: '313', label: 'HIDROELÉCTRICA VEGA, S.A.' },
  { value: '314', label: 'HIDROELÉCTRICA VIRGEN DE CHILLA, S.L.' },
  { value: '315', label: 'HIDROENERGETICA DE MILLARES, S.L' },
  { value: '316', label: 'HIDROFLAMICELL, S.L.' },
  { value: '317', label: 'HIJO DE JORGE MARTIN, S.A.' },
  { value: '318', label: 'HIJOS DE CASIANO SANCHEZ, S.L.' },
  { value: '319', label: 'HIJOS DE FELIPE GARCÍA ÁLVAREZ, S.L.' },
  { value: '320', label: 'HIJOS DE FRANCISCO ESCASO S.L.' },
  { value: '321', label: 'HIJOS DE JACINTO GUILLEN DISTRIBUIDORA ELÉCTRICA, S.L.' },
  { value: '322', label: 'HIJOS DE MANUEL PERLES VICENS, S.L.' },
  { value: '323', label: 'I-DE Redes Eléctricas Inteligentes, S.A.U.' },
  { value: '324', label: 'ICASA DISTRIBUCIÓN ENERGIA, S.L.' },
  { value: '46', label: 'IGNALUZ JIMENEZ DE TORRES, S.L.' },
  { value: '325', label: 'INDUSTRIAL BARCALESA, S.L.' },
  { value: '70', label: 'INPECUARIAS POZOBLANCO, S.L.' },
  { value: '326', label: 'INPECUARIAS TORRECAMPO, S.L.' },
  { value: '327', label: 'INPECUARIAS VILLARALTO, S.L.' },
  { value: '328', label: 'ISMAEL BIOSCA, S.L.' },
  { value: '330', label: 'JOSE RIPOLL ALBANELL, S.L.' },
  { value: '331', label: 'JOSEFA GIL COSTA, S.L.' },
  { value: '329', label: 'JOSÉ FERRE SEGURA E HIJOS, S.R.L.' },
  { value: '332', label: 'JUAN DE FRUTOS GARCÍA DISTRIBUCIÓN ELÉCTRICA, S.L.U.' },
  { value: '333', label: 'JUAN N. DIAZ GÁLVEZ Y HERMANOS, S.L.' },
  { value: '334', label: 'JUAN Y FRANCISCO ESTEVE MAS, S.L.' },
  { value: '335', label: 'LA CONSTANCIA-ARÉN, S.L.' },
  { value: '336', label: 'LA ELÉCTRICA DE VALL DE EBO, S.L.' },
  { value: '337', label: 'LA ERNESTINA ENERGÍA, S.L.' },
  { value: '338', label: 'LA PROHIDA DISTRIBUCIÓN ELÉCTRICA, S.L.' },
  { value: '339', label: 'LA SINARQUENSE, S.L.U.' },
  { value: '340', label: 'LEANDRO PEREZ ALFONSO, S.L.' },
  { value: '341', label: 'LEINTZARGI, S.L.' },
  { value: '342', label: 'LERSA ELECTRICITAT, S.L.' },
  { value: '343', label: 'LLUM D\'AIN, S.L' },
  { value: '344', label: 'LUIS RANGEL Y HERMANOS, S.A.' },
  { value: '49', label: 'LUZ DE CELA, S.L.' },
  { value: '345', label: 'LUZ ELÉCTRICA DE ALGAR, S.L.U.' },
  { value: '29', label: 'LUZ ELÉCTRICA LOS MOLARES, S.L.' },
  { value: '346', label: 'MAESTRAZGO DISTRIBUCIÓN ELÉCTRICA, S.L.' },
  { value: '347', label: 'MANUEL ROBRES CELADES, S.L.' },
  { value: '51', label: 'MEDINA GARVEY ELECTRICIDAD, S.L.U.' },
  { value: '348', label: 'MOLINO VIEJO DE VILALLER, S.A.' },
  { value: '349', label: 'MONTESLUZ DISTRIBUCIÓN ELÉCTRICA, S.L.' },
  { value: '350', label: 'MUNICIPAL ELÉCTRICA VILORIA, S.L.' },
  { value: '351', label: 'OÑARGI, S.L.' },
  { value: '52', label: 'PEDRO SANCHEZ IBAÑEZ, S.L.' },
  { value: '352', label: 'PEUSA DISTRIBUCIÓ, S.L.' },
  { value: '353', label: 'REPSOL ELÉCTRICA DE DISTRIBUCIÓN, S.L.' },
  { value: '53', label: 'RODALEC, S.L.' },
  { value: '54', label: 'ROMERO CANDAU, S.L.' },
  { value: '354', label: 'RUIZ DE LA TORRE, S.L.' },
  { value: '355', label: 'SALTOS DEL CABRERA, S.L.' },
  { value: '356', label: 'SAMPOL ENERGÍA, S.L.' },
  { value: '357', label: 'SAN CIPRIANO DE RUEDA DISTRIBUCIÓN, S.L.' },
  { value: '358', label: 'SAN MIGUEL 2000 DISTRIBUCIÓN ELÉCTRICA, S.L.' },
  { value: '359', label: 'SERVICIOS URBANOS DE CERLER, S.A. (SUCSA)' },
  { value: '360', label: 'SERVICIOS Y SUMINISTROS MUNICIPALES ARAS, S.L.' },
  { value: '361', label: 'SERVICIOS Y SUMINISTROS MUNICIPALES DE CHULILLA, S.L.' },
  { value: '362', label: 'SERVILIANO GARCÍA, S.A.' },
  { value: '55', label: 'SIERRO DE ELECTRICIDAD, S.L.' },
  { value: '363', label: 'SOCIEDAD DISTRIBUIDORA ELÉCTRICA DE ELORRIO, S.A.' },
  { value: '367', label: 'SOCIEDAD ELECTRICISTA DE TUI DISTRIBUIDORA, S.L.U.' },
  { value: '364', label: 'SOCIEDAD ELÉCTRICA DE RIBERA DEL FRESNO, S.A.' },
  { value: '365', label: 'SOCIEDAD ELÉCTRICA JEREZ DEL MARQUESADO S.A.' },
  { value: '366', label: 'SOCIEDAD ELÉCTRICA NTRA. SRA. DE LOS DESAMPARADOS, S. L.' },
  { value: '369', label: 'SOCIETAT MUNICIPAL DE DISTRIBUCIÓ ELECTRICA DE TIRVIA, S.L.' },
  { value: '368', label: 'SOCIETAT MUNICIPAL DE DISTRIBUCIÓ ELÉCTRICA DE LLAVORSÍ, S.L.' },
  { value: '370', label: 'SUCESORES DE MANUEL LEIRA, S.L.' },
  { value: '371', label: 'SUMINISTRADORA ELÉCTRICA DE CÁDIZ, S.A.' },
  { value: '372', label: 'SUMINISTRO DE LUZ Y FUERZA, S.L.' },
  { value: '373', label: 'SUMINISTROS ELÉCTRICOS DE AMIEVA, S.L.' },
  { value: '374', label: 'SUMINISTROS ELÉCTRICOS ISÁBENA, S.L.' },
  { value: '375', label: 'TALARN DISTRIBUCIÓ MUNINCIPAL ELÈCTRICA, S.L.' },
  { value: '376', label: 'TOLARGI, S.L.' },
  { value: '378', label: 'UNION FENOSA DISTRIBUCIÓN, S.A.' },
  { value: '377', label: 'UNIÓN DE DISTRIBUIDORES DE ELECTRICIDAD, S.A. (UDESA)' },
  { value: '379', label: 'VALL DE SÓLLER ENERGÍA, S.L.U.' },
  { value: '380', label: 'VARGAS Y COMPAÑÍA ELECTRO HARINERA SAN RAMÓN, S.A.' },
  { value: '381', label: 'VIESGO DISTRIBUCIÓN ELÉCTRICA, S.L.' },
  { value: '382', label: 'VINALESA DISTRIBUCIÓN DE ENERGÍA, S.L.U.' }
];
