export const autorizacionRepresentacionConfig = {
  id: 'autorizacion-representacion',
  title: 'Autorización de Representación',
  description: 'Documento válido para trámites administrativos',
  fileName: 'autorizacion-representacion.pdf',
  route: '/autorizacion-representacion',
  fields: [
    { name: 'autorizante', label: 'Nombre del Autorizante', type: 'text', fullWidth: true },
    { name: 'dniAutorizante', label: 'DNI/NIF del Autorizante', type: 'text' },
    { name: 'domicilioAutorizante', label: 'Domicilio del Autorizante', type: 'text', fullWidth: true },
    { name: 'representante', label: 'Representante', type: 'text', fullWidth: true },
    { name: 'dniRepresentante', label: 'DNI/NIF del Representante', type: 'text' },
    { name: 'domicilioRepresentante', label: 'Domicilio del Representante', type: 'text', fullWidth: true },
    { name: 'organismo', label: 'Organismo', type: 'text', fullWidth: true },
    { name: 'gestiones', label: 'Gestiones a Realizar', type: 'textarea', rows: 3, fullWidth: true },
    { name: 'fecha', label: 'Fecha', type: 'date' }
  ],
  defaultData: {
    autorizante: '',
    dniAutorizante: '',
    domicilioAutorizante: '',
    representante: 'Solay Ingenieros, S.L.',
    dniRepresentante: 'B09848912',
    domicilioRepresentante: 'Calle Ebro, 35 – 41012, Sevilla, Sevilla',
    organismo: 'Ayuntamiento de Puerto Real (Cádiz)',
    gestiones: 'SOLICITUD DE LICENCIA DE OBRA MENOR CON DECLARACIÓN RESPONSABLE O AUTORIZACIÓN URBANÍSTICA',
    fecha: '18/11/2025'
  },
  fieldMapping: {
    autorizante: 'apellidosNombre',
    dniAutorizante: 'nifCif',
    domicilioAutorizante: 'domicilio',
    fecha: 'fecha'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const declaracionHabilitacionProfesionalConfig = {
  id: 'declaracion-habilitacion-profesional',
  title: 'Declaración Responsable de Habilitación Profesional',
  description: 'Documento de declaración de habilitación profesional para colegiados',
  fileName: 'declaracion-habilitacion-profesional.pdf',
  route: '/declaracion-habilitacion-profesional',
  fields: [
    { name: 'nombreProfesional', label: 'Nombre del Profesional', type: 'text', fullWidth: true },
    { name: 'nifProfesional', label: 'NIF del Profesional', type: 'text' },
    { name: 'profesionTitulo', label: 'Título Profesional', type: 'text', fullWidth: true },
    { name: 'numeroColegiado', label: 'Número de Colegiado', type: 'text' },
    { name: 'nombreColegio', label: 'Nombre del Colegio', type: 'text', fullWidth: true },
    { name: 'domicilioProfesional', label: 'Domicilio Profesional', type: 'text', fullWidth: true },
    { name: 'codigoPostalProfesional', label: 'Código Postal', type: 'text' },
    { name: 'localidadProfesional', label: 'Localidad', type: 'text' },
    { name: 'provinciaProfesional', label: 'Provincia', type: 'text' },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' }
  ],
  defaultData: {
    nombreProfesional: 'Eduardo Rivera Cabezas',
    nifProfesional: '28.818.007-L',
    profesionTitulo: 'Ingeniero Industrial',
    numeroColegiado: '4654',
    nombreColegio: 'Colegio Oficial de Ingenieros Industriales de Andalucía Occidental',
    domicilioProfesional: 'Calle El Peñón 5',
    codigoPostalProfesional: '41940',
    localidadProfesional: 'Tomares',
    provinciaProfesional: 'Sevilla',
    ciudadFirma: 'Jerez de la Frontera',
    fecha: '16/10/2025'
  },
  fieldMapping: {
    ciudadFirma: 'ciudadFirma',
    fecha: 'fecha'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoCoplanarTejaConfig = {
  id: 'certificado-coplanar-teja',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Coplanar Teja',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas en cubierta de teja coplanar',
  fileName: 'certificado-coplanar-teja.pdf',
  route: '/certificado-coplanar-teja',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'otrosDatosDireccion', label: 'Otros Datos de Dirección', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'numModulos', label: 'Número de Módulos', type: 'text' },
    { name: 'potencia', label: 'Potencia', type: 'text' },
    { name: 'peso', label: 'Peso', type: 'text' },
    { name: 'modelo', label: 'Modelo', type: 'text' },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' },
    { name: 'imagen1', label: 'Imagen 1', type: 'file', accept: 'image/*' },
    { name: 'imagen4', label: 'Imagen 4', type: 'file', accept: 'image/*' }
  ],
  defaultData: {
    direccion: ' ',
    numero: '',
    otrosDatosDireccion: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    modelo: '',
    ciudadFirma: '',
    fecha: '',
    imagen1: null,
    imagen4: null
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostal',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    ciudadFirma: 'ciudadFirma',
    fecha: 'fecha'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoCubiertaPlanAaporticadaConfig = {
  id: 'certificado-cubierta-plan-aaporticada',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Plana Aportícada',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas en cubierta plana con estructura aportícada',
  fileName: 'certificado-cubierta-plan-aaporticada.pdf',
  route: '/certificado-cubierta-plan-aaporticada',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'otrosDatosDireccion', label: 'Otros Datos de Dirección', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'numModulos', label: 'Número de Módulos', type: 'text' },
    { name: 'potencia', label: 'Potencia', type: 'text' },
    { name: 'peso', label: 'Peso', type: 'text' },
    { name: 'modelo', label: 'Modelo', type: 'text' },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' },
    { name: 'imagen1', label: 'Imagen 1', type: 'file', accept: 'image/*' }
  ],
  defaultData: {
    direccion: '',
    numero: '',
    otrosDatosDireccion: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    modelo: '',
    ciudadFirma: '',
    fecha: '',
    imagen1: null
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostal',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    ciudadFirma: 'ciudadFirma',
    fecha: 'fecha'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoAporticadaTejConfig = {
  id: 'certificado-aporticada-teja',
  title: 'Certificado de Solidez y Seguridad - Aporticada Teja',
  description: 'Certificado de solidez y seguridad de la cubierta para instalación aporticada sobre teja',
  fileName: 'certificado-aporticada-teja.pdf',
  route: '/certificado-aporticada-teja',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'cantidadModulos', label: 'Cantidad de Módulos', type: 'text' },
    { name: 'potenciaModulos', label: 'Potencia de Módulos (Wp)', type: 'text' },
    { name: 'pesoModulo', label: 'Peso por Módulo (kg)', type: 'text' },
    { name: 'fabricante', label: 'Fabricante de Módulos', type: 'text', fullWidth: true },
    { name: 'modeloPanel', label: 'Modelo de Panel', type: 'text', fullWidth: true },
    { name: 'emailIngeniero', label: 'Email del Ingeniero', type: 'text' },
    { name: 'fechaFirma', label: 'Fecha de Firma', type: 'text' },
    { name: 'localidadFirma', label: 'Localidad de Firma', type: 'text' },
    { name: 'imagen1', label: 'Imagen 1 - Estructura Aporticada', type: 'file' },
    { name: 'imagen2', label: 'Imagen 2 - Componentes', type: 'file' }
  ],
  defaultData: {
    direccion: 'Calle de la Rosa, número 11, Facinas',
    localidad: 'Tarifa',
    codigoPostal: '11380',
    provincia: 'Cádiz',
    referenciaCatastral: '7433302TF5073S0001EH',
    cantidadModulos: '6',
    potenciaModulos: '640',
    pesoModulo: '28.00',
    fabricante: 'Longi Solar',
    modeloPanel: 'LR7-72HVH-640M',
    emailIngeniero: 'rivera@solay.es',
    fechaFirma: '10 de Febrero de 2026',
    localidadFirma: 'Tarifa',
    imagen1: '',
    imagen2: ''
  },
  fieldMapping: {
    direccion: 'direccion',
    localidad: 'localidad',
    codigoPostal: 'codigoPostal',
    provincia: 'provincia',
    referenciaCatastral: 'referenciaCatastral',
    cantidadModulos: 'cantidadModulos',
    potenciaModulos: 'potenciaModulos',
    pesoModulo: 'pesoModulo',
    fabricante: 'fabricante',
    modeloPanel: 'modeloPanel',
    emailIngeniero: 'emailIngeniero',
    fechaFirma: 'fechaFirma',
    localidadFirma: 'localidadFirma',
    imagen1: 'imagen1',
    imagen2: 'imagen2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoChapasGrecadasAporticadaConfig = {
  id: 'certificado-chapas-grecadas-aporticada',
  title: 'Certificado de Solidez y Seguridad - Chapas Grecadas Aporticada',
  description: 'Certificado de solidez y seguridad de la cubierta para instalación aporticada sobre chapas grecadas',
  fileName: 'certificado-chapas-grecadas-aporticada.pdf',
  route: '/certificado-chapas-grecadas-aporticada',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'cantidadModulos', label: 'Cantidad de Módulos', type: 'text' },
    { name: 'potenciaModulos', label: 'Potencia de Módulos (Wp)', type: 'text' },
    { name: 'pesoModulo', label: 'Peso por Módulo (kg)', type: 'text' },
    { name: 'fabricanteYModelo', label: 'Fabricante y Modelo', type: 'text', fullWidth: true },
    { name: 'localidadFirma', label: 'Localidad de Firma', type: 'text' },
    { name: 'fechaFirma', label: 'Fecha de Firma', type: 'text' },
    { name: 'imagen1', label: 'Imagen - Estructura Aporticada', type: 'file' },
    { name: 'imagen2', label: 'Imagen 2 (Opcional)', type: 'file' }
  ],
  defaultData: {
    direccion: 'Calle de la Rosa',
    numero: '11',
    localidad: 'Tarifa',
    codigoPostal: '11380',
    provincia: '',
    referenciaCatastral: '7433302TF5073S0001EH',
    cantidadModulos: '6',
    potenciaModulos: '640',
    pesoModulo: '28.00',
    fabricanteYModelo: 'Longi Solar y modelo LR7-72HVH-640M',
    localidadFirma: 'Tarifa',
    fechaFirma: '10 de Febrero de 2026',
    imagen1: '',
    imagen2: ''
  },
  fieldMapping: {
    direccion: 'direccion',
    numero: 'numero',
    localidad: 'localidad',
    codigoPostal: 'codigoPostal',
    provincia: 'provincia',
    referenciaCatastral: 'referenciaCatastral',
    cantidadModulos: 'cantidadModulos',
    potenciaModulos: 'potenciaModulos',
    pesoModulo: 'pesoModulo',
    fabricanteYModelo: 'fabricanteYModelo',
    localidadFirma: 'localidadFirma',
    fechaFirma: 'fechaFirma',
    imagen1: 'imagen1',
    imagen2: 'imagen2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoParamentoVerticalConfig = {
  id: 'certificado-paramento-vertical',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Paramento Vertical',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas en paramento vertical',
  fileName: 'certificado-paramento-vertical.pdf',
  route: '/certificado-paramento-vertical',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'otrosDatosDireccion', label: 'Otros Datos de Dirección', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'cantidadModulos', label: 'Cantidad de Módulos', type: 'text' },
    { name: 'potenciaModulos', label: 'Potencia de Módulos (Wp)', type: 'text' },
    { name: 'pesoModulo', label: 'Peso por Módulo (kg)', type: 'text' },
    { name: 'fabricante', label: 'Fabricante de Módulos', type: 'text' },
    { name: 'modeloPanel', label: 'Modelo de Panel', type: 'text' },
    { name: 'fechaFirma', label: 'Fecha de Firma', type: 'text' },
    { name: 'localidadFirma', label: 'Localidad de Firma', type: 'text' },
    { name: 'imagen1', label: 'Imagen 1 - Vista paramento', type: 'file', accept: 'image/*' },
    { name: 'imagen2', label: 'Imagen 2 - Detalle anclajes', type: 'file', accept: 'image/*' }
  ],
  defaultData: {
    direccion: '',
    numero: '',
    otrosDatosDireccion: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    cantidadModulos: '',
    potenciaModulos: '',
    pesoModulo: '',
    fabricante: '',
    modeloPanel: '',
    fechaFirma: '',
    localidadFirma: '',
    imagen1: null,
    imagen2: null
  },
  fieldMapping: {
    direccion: 'direccion',
    numero: 'numero',
    codigoPostal: 'codigoPostal',
    localidad: 'localidad',
    provincia: 'provincia',
    referenciaCatastral: 'referenciaCatastral',
    cantidadModulos: 'cantidadModulos',
    potenciaModulos: 'potenciaModulos',
    pesoModulo: 'pesoModulo',
    fabricante: 'fabricante',
    modeloPanel: 'modeloPanel',
    fechaFirma: 'fechaFirma',
    localidadFirma: 'localidadFirma',
    imagen1: 'imagen1',
    imagen2: 'imagen2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoPergolaAporticadaConfig = {
  id: 'certificado-pergola-aporticada',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Pérgola Aporticada',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas sobre pérgola aporticada',
  fileName: 'certificado-pergola-aporticada.pdf',
  route: '/certificado-pergola-aporticada',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'otrosDatosDireccion', label: 'Otros Datos de Dirección', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'cantidadModulos', label: 'Cantidad de Módulos', type: 'text' },
    { name: 'potenciaModulos', label: 'Potencia de Módulos (Wp)', type: 'text' },
    { name: 'modeloPanel', label: 'Modelo de Panel', type: 'text' },
    { name: 'orientacion', label: 'Orientación', type: 'text' },
    { name: 'inclinacion', label: 'Inclinación', type: 'text' },
    { name: 'cubiertaTipo', label: 'Cubierta / del suelo', type: 'text' },
    { name: 'fechaFirma', label: 'Fecha de Firma', type: 'text' },
    { name: 'localidadFirma', label: 'Localidad de Firma', type: 'text' },
    { name: 'imagen1', label: 'Imagen 1 - Vista pérgola', type: 'file', accept: 'image/*' },
    { name: 'imagen2', label: 'Imagen 2 - Detalle anclajes', type: 'file', accept: 'image/*' }
  ],
  defaultData: {
    direccion: '',
    numero: '',
    otrosDatosDireccion: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    cantidadModulos: '',
    potenciaModulos: '',
    modeloPanel: '',
    orientacion: '',
    inclinacion: '',
    cubiertaTipo: '',
    fechaFirma: '',
    localidadFirma: '',
    imagen1: null,
    imagen2: null
  },
  fieldMapping: {
    direccion: 'direccion',
    numero: 'numero',
    codigoPostal: 'codigoPostal',
    localidad: 'localidad',
    provincia: 'provincia',
    referenciaCatastral: 'referenciaCatastral',
    cantidadModulos: 'cantidadModulos',
    potenciaModulos: 'potenciaModulos',
    modeloPanel: 'modeloPanel',
    orientacion: 'orientacion',
    inclinacion: 'inclinacion',
    cubiertaTipo: 'cubiertaTipo',
    fechaFirma: 'fechaFirma',
    localidadFirma: 'localidadFirma',
    imagen1: 'imagen1',
    imagen2: 'imagen2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const memoriaTecnicaConfig = {
  id: 'mtd-instalacion-autoconsumo-monofasica-con-bateria',
  title: 'Memoria Técnica de Instalación de Autoconsumo Monofásica con Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas en baja tensión',
  fileName: '6-MTD-INSTALACION-AUTOCONSUMO-MONOFASICA-CON-BATERIA.pdf',
  route: '/mtd-instalacion-autoconsumo-monofasica-con-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Fotovoltaica conectada a red interior',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: 'Calle Ebro',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41.012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '',
    vccMaximaInversor: '',
    vccMinimaInversor: '',
    tipoConexionInversor: '',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: 'Litio-Hierro Fosfato (LiFePO4)',
    tensionNominalBateria: '200V',
    profundidadDescargaBateria: '100%',
    tensionMaximaBateria: '57,6V',
    tensionMinimaBateria: '44,8V',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '25',
    poderCorteInterruptor: '6',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'Interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: 'Descargador',
    parteInstalacionSobretensiones: 'CGMP',
    medidaPuntoCaliente: '3 Diodos bypass',
    parteInstalacionPuntoCaliente: 'Módulo FV',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    caidaTensionReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    // No hay mappings necesarios ya que MemoriaTecnica usa los mismos nombres que el formulario maestro
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const memoriaInstalacionAisladaConBateriaConfig = {
  id: 'mtd-instalacion-aislada-con-bateria',
  title: 'Memoria Técnica de Instalación Aislada con Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas aisladas con almacenamiento',
  fileName: 'mtd-instalacion-aislada-con-bateria.pdf',
  route: '/mtd-instalacion-aislada-con-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Fotovoltaica aislada',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas ',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41.012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '20º',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '230 V',
    vccMaximaInversor: '425',
    vccMinimaInversor: '150',
    tipoConexionInversor: 'MONOFÁSICA',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: 'Litio-Hierro Fosfato (LiFePO4)',
    tensionNominalBateria: '200V',
    profundidadDescargaBateria: '100%',
    tensionMaximaBateria: '57,6V',
    tensionMinimaBateria: '44,8V',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '25',
    poderCorteInterruptor: '6',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'Interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: 'Descargador',
    parteInstalacionSobretensiones: 'Módulo FV',
    medidaPuntoCaliente: '3 Diodos bypass',
    parteInstalacionPuntoCaliente: 'Módulo FV',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    // No hay mappings necesarios ya que MemoriaTecnica usa los mismos nombres que el formulario maestro
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const memoriaTecnicaTrifasicaConBateriaConfig = {
  id: 'mtd-instalacion-autoconsumo-trifasica-con-bateria',
  title: 'Memoria Técnica de Instalación de Autoconsumo Trifásica con Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas en baja tensión (trifásica con batería)',
  fileName: '6-MTD-INSTALACION-AUTOCONSUMO-TRIFASICA-CON-BATERIA.pdf',
  route: '/mtd-instalacion-autoconsumo-trifasica-con-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: 'aaaaaaaaaaa',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Fotovoltaica conectada a red interior',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '400 V',
    vccMaximaInversor: '1100',
    vccMinimaInversor: '140',
    tipoConexionInversor: 'trifásica',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: 'Litio-Hierro Fosfato (LiFePO4)',
    tensionNominalBateria: '450V',
    profundidadDescargaBateria: '100%',
    tensionMaximaBateria: '980V',
    tensionMinimaBateria: '600V',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '',
    poderCorteInterruptor: '',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: '3 Diodos bypass',
    parteInstalacionSobretensiones: 'modulo FV',
    medidaPuntoCaliente: 'Descargador',
    parteInstalacionPuntoCaliente: 'CGMP',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    caidaTensionReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    // No hay mappings necesarios ya que MemoriaTecnica usa los mismos nombres que el formulario maestro
  },
  capabilities: { ...memoriaTecnicaConfig.capabilities }
}

export const memoriaTecnicaAutoconsumoSinBateriaConfig = {
  id: 'mtd-instalacion-autoconsumo-sin-bateria',
  title: 'Memoria Técnica de Instalación Autoconsumo Sin Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas en baja tensión (autoconsumo sin batería)',
  fileName: '6-MTD-INSTALACION-AUTOCONSUMO-SIN-BATERIA.pdf',
  route: '/mtd-instalacion-autoconsumo-sin-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Instalación Generadora Fotovoltaica',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '400 V',
    vccMaximaInversor: '1100',
    vccMinimaInversor: '140',
    tipoConexionInversor: 'trifásica',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: 'Litio-Hierro Fosfato (LiFePO4)',
    tensionNominalBateria: '450V',
    profundidadDescargaBateria: '100%',
    tensionMaximaBateria: '980V',
    tensionMinimaBateria: '600V',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '',
    poderCorteInterruptor: '',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: '3 Diodos bypass',
    parteInstalacionSobretensiones: 'modulo FV',
    medidaPuntoCaliente: 'Descargador',
    parteInstalacionPuntoCaliente: 'CGMP',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    caidaTensionReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    // No hay mappings necesarios ya que MemoriaTecnica usa los mismos nombres que el formulario maestro
  },
  capabilities: { ...memoriaTecnicaConfig.capabilities }
}

export const memoriaTecnicaPuntoRecargaConfig = {
  id: 'mtd-instalacion-puntos-recarga',
  title: 'Memoria Técnica de Instalación de Puntos de Recarga para Vehículos Eléctricos',
  description: 'Documento técnico para instalaciones de recarga de vehículos eléctricos',
  fileName: '6-MTD-INSTALACION-PUNTOS-RECARGA.pdf',
  route: '/mtd-instalacion-puntos-recarga',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Instalación con fines especiales',
    usoDestino: 'Infraestructura para la recarga de vehículos eléctricos',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '45',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // Sección E - INSTALACIÓN PARA LA RECARGA DE VEHÍCULO ELÉCTRICO
    // E.1 CARGADOR
    cargadorMarca: 'SMA EV',
    trifasica: true,
    potenciaInstalada: '22',
    potenciaPrevisita: '22',
    tipoInstalacionRecarga: 'INTERIOR',
    modoCarga: 'Modo 3 (IEC 61851-)',
    tipoConector: '2',
    // E.3 CUADRO DE MANDO Y PROTECCIÓN
    interruptorGeneralAmperaje: '',
    interruptorDiferencialAmperaje: '',
    interruptorDiferencialSensibilidad: '',
    descargadorSobretensiones: 'Sí',
    puestaATierra: 'Según normas',
    // Sección F - CARACTERÍSTICAS DE LÍNEAS Y CIRCUITOS
    potenciaPrevistaCuadroPrincipal: '',
    longitudCuadroPrincipal: '10',
    materialConductor: '6',
    intensidadAdmisible: '49',
    caidaTension: '< 1,5 %',
    // Sección G - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección H - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    // No hay mappings necesarios ya que MemoriaTecnica usa los mismos nombres que el formulario maestro
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const declaracionNoGeneracionRcdsConfig = {
  id: 'declaracion-no-generacion-rcds',
  title: 'Declaración Responsable de No Generación de RCDs',
  description: 'Declaración de no generación de residuos de construcción y demolición',
  fileName: 'declaracion-no-generacion-rcds.pdf',
  route: '/declaracion-no-generacion-rcds',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'otrosDatos', label: 'Otros Datos', type: 'text', fullWidth: true },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'municipio', label: 'Municipio', type: 'text' },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' }
  ],
  defaultData: {
    direccion: '',
    numero: '',
    otrosDatos: '',
    codigoPostal: '',
    referenciaCatastral: '',
    municipio: '',
    ciudadFirma: '',
    fecha: ''
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostal',
    municipio: 'localidadEmplazamiento',
    referenciaCatastral: 'referenciaCatastral',
    ciudadFirma: 'ciudadFirma',
    fecha: 'fecha'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const planosPlanosSituacionEmplazamientoCubiertaConfig = {
  id: 'planos-situacion-emplazamiento-cubierta',
  title: 'Planos de Situación, Emplazamiento y Cubierta',
  description: 'Documento con planos de ubicación, emplazamiento y disposición de módulos fotovoltaicos',
  fileName: 'planos-situacion-emplazamiento-cubierta.pdf',
  route: '/planos-situacion-emplazamiento-cubierta',
  defaultData: {
    pse_promotor: '',
    pse_nif: '',
    pse_direccion: '',
    pse_numero: '',
    pse_localidad: '',
    pse_codigoPostal: '',
    pse_provincia: '',
    pse_referenciaCatastral: '',
    pse_potenciaKw: '',
    pse_tipoInstalacion: '',
    pse_potenciaPicoGenerador: '',
    pse_totalModulos: '',
    pse_potenciaModulos: '',
    pse_disposicionModulos: '',
    pse_fecha: '',
    pse_autorProyecto: 'Eduardo Rivera Cabezas',
    pse_tituloDescriptivo: 'Instalación Solar Fotovoltaica',
    pse_tipo: '',
    pse_potencia: '',
    pse_descripcion: ''
  },
  fieldMapping: {
    pse_promotor: 'apellidosNombre',
    pse_nif: 'nifCif',
    pse_direccion: 'emplazamientoCalle',
    pse_numero: 'numero',
    pse_localidad: 'localidadEmplazamiento',
    pse_codigoPostal: 'codigoPostal',
    pse_provincia: 'provinciaEmplazamiento',
    pse_referenciaCatastral: 'referenciaCatastral',
    pse_potenciaKw: 'potenciaKw',
    pse_tipoInstalacion: 'tipoInstalacionSeleccionada',
    pse_potenciaPicoGenerador: 'potenciaPicoGenerador',
    pse_totalModulos: 'totalModulos',
    pse_potenciaModulos: 'potenciaModulos',
    pse_disposicionModulos: 'disposicionModulos',
    pse_fecha: 'fecha',
    pse_autorProyecto: 'nombreTecnicoCompetente',
    pse_tipo: 'otros_tipoInstalacion',
    pse_potencia: 'e2_potenciaNominalInversores',
    pse_descripcion: 'otros_descripcionProyecto',
    pse_imagenSituacion: 'otros_imagenPlanoSituacion',
    pse_imagenEmplazamiento: 'otros_imagenPlanoEmplazamiento',
    pse_imagenCubierta: 'otros_imagenPlanoCubierta'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

/**
 * Objeto que contiene todas las configuraciones de documentos
 */
const documentConfigs = {
  'autorizacion-representacion': autorizacionRepresentacionConfig,
  'declaracion-habilitacion-profesional': declaracionHabilitacionProfesionalConfig,
  'declaracion-no-generacion-rcds': declaracionNoGeneracionRcdsConfig,
  'certificado-coplanar-teja': certificadoCoplanarTejaConfig,
  'certificado-cubierta-plan-aaporticada': certificadoCubiertaPlanAaporticadaConfig,
  'certificado-aporticada-teja': certificadoAporticadaTejConfig,
  'certificado-paramento-vertical': certificadoParamentoVerticalConfig,
  'certificado-chapas-grecadas-aporticada': certificadoChapasGrecadasAporticadaConfig,
  'certificado-pergola-aporticada': certificadoPergolaAporticadaConfig,
  'mtd-instalacion-autoconsumo-monofasica-con-bateria': memoriaTecnicaConfig,
  'mtd-instalacion-aislada-con-bateria': memoriaInstalacionAisladaConBateriaConfig,
  'mtd-instalacion-autoconsumo-trifasica-con-bateria': memoriaTecnicaTrifasicaConBateriaConfig,
  'mtd-instalacion-autoconsumo-sin-bateria': memoriaTecnicaAutoconsumoSinBateriaConfig,
  'mtd-instalacion-puntos-recarga': memoriaTecnicaPuntoRecargaConfig,
  'planos-situacion-emplazamiento-cubierta': planosPlanosSituacionEmplazamientoCubiertaConfig
}

/**
 * Obtener configuración de un documento por ID
 */
export const getDocumentConfig = (documentId) => {
  // Primero intentar por clave directa (para compatibilidad con aliases)
  if (documentConfigs[documentId]) return documentConfigs[documentId]

  // Si no existe, buscar por el campo `id` dentro de las configuraciones
  const found = Object.values(documentConfigs).find(cfg => cfg.id === documentId)
  return found || null
}

/**
 * Obtener lista de todos los documentos disponibles
 * Devuelve una lista sin duplicados (se agrupan por `config.id`)
 */
export const getAllDocuments = () => {
  const seen = new Set()
  const list = []

  for (const cfg of Object.values(documentConfigs)) {
    const uniqueId = cfg.id || cfg.route || cfg.fileName
    if (seen.has(uniqueId)) continue
    seen.add(uniqueId)
    list.push({ id: uniqueId, ...cfg })
  }

  return list
}
