export const autorizacionRepresentacionConfig = {
  id: 'autorizacion-representacion',
  title: 'Autorización de Representación',
  description: 'Documento válido para trámites administrativos',
  fileName: 'autorizacion-representacion.pdf',
  route: '/autorizacion-representacion',
  fields: [
    { name: 'autorizante', label: 'Nombre del Autorizante', type: 'text', fullWidth: true },
    { name: 'dniAutorizante', label: 'DNI/NIF del Autorizante', type: 'text' },
    { name: 'domicilioAutorizante', label: 'Domicilio del Autorizante', type: 'text', fullWidth: true },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'representante', label: 'Representante', type: 'text', fullWidth: true },
    { name: 'dniRepresentante', label: 'DNI/NIF del Representante', type: 'text' },
    { name: 'domicilioRepresentante', label: 'Domicilio del Representante', type: 'text', fullWidth: true },
    { name: 'organismo', label: 'Organismo', type: 'text', fullWidth: true },
    { name: 'gestiones', label: 'Gestiones a Realizar', type: 'textarea', rows: 3, fullWidth: true },
    { name: 'fecha', label: 'Fecha', type: 'date' }
  ],
  defaultData: {
    autorizante: '',
    dniAutorizante: '',
    domicilioAutorizante: '',
    localidad: '',
    provincia: '',
    representante: 'Solay Ingenieros, S.L.',
    dniRepresentante: 'B09848912',
    domicilioRepresentante: 'Calle Ebro, 35 – 41012, Sevilla, Sevilla',
    organismo: '',
    gestiones: 'SOLICITUD DE LICENCIA DE OBRA MENOR CON DECLARACIÓN RESPONSABLE O AUTORIZACIÓN URBANÍSTICA',
    fecha: '18/11/2025'
  },
  fieldMapping: {
    autorizante: 'apellidosNombre',
    dniAutorizante: 'nifCif',
    domicilioAutorizante: 'emplazamientoCalle',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    organismo: 'localidadEmplazamiento',
    fecha: 'fecha'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const declaracionHabilitacionProfesionalConfig = {
  id: 'declaracion-habilitacion-profesional',
  title: 'Declaración Responsable de Habilitación Profesional',
  description: 'Documento de declaración de habilitación profesional para colegiados',
  fileName: 'declaracion-habilitacion-profesional.pdf',
  route: '/declaracion-habilitacion-profesional',
  fields: [
    { name: 'nombreProfesional', label: 'Nombre del Profesional', type: 'text', fullWidth: true },
    { name: 'nifProfesional', label: 'NIF del Profesional', type: 'text' },
    { name: 'profesionTitulo', label: 'Título Profesional', type: 'text', fullWidth: true },
    { name: 'numeroColegiado', label: 'Número de Colegiado', type: 'text' },
    { name: 'nombreColegio', label: 'Nombre del Colegio', type: 'text', fullWidth: true },
    { name: 'domicilioProfesional', label: 'Domicilio Profesional', type: 'text', fullWidth: true },
    { name: 'codigoPostalProfesional', label: 'Código Postal', type: 'text' },
    { name: 'localidadProfesional', label: 'Localidad', type: 'text' },
    { name: 'provinciaProfesional', label: 'Provincia', type: 'text' },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' }
  ],
  defaultData: {
    nombreProfesional: 'Eduardo Rivera Cabezas',
    nifProfesional: '28.818.007-L',
    profesionTitulo: 'Ingeniero Industrial',
    numeroColegiado: '4654',
    nombreColegio: 'Colegio Oficial de Ingenieros Industriales de Andalucía Occidental',
    domicilioProfesional: 'Calle El Peñón 5',
    codigoPostalProfesional: '41940',
    localidadProfesional: 'Tomares',
    provinciaProfesional: 'Sevilla',
    ciudadFirma: 'Jerez de la Frontera',
    fecha: '16/10/2025'
  },
  fieldMapping: {
    ciudadFirma: 'localidadEmplazamiento',
    fecha: 'fecha'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoCoplanarTejaConfig = {
  id: 'certificado-coplanar-teja',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Coplanar Teja',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas en cubierta de teja coplanar',
  fileName: 'certificado-coplanar-teja.pdf',
  route: '/certificado-coplanar-teja',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'otrosDatosDireccion', label: 'Otros Datos de Dirección', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'numModulos', label: 'Número de Módulos', type: 'text' },
    { name: 'potencia', label: 'Potencia', type: 'text' },
    { name: 'peso', label: 'Peso', type: 'text' },
    { name: 'marcaModelo', label: 'Marca y Modelo', type: 'text', fullWidth: true },
    { name: 'modelo', label: 'Modelo', type: 'text' },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' },
    { name: 'foto1', label: 'Foto Certificado 1', type: 'file', accept: 'image/*,.pdf' },
    { name: 'foto2', label: 'Foto Certificado 2', type: 'file', accept: 'image/*,.pdf' }
  ],
  defaultData: {
    direccion: ' ',
    numero: '',
    otrosDatosDireccion: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    marcaModelo: '',
    modelo: '',
    ciudadFirma: '',
    fecha: '',
    foto1: null,
    foto2: null
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    numModulos: 'e2_totalModulos',
    potencia: 'e2_potenciaPicoModulo',
    peso: 'peso',
    marcaModelo: 'e2_marcaModeloModulo',
    ciudadFirma: 'localidadEmplazamiento',
    fecha: 'fecha',
    foto1: 'otros_foto1',
    foto2: 'otros_foto2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoCubiertaPlanAaporticadaConfig = {
  id: 'certificado-cubierta-plan-aaporticada',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Plana Aportícada',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas en cubierta plana con estructura aportícada',
  fileName: 'certificado-cubierta-plan-aaporticada.pdf',
  route: '/certificado-cubierta-plan-aaporticada',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'otrosDatosDireccion', label: 'Otros Datos de Dirección', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'numModulos', label: 'Número de Módulos', type: 'text' },
    { name: 'potencia', label: 'Potencia', type: 'text' },
    { name: 'peso', label: 'Peso', type: 'text' },
    { name: 'marcaModelo', label: 'Marca y Modelo', type: 'text', fullWidth: true },
    { name: 'modelo', label: 'Modelo', type: 'text' },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' },
    { name: 'foto1', label: 'Foto Certificado 1', type: 'file', accept: 'image/*,.pdf' },
    { name: 'foto2', label: 'Foto Certificado 2', type: 'file', accept: 'image/*,.pdf' }
  ],
  defaultData: {
    direccion: ' ',
    numero: '',
    otrosDatosDireccion: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    marcaModelo: '',
    modelo: '',
    ciudadFirma: '',
    fecha: '',
    foto1: null,
    foto2: null
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    numModulos: 'e2_totalModulos',
    potencia: 'e2_potenciaPicoModulo',
    peso: 'peso',
    marcaModelo: 'e2_marcaModeloModulo',
    ciudadFirma: 'ciudadFirma',
    fecha: 'fecha',
    foto1: 'otros_foto1',
    foto2: 'otros_foto2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoAporticadaTejConfig = {
  id: 'certificado-aporticada-teja',
  title: 'Certificado de Solidez y Seguridad - Aporticada Teja',
  description: 'Certificado de solidez y seguridad de la cubierta para instalación aporticada sobre teja',
  fileName: 'certificado-aporticada-teja.pdf',
  route: '/certificado-aporticada-teja',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'numModulos', label: 'Número de Módulos', type: 'text' },
    { name: 'potencia', label: 'Potencia', type: 'text' },
    { name: 'peso', label: 'Peso', type: 'text' },
    { name: 'marcaModelo', label: 'Marca y Modelo', type: 'text', fullWidth: true },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' },
    { name: 'foto1', label: 'Foto Certificado 1', type: 'file', accept: 'image/*,.pdf' },
    { name: 'foto2', label: 'Foto Certificado 2', type: 'file', accept: 'image/*,.pdf' }
  ],
  defaultData: {
    direccion: ' ',
    numero: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    marcaModelo: '',
    ciudadFirma: '',
    fecha: '',
    foto1: null,
    foto2: null
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    numModulos: 'e2_totalModulos',
    potencia: 'e2_potenciaPicoModulo',
    peso: 'peso',
    marcaModelo: 'e2_marcaModeloModulo',
    ciudadFirma: 'ciudadFirma',
    fecha: 'fecha',
    foto1: 'otros_foto1',
    foto2: 'otros_foto2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoChapasGrecadasAporticadaConfig = {
  id: 'certificado-chapas-grecadas-aporticada',
  title: 'Certificado de Solidez y Seguridad - Chapas Grecadas Aporticada',
  description: 'Certificado de solidez y seguridad de la cubierta para instalación aporticada sobre chapas grecadas',
  fileName: 'certificado-chapas-grecadas-aporticada.pdf',
  route: '/certificado-chapas-grecadas-aporticada',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'numModulos', label: 'Número de Módulos', type: 'text' },
    { name: 'potencia', label: 'Potencia', type: 'text' },
    { name: 'peso', label: 'Peso', type: 'text' },
    { name: 'marcaModelo', label: 'Marca y Modelo', type: 'text', fullWidth: true },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' },
    { name: 'foto1', label: 'Foto Certificado 1', type: 'file', accept: 'image/*,.pdf' },
    { name: 'foto2', label: 'Foto Certificado 2', type: 'file', accept: 'image/*,.pdf' }
  ],
  defaultData: {
    direccion: ' ',
    numero: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    marcaModelo: '',
    ciudadFirma: '',
    fecha: '',
    foto1: null,
    foto2: null
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    numModulos: 'e2_totalModulos',
    potencia: 'e2_potenciaPicoModulo',
    peso: 'peso',
    marcaModelo: 'e2_marcaModeloModulo',
    ciudadFirma: 'ciudadFirma',
    fecha: 'fecha',
    foto1: 'otros_foto1',
    foto2: 'otros_foto2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoParamentoVerticalConfig = {
  id: 'certificado-paramento-vertical',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Paramento Vertical',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas en paramento vertical',
  fileName: 'certificado-paramento-vertical.pdf',
  route: '/certificado-paramento-vertical',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'numModulos', label: 'Número de Módulos', type: 'text' },
    { name: 'potencia', label: 'Potencia', type: 'text' },
    { name: 'peso', label: 'Peso', type: 'text' },
    { name: 'marcaModelo', label: 'Marca y Modelo', type: 'text', fullWidth: true },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' },
    { name: 'foto1', label: 'Foto Certificado 1', type: 'file', accept: 'image/*,.pdf' },
    { name: 'foto2', label: 'Foto Certificado 2', type: 'file', accept: 'image/*,.pdf' }
  ],
  defaultData: {
    direccion: ' ',
    numero: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    marcaModelo: '',
    ciudadFirma: '',
    fecha: '',
    foto1: null,
    foto2: null
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    numModulos: 'e2_totalModulos',
    potencia: 'e2_potenciaPicoModulo',
    peso: 'peso',
    marcaModelo: 'e2_marcaModeloModulo',
    ciudadFirma: 'ciudadFirma',
    fecha: 'fecha',
    foto1: 'otros_foto1',
    foto2: 'otros_foto2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoPergolaAporticadaConfig = {
  id: 'certificado-pergola-aporticada',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Pérgola Aporticada',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas sobre pérgola aporticada',
  fileName: 'certificado-pergola-aporticada.pdf',
  route: '/certificado-pergola-aporticada',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'numModulos', label: 'Número de Módulos', type: 'text' },
    { name: 'potencia', label: 'Potencia', type: 'text' },
    { name: 'peso', label: 'Peso', type: 'text' },
    { name: 'marcaModelo', label: 'Marca y Modelo', type: 'text', fullWidth: true },
    { name: 'orientacion', label: 'Orientación', type: 'text' },
    { name: 'inclinacion', label: 'Inclinación', type: 'text' },
    { name: 'cubiertaTipo', label: 'Cubierta / del suelo', type: 'text' },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' },
    { name: 'foto1', label: 'Foto Certificado 1', type: 'file', accept: 'image/*,.pdf' },
    { name: 'foto2', label: 'Foto Certificado 2', type: 'file', accept: 'image/*,.pdf' }
  ],
  defaultData: {
    direccion: ' ',
    numero: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    marcaModelo: '',
    orientacion: '',
    inclinacion: '',
    cubiertaTipo: '',
    ciudadFirma: '',
    fecha: '',
    foto1: null,
    foto2: null
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    referenciaCatastral: 'referenciaCatastral',
    numModulos: 'e2_totalModulos',
    potencia: 'e2_potenciaPicoModulo',
    peso: 'peso',
    marcaModelo: 'e2_marcaModeloModulo',
    orientacion: 'orientacion',
    inclinacion: 'inclinacion',
    cubiertaTipo: 'cubiertaTipo',
    ciudadFirma: 'localidadEmplazamiento',
    fecha: 'fecha',
    foto1: 'otros_foto1',
    foto2: 'otros_foto2'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const memoriaTecnicaConfig = {
  id: 'mtd-instalacion-autoconsumo-monofasica-con-bateria',
  title: 'Memoria Técnica de Instalación de Autoconsumo Monofásica con Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas en baja tensión',
  fileName: '6-MTD-INSTALACION-AUTOCONSUMO-MONOFASICA-CON-BATERIA.pdf',
  route: '/mtd-instalacion-autoconsumo-monofasica-con-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    puerta: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Fotovoltaica conectada a red interior',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41.012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '',
    vccMaximaInversor: '',
    vccMinimaInversor: '',
    tipoConexionInversor: '',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: '',
    tensionNominalBateria: '',
    profundidadDescargaBateria: '',
    tensionMaximaBateria: '',
    tensionMinimaBateria: '',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '25',
    poderCorteInterruptor: '6',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'Interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: 'Descargador',
    parteInstalacionSobretensiones: 'CGMP',
    medidaPuntoCaliente: '3 Diodos bypass',
    parteInstalacionPuntoCaliente: 'Módulo FV',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    caidaTensionReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    domicilio: 'emplazamientoCalle',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    correoElectronico: 'correoElectronicoEmplazamiento',
    telefono: 'telefono',
    // E2.1 - Conexión a la Red
    potenciaNominalInversores: 'e2_potenciaNominalInversores',
    tipoConexionRed: 'e2_tipoConexionRed',
    // E2.2 - Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'e2_tecnologiaCelulaModulo',
    marcaModeloModulo: 'e2_marcaModeloModulo',
    potenciaPicoModulo: 'e2_potenciaPicoModulo',
    toncModulo: 'e2_toncModulo',
    // E2.3 - Generador Fotovoltaico
    potenciaPicoGenerador: 'e2_potenciaPicoGenerador',
    tensionVpmpGenerador: 'e2_tensionVpmpGenerador',
    orientacionGenerador: 'e2_orientacionGenerador',
    inclinacionGenerador: 'e2_inclinacionGenerador',
    totalModulos: 'e2_totalModulos',
    modulosEnSerie: 'e2_modulosEnSerie',
    // E2.4 - Inversor E2
    marcaModeloInversor: 'e2_marcaModeloInversor',
    potenciaACInversor: 'e2_potenciaNominalInversor',
    tensionNominalInversor: 'e2_relacionTensionInversor',
    vccMaximaInversor: 'e2_formaOndaSalidaInversor',
    vccMinimaInversor: 'e2_frecuenciaNominalInversor',
    tipoConexionInversor: 'e2_tensionMaximaEntradaInversor',
    // E2.5 - Grupo Auxiliar
    marcaModeloBateria: 'e2_marcaModelo',
    tipoBateria: 'e2_tipoDeBateria',
    tensionNominalBateria: 'e2_tensionNominal',
    profundidadDescargaBateria: 'e2_profundidadDescarga',
    tensionMaximaBateria: 'e2_tensionMaxima',
    tensionMinimaBateria: 'e2_tensionMinima',
    energiaTotalBateria: 'e2_energiaTotal',
    potenciaMaximaSalidaBateria: 'e2_potenciaMaximaSalida',
    maximoPicoPotenciaBateria: 'e2_maximoPicoDePotencia',
    // E2.5.1 - Protecciones Externas
    intensidadInterruptorGeneral: 'e2_intensidadNominalInterruptor',
    poderCorteInterruptor: 'e2_poderCorteInterruptor',
    // G - Características de Líneas y Circuitos
    potenciaBateriaInversor: 'g_bateriaDiRectaInversorPotencia',
    potenciaGeneradorInversorDirecto: 'g_generadorDirectoInversorPotencia',
    potenciaSalidaInversorRed: 'g_inversorRedPotencia',
    // H - Esquema Unifilar
    esquemaUnifilar: 'h_esquemaUnifilar',
    // I - Plano de Emplazamiento
    planoEmplazamiento: 'otros_imagenPlanoEmplazamiento'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const memoriaInstalacionAisladaConBateriaConfig = {
  id: 'mtd-instalacion-aislada-con-bateria',
  title: 'Memoria Técnica de Instalación Aislada con Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas aisladas con almacenamiento',
  fileName: 'mtd-instalacion-aislada-con-bateria.pdf',
  route: '/mtd-instalacion-aislada-con-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Fotovoltaica aislada',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas ',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41.012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '20º',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: 'e2_marcaModeloInversor',
    potenciaACInversor: 'e2_potenciaNominalInversor',
    tensionNominalInversor: 'e2_relacionTensionInversor',
    vccMaximaInversor: 'e2_formaOndaSalidaInversor',
    vccMinimaInversor: 'e2_frecuenciaNominalInversor',
    tipoConexionInversor: 'e2_tensionMaximaEntradaInversor',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: '',
    tensionNominalBateria: '',
    profundidadDescargaBateria: '',
    tensionMaximaBateria: '',
    tensionMinimaBateria: '',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '25',
    poderCorteInterruptor: '6',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'Interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: 'Descargador',
    parteInstalacionSobretensiones: 'Módulo FV',
    medidaPuntoCaliente: '3 Diodos bypass',
    parteInstalacionPuntoCaliente: 'Módulo FV',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    // Sección A - TITULAR
    domicilio: 'emplazamientoCalle',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    correoElectronico: 'correoElectronicoEmplazamiento',
    telefono: 'telefono',
    // E2.1 - Conexión a la Red
    potenciaNominalInversores: 'e2_potenciaNominalInversores',
    tipoConexionRed: 'e2_tipoConexionRed',
    // E2.2 - Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'e2_tecnologiaCelulaModulo',
    marcaModeloModulo: 'e2_marcaModeloModulo',
    potenciaPicoModulo: 'e2_potenciaPicoModulo',
    toncModulo: 'e2_toncModulo',
    // E2.3 - Generador Fotovoltaico
    potenciaPicoGenerador: 'e2_potenciaPicoGenerador',
    tensionVpmpGenerador: 'e2_tensionVpmpGenerador',
    orientacionGenerador: 'e2_orientacionGenerador',
    inclinacionGenerador: 'e2_inclinacionGenerador',
    totalModulos: 'e2_totalModulos',
    modulosEnSerie: 'e2_modulosEnSerie',
    // E2.4 - Inversor E2
    marcaModeloInversor: 'e2_marcaModeloInversor',
    potenciaACInversor: 'e2_potenciaNominalInversor',
    tensionNominalInversor: 'e2_relacionTensionInversor',
    vccMaximaInversor: 'e2_formaOndaSalidaInversor',
    vccMinimaInversor: 'e2_frecuenciaNominalInversor',
    tipoConexionInversor: 'e2_tensionMaximaEntradaInversor',
    // E2.5 - Grupo Auxiliar
    marcaModeloBateria: 'e2_marcaModelo',
    tipoBateria: 'e2_tipoDeBateria',
    tensionNominalBateria: 'e2_tensionNominal',
    profundidadDescargaBateria: 'e2_profundidadDescarga',
    tensionMaximaBateria: 'e2_tensionMaxima',
    tensionMinimaBateria: 'e2_tensionMinima',
    energiaTotalBateria: 'e2_energiaTotal',
    potenciaMaximaSalidaBateria: 'e2_potenciaMaximaSalida',
    maximoPicoPotenciaBateria: 'e2_maximoPicoDePotencia',
    intensidadInterruptorGeneral: 'e2_intensidadNominalInterruptor',
    poderCorteInterruptor: 'e2_poderCorteInterruptor',
    // G - Características de Líneas y Circuitos
    potenciaBateriaInversor: 'g_bateriaDiRectaInversorPotencia',
    potenciaGeneradorInversorDirecto: 'g_generadorDirectoInversorPotencia',
    potenciaSalidaInversorRed: 'g_inversorRedPotencia',
    // H - Esquema Unifilar
    esquemaUnifilar: 'h_esquemaUnifilar',
    // I - Plano de Emplazamiento
    planoEmplazamiento: 'otros_imagenPlanoEmplazamiento'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const memoriaTecnicaTrifasicaConBateriaConfig = {
  id: 'mtd-instalacion-autoconsumo-trifasica-con-bateria',
  title: 'Memoria Técnica de Instalación de Autoconsumo Trifásica con Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas en baja tensión (trifásica con batería)',
  fileName: '6-MTD-INSTALACION-AUTOCONSUMO-TRIFASICA-CON-BATERIA.pdf',
  route: '/mtd-instalacion-autoconsumo-trifasica-con-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: 'aaaaaaaaaaa',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    puerta: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Fotovoltaica conectada a red interior',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '',
    vccMaximaInversor: '',
    vccMinimaInversor: '',
    tipoConexionInversor: '',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: '',
    tensionNominalBateria: '',
    profundidadDescargaBateria: '',
    tensionMaximaBateria: '',
    tensionMinimaBateria: '',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '25',
    poderCorteInterruptor: '6',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: '3 Diodos bypass',
    parteInstalacionSobretensiones: 'modulo FV',
    medidaPuntoCaliente: 'Descargador',
    parteInstalacionPuntoCaliente: 'CGMP',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    caidaTensionReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    // Sección A - TITULAR
    domicilio: 'emplazamientoCalle',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    correoElectronico: 'correoElectronicoEmplazamiento',
    telefono: 'telefono',
    // E2.1 - Conexión a la Red
    potenciaNominalInversores: 'e2_potenciaNominalInversores',
    tipoConexionRed: 'e2_tipoConexionRed',
    // E2.2 - Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'e2_tecnologiaCelulaModulo',
    marcaModeloModulo: 'e2_marcaModeloModulo',
    potenciaPicoModulo: 'e2_potenciaPicoModulo',
    toncModulo: 'e2_toncModulo',
    // E2.3 - Generador Fotovoltaico
    potenciaPicoGenerador: 'e2_potenciaPicoGenerador',
    tensionVpmpGenerador: 'e2_tensionVpmpGenerador',
    orientacionGenerador: 'e2_orientacionGenerador',
    inclinacionGenerador: 'e2_inclinacionGenerador',
    totalModulos: 'e2_totalModulos',
    modulosEnSerie: 'e2_modulosEnSerie',
    // E2.4 - Inversor E2
    marcaModeloInversor: 'e2_marcaModeloInversor',
    potenciaACInversor: 'e2_potenciaNominalInversor',
    tensionNominalInversor: 'e2_relacionTensionInversor',
    vccMaximaInversor: 'e2_formaOndaSalidaInversor',
    vccMinimaInversor: 'e2_frecuenciaNominalInversor',
    tipoConexionInversor: 'e2_tensionMaximaEntradaInversor',
    // E2.5 - Baterias
    marcaModeloBateria: 'e2_marcaModelo',
    tipoBateria: 'e2_tipoDeBateria',
    tensionNominalBateria: 'e2_tensionNominal',
    profundidadDescargaBateria: 'e2_profundidadDescarga',
    tensionMaximaBateria: 'e2_tensionMaxima',
    tensionMinimaBateria: 'e2_tensionMinima',
    energiaTotalBateria: 'e2_energiaTotal',
    potenciaMaximaSalidaBateria: 'e2_potenciaMaximaSalida',
    maximoPicoPotenciaBateria: 'e2_maximoPicoDePotencia',
    // E2.5.1 - Protecciones Externas
    intensidadInterruptorGeneral: 'e2_intensidadNominalInterruptor',
    poderCorteInterruptor: 'e2_poderCorteInterruptor',
    // G - Características de Líneas y Circuitos
    potenciaBateriaInversor: 'g_bateriaDiRectaInversorPotencia',
    potenciaGeneradorInversorDirecto: 'g_generadorDirectoInversorPotencia',
    potenciaSalidaInversorRed: 'g_inversorRedPotencia',
    // H - Esquema Unifilar
    esquemaUnifilar: 'h_esquemaUnifilar',
    // I - Plano de Emplazamiento
    planoEmplazamiento: 'otros_imagenPlanoEmplazamiento'
  },
  capabilities: { ...memoriaTecnicaConfig.capabilities }
}

export const memoriaTecnicaAutoconsumoSinBateriaConfig = {
  id: 'mtd-instalacion-autoconsumo-sin-bateria',
  title: 'Memoria Técnica de Instalación Autoconsumo Sin Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas en baja tensión (autoconsumo sin batería)',
  fileName: '6-MTD-INSTALACION-AUTOCONSUMO-SIN-BATERIA.pdf',
  route: '/mtd-instalacion-autoconsumo-sin-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    puerta: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Instalación Generadora Fotovoltaica',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '',
    vccMaximaInversor: '',
    vccMinimaInversor: '',
    tipoConexionInversor: '',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: '',
    tensionNominalBateria: '',
    profundidadDescargaBateria: '',
    tensionMaximaBateria: '',
    tensionMinimaBateria: '',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '25',
    poderCorteInterruptor: '6',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: '3 Diodos bypass',
    parteInstalacionSobretensiones: 'modulo FV',
    medidaPuntoCaliente: 'Descargador',
    parteInstalacionPuntoCaliente: 'CGMP',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    caidaTensionReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    // Sección A - TITULAR
    domicilio: 'emplazamientoCalle',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    correoElectronico: 'correoElectronicoEmplazamiento',
    telefono: 'telefono',
    // E2.1 - Conexión a la Red
    potenciaNominalInversores: 'e2_potenciaNominalInversores',
    tipoConexionRed: 'e2_tipoConexionRed',
    // E2.2 - Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'e2_tecnologiaCelulaModulo',
    marcaModeloModulo: 'e2_marcaModeloModulo',
    potenciaPicoModulo: 'e2_potenciaPicoModulo',
    toncModulo: 'e2_toncModulo',
    // E2.3 - Generador Fotovoltaico
    potenciaPicoGenerador: 'e2_potenciaPicoGenerador',
    tensionVpmpGenerador: 'e2_tensionVpmpGenerador',
    orientacionGenerador: 'e2_orientacionGenerador',
    inclinacionGenerador: 'e2_inclinacionGenerador',
    totalModulos: 'e2_totalModulos',
    modulosEnSerie: 'e2_modulosEnSerie',
    // E2.4 - Inversor E2
    marcaModeloInversor: 'e2_marcaModeloInversor',
    potenciaACInversor: 'e2_potenciaNominalInversor',
    tensionNominalInversor: 'e2_relacionTensionInversor',
    vccMaximaInversor: 'e2_formaOndaSalidaInversor',
    vccMinimaInversor: 'e2_frecuenciaNominalInversor',
    tipoConexionInversor: 'e2_tensionMaximaEntradaInversor',
    // E2.5 - Baterias
    marcaModeloBateria: 'e2_marcaModelo',
    tipoBateria: 'e2_tipoDeBateria',
    tensionNominalBateria: 'e2_tensionNominal',
    profundidadDescargaBateria: 'e2_profundidadDescarga',
    tensionMaximaBateria: 'e2_tensionMaxima',
    tensionMinimaBateria: 'e2_tensionMinima',
    energiaTotalBateria: 'e2_energiaTotal',
    potenciaMaximaSalidaBateria: 'e2_potenciaMaximaSalida',
    maximoPicoPotenciaBateria: 'e2_maximoPicoDePotencia',
    // E2.5.1 - Protecciones Externas
    intensidadInterruptorGeneral: 'e2_intensidadNominalInterruptor',
    poderCorteInterruptor: 'e2_poderCorteInterruptor',
    // G - Características de Líneas y Circuitos
    potenciaBateriaInversor: 'g_bateriaDiRectaInversorPotencia',
    potenciaGeneradorInversorDirecto: 'g_generadorDirectoInversorPotencia',
    potenciaSalidaInversorRed: 'g_inversorRedPotencia',
    // H - Esquema Unifilar
    esquemaUnifilar: 'h_esquemaUnifilar',
    // I - Plano de Emplazamiento
    planoEmplazamiento: 'otros_imagenPlanoEmplazamiento'
  },
  capabilities: { ...memoriaTecnicaConfig.capabilities }
}

export const memoriaTecnicaPuntoRecargaConfig = {
  id: 'mtd-instalacion-puntos-recarga',
  title: 'Memoria Técnica de Instalación de Puntos de Recarga para Vehículos Eléctricos',
  description: 'Documento técnico para instalaciones de recarga de vehículos eléctricos',
  fileName: '6-MTD-INSTALACION-PUNTOS-RECARGA.pdf',
  route: '/mtd-instalacion-puntos-recarga',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    puerta: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Instalación con fines especiales',
    usoDestino: 'Infraestructura para la recarga de vehículos eléctricos',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // Sección E - INSTALACIÓN PARA LA RECARGA DE VEHÍCULO ELÉCTRICO
    // E.1 CARGADOR
    cargadorMarca: 'SMA EV',
    trifasica: true,
    potenciaInstalada: '22',
    potenciaPrevisita: '22',
    tipoInstalacionRecarga: 'INTERIOR',
    modoCarga: 'Modo 3 (IEC 61851-)',
    tipoConector: '2',
    // E.3 CUADRO DE MANDO Y PROTECCIÓN
    interruptorGeneralAmperaje: '',
    interruptorDiferencialAmperaje: '',
    interruptorDiferencialSensibilidad: '',
    descargadorSobretensiones: 'Sí',
    puestaATierra: 'Según normas',
    // Sección F - CARACTERÍSTICAS DE LÍNEAS Y CIRCUITOS
    potenciaPrevistaCuadroPrincipal: '',
    longitudCuadroPrincipal: '10',
    materialConductor: '6',
    intensidadAdmisible: '49',
    caidaTension: '< 1,5 %',
    // Sección G - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección H - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  fieldMapping: {
    // Sección A - TITULAR
    domicilio: 'emplazamientoCalle',
    codigoPostal: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    correoElectronico: 'correoElectronicoEmplazamiento',
    telefono: 'telefono',
    // E2.1 - Conexión a la Red
    potenciaNominalInversores: 'e2_potenciaNominalInversores',
    tipoConexionRed: 'e2_tipoConexionRed',
    // E2.2 - Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'e2_tecnologiaCelulaModulo',
    marcaModeloModulo: 'e2_marcaModeloModulo',
    potenciaPicoModulo: 'e2_potenciaPicoModulo',
    toncModulo: 'e2_toncModulo',
    // E2.3 - Generador Fotovoltaico
    potenciaPicoGenerador: 'e2_potenciaPicoGenerador',
    tensionVpmpGenerador: 'e2_tensionVpmpGenerador',
    orientacionGenerador: 'e2_orientacionGenerador',
    inclinacionGenerador: 'e2_inclinacionGenerador',
    totalModulos: 'e2_totalModulos',
    modulosEnSerie: 'e2_modulosEnSerie',
    // E2.4 - Inversor E2
    marcaModeloInversor: 'e2_marcaModeloInversor',
    potenciaACInversor: 'e2_potenciaNominalInversor',
    // G - Características de Líneas y Circuitos
    potenciaBateriaInversor: 'g_bateriaDiRectaInversorPotencia',
    potenciaGeneradorInversorDirecto: 'g_generadorDirectoInversorPotencia',
    potenciaSalidaInversorRed: 'g_inversorRedPotencia',
    // H - Esquema Unifilar
    esquemaUnifilar: 'h_esquemaUnifilar',
    // I - Plano de Emplazamiento
    planoEmplazamiento: 'otros_imagenPlanoEmplazamiento'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const declaracionNoGeneracionRcdsConfig = {
  id: 'declaracion-no-generacion-rcds',
  title: 'Declaración Responsable de No Generación de RCDs',
  description: 'Declaración de no generación de residuos de construcción y demolición',
  fileName: 'declaracion-no-generacion-rcds.pdf',
  route: '/declaracion-no-generacion-rcds',
  fields: [
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'numero', label: 'Número', type: 'text' },
    { name: 'otrosDatos', label: 'Otros Datos', type: 'text', fullWidth: true },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'municipio', label: 'Municipio', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'ciudadFirma', label: 'Ciudad de Firma', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' }
  ],
  defaultData: {
    direccion: '',
    numero: '',
    otrosDatos: '',
    codigoPostal: '',
    referenciaCatastral: '',
    municipio: '',
    provincia: '',
    ciudadFirma: '',
    fecha: ''
  },
  fieldMapping: {
    direccion: 'emplazamientoCalle',
    numero: 'numero',
    codigoPostal: 'codigoPostalEmplazamiento',
    municipio: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    referenciaCatastral: 'referenciaCatastral',
    ciudadFirma: 'ciudadFirma',
    fecha: 'fecha'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const planosPlanosSituacionEmplazamientoCubiertaConfig = {
  id: 'planos-situacion-emplazamiento-cubierta',
  title: 'Planos de Situación, Emplazamiento y Cubierta',
  description: 'Documento con planos de ubicación, emplazamiento y disposición de módulos fotovoltaicos',
  fileName: 'planos-situacion-emplazamiento-cubierta.pdf',
  route: '/planos-situacion-emplazamiento-cubierta',
  fields: [
    // Datos del Promotor
    { name: 'pse_promotor', label: 'Titular / Promotor', type: 'text', fullWidth: true },
    { name: 'pse_nif', label: 'NIF/CIF', type: 'text' },

    // Ubicación
    { name: 'pse_direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'pse_numero', label: 'Número', type: 'text' },
    { name: 'pse_codigoPostal', label: 'Código Postal', type: 'text' },
    { name: 'pse_localidad', label: 'Localidad', type: 'text' },
    { name: 'pse_provincia', label: 'Provincia', type: 'text' },
    { name: 'pse_referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },

    // Datos Técnicos
    { name: 'pse_potenciaKw', label: 'Potencia (kW)', type: 'text' },
    { name: 'pse_tipoInstalacion', label: 'Tipo de Instalación', type: 'text', fullWidth: true },
    { name: 'pse_potenciaPicoGenerador', label: 'Potencia Pico del Generador (Wp)', type: 'text' },
    { name: 'pse_totalModulos', label: 'Total de Módulos', type: 'text' },
    { name: 'pse_potenciaModulos', label: 'Potencia de Módulos (Wp)', type: 'text' },
    { name: 'pse_disposicionModulos', label: 'Disposición de Módulos', type: 'text', fullWidth: true },

    // Descripción Proyecto
    { name: 'pse_tipo', label: 'Tipo de Instalación (ej: Instalación Solar Fotovoltaica)', type: 'text', fullWidth: true },
    { name: 'pse_potencia', label: 'Potencia Nominal (ej: 3.6 kW)', type: 'text' },
    { name: 'pse_descripcion', label: 'Descripción del Proyecto (ej: para Autoconsumo Individual)', type: 'textarea', fullWidth: true },

    // Imágenes de Planos
    { name: 'pse_imagenSituacion', label: 'PLANO DE SITUACIÓN', type: 'file', accept: 'image/*,.pdf', description: 'Plano de situación geográfica de la instalación.', fullWidth: true },
    { name: 'pse_imagenEmplazamiento', label: 'PLANO DE EMPLAZAMIENTO', type: 'file', accept: 'image/*,.pdf', description: 'Plano de emplazamiento de la instalación.', fullWidth: true },
    { name: 'pse_imagenCubierta', label: 'PLANO DE CUBIERTA', type: 'file', accept: 'image/*,.pdf', description: 'Plano de detalle de la instalación fotovoltaica en cubierta.', fullWidth: true },

    // Otros datos
    { name: 'pse_fecha', label: 'Fecha', type: 'date' },
    { name: 'pse_autorProyecto', label: 'Autor del Proyecto', type: 'text', fullWidth: true },
  ],
  defaultData: {
    pse_promotor: '',
    pse_nif: '',
    pse_direccion: '',
    pse_numero: '',
    pse_localidad: '',
    pse_codigoPostal: '',
    pse_provincia: '',
    pse_referenciaCatastral: '',
    pse_potenciaKw: '',
    pse_tipoInstalacion: '',
    pse_potenciaPicoGenerador: '',
    pse_totalModulos: '',
    pse_potenciaModulos: '',
    pse_disposicionModulos: '',
    pse_fecha: '',
    pse_autorProyecto: 'Eduardo Rivera Cabezas',
    pse_tituloDescriptivo: 'Instalación Solar Fotovoltaica',
    pse_tipo: '',
    pse_potencia: '',
    pse_descripcion: '',
    pse_imagenSituacion: '',
    pse_imagenEmplazamiento: '',
    pse_imagenCubierta: ''
  },
  fieldMapping: {
    pse_promotor: 'apellidosNombre',
    pse_nif: 'nifCif',
    pse_direccion: 'emplazamientoCalle',
    pse_numero: 'numero',
    pse_localidad: 'localidadEmplazamiento',
    pse_codigoPostal: 'codigoPostalEmplazamiento',
    pse_provincia: 'provinciaEmplazamiento',
    pse_referenciaCatastral: 'referenciaCatastral',
    pse_potenciaKw: 'potenciaKw',
    pse_tipoInstalacion: 'tipoInstalacionSeleccionada',
    pse_potenciaPicoGenerador: 'e2_potenciaPicoGenerador',
    pse_totalModulos: 'e2_totalModulos',
    pse_potenciaModulos: 'e2_potenciaPicoModulo',
    pse_disposicionModulos: 'disposicionModulos',
    pse_fecha: 'fecha',
    pse_autorProyecto: 'nombreTecnicoCompetente',
    pse_tipo: 'otros_tipoInstalacion',
    pse_potencia: 'e2_potenciaNominalInversores',
    pse_descripcion: 'otros_descripcionProyecto',
    pse_imagenSituacion: 'otros_imagenPlanoSituacion',
    pse_imagenEmplazamiento: 'otros_imagenPlanoEmplazamiento',
    pse_imagenCubierta: 'otros_imagenPlanoCubierta'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const zCertificadoBRConfig = {
  id: 'z-certificado-br',
  title: 'Certificado de Instalación Eléctrica de Baja Tensión',
  description: 'Plantilla base para legalización con bloques preparados para posicionar variables sobre formulario.',
  fileName: 'z-certificado-br.pdf',
  route: '/z-certificado-br',
  fields: [
    { name: 'registro_instalacion', label: 'Registro instalación', type: 'text' },
    { name: 'nombre', label: 'Nombre / Apellidos', type: 'text', fullWidth: true },
    { name: 'nif', label: 'NIF / CIF', type: 'text' },
    { name: 'domicilio', label: 'Domicilio', type: 'text', fullWidth: true },
    { name: 'cp', label: 'Código postal', type: 'text' },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'correo_electronico', label: 'Correo electrónico', type: 'text' },
    { name: 'telefono', label: 'Teléfono', type: 'text' },
    { name: 'emplazamiento', label: 'Dirección emplazamiento', type: 'text', fullWidth: true },
    { name: 'emplazamientoNumero', label: 'Número emplazamiento', type: 'text' },
    { name: 'emplazamientoBloque', label: 'Bloque', type: 'text' },
    { name: 'emplazamientoPortal', label: 'Portal', type: 'text' },
    { name: 'emplazamientoEscalera', label: 'Escalera', type: 'text' },
    { name: 'emplazamientoPiso', label: 'Piso', type: 'text' },
    { name: 'emplazamientoPuerta', label: 'Puerta', type: 'text' },
    { name: 'emplazamientoLocalidad', label: 'Localidad emplazamiento', type: 'text' },
    { name: 'emplazamientoProvincia', label: 'Provincia emplazamiento', type: 'text' },
    { name: 'emplazamientoCodigoPostal', label: 'Código postal emplazamiento', type: 'text' },
    { name: 'UsoAlQueSeDestinaEmplazamiento', label: 'Uso del emplazamiento', type: 'text' },
    { name: 'cups', label: 'CUPS', type: 'text' },
    { name: 'instalacionTipo', label: 'Tipo de intervención', type: 'select', options: ['nueva','ampliacion','modificacion'] },
    { name: 'fase', label: 'Fase', type: 'select', options: ['monofasico','trifasico'] },
    { name: 'potenciaPrevista', label: 'Potencia prevista (kW)', type: 'text' },
    { name: 'Superficie', label: 'Superficie (m²)', type: 'text' },
    { name: 'registro', label: 'Registro instalación', type: 'text' },
    { name: 'tensionSuministro', label: 'Tensión suministro', type: 'text' },
    { name: 'empresaDistribuidora', label: 'Empresa Distribuidora', type: 'text' },
    { name: 'intensidadNominal', label: 'Intensidad nominal', type: 'text' },
    { name: 'sensibilidadDiferencial', label: 'Sensibilidad (mA)', type: 'text' },
    { name: 'directorDeObra', label: 'Director de Obra', type: 'text' },
    { name: 'observaciones', label: 'Observaciones', type: 'textarea', rows: 3, fullWidth: true },
    { name: 'dia', label: 'Día', type: 'text' },
    { name: 'mes', label: 'Mes', type: 'text' },
    { name: 'anio', label: 'Año', type: 'text' },
    { name: 'fecha', label: 'Fecha', type: 'date' }
  ],
  defaultData: {
    registro_instalacion: '',
    nombre: '',
    nif: '',
    domicilio: '',
    cp: '',
    localidad: '',
    provincia: '',
    correo_electronico: '',
    telefono: '',
    emplazamiento: '',
    emplazamientoNumero: '',
    emplazamientoBloque: '',
    emplazamientoPortal: '',
    emplazamientoEscalera: '',
    emplazamientoPiso: '',
    emplazamientoPuerta: '',
    emplazamientoLocalidad: '',
    emplazamientoProvincia: '',
    emplazamientoCodigoPostal: '',
    UsoAlQueSeDestinaEmplazamiento: '',
    cups: '',
    instalacionTipo: '',
    fase: '',
    potenciaPrevista: '',
    Superficie: '',
    registro: '',
    tensionSuministro: '',
    empresaDistribuidora: '',
    intensidadNominal: '',
    sensibilidadDiferencial: '',
    directorDeObra: '',
    observaciones: '',
    dia: '',
    mes: '',
    anio: '',
    fecha: ''
  },
  fieldMapping: {
    registro_instalacion: 'registro_instalacion',
    nombre: 'apellidosNombre',
    nif: 'nifCif',
    domicilio: 'emplazamientoCalle',
    cp: 'codigoPostalEmplazamiento',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    correo_electronico: 'email',
    telefono: 'telefono',
    emplazamiento: 'emplazamientoCalle',
    emplazamientoNumero: 'numero',
    emplazamientoBloque: 'bloque',
    emplazamientoPortal: 'portal',
    emplazamientoEscalera: 'escalera',
    emplazamientoPiso: 'piso',
    emplazamientoPuerta: 'puerta',
    emplazamientoLocalidad: 'localidadEmplazamiento',
    emplazamientoProvincia: 'provinciaEmplazamiento',
    emplazamientoCodigoPostal: 'codigoPostalEmplazamiento',
    UsoAlQueSeDestinaEmplazamiento: 'usoEmplazamiento',
    cups: 'cups',
    instalacionTipo: 'instalacion',
    fase: 'e2_tipoConexionRed',
    potenciaPrevista: 'potenciaPrevista',
    Superficie: 'superficie',
    registro: 'registro',
    tensionSuministro: 'tensionSuministro',
    empresaDistribuidora: 'empresaDistribuidora',
    intensidadNominal: 'intensidadNominal',
    sensibilidadDiferencial: 'sensibilidadDiferencial',
    directorDeObra: 'directorDeObra',
    observaciones: 'observaciones',
    dia: 'dia',
    mes: 'mes',
    anio: 'anio',
    fecha: 'fecha'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'legalizacion'
}

/**
 * AUTORIZACIÓN PARA PRESENTAR LA COMUNICACIÓN DE PUESTA EN FUNCIONAMIENTO
 * Documento multi-página (3 páginas) - Junta de Andalucía ANEXO III
 */
export const autorizacionComunicacionConfig = {
  id: 'autorizacion-comunicacion',
  title: 'Autorización para Comunicación de Puesta en Funcionamiento',
  description: 'Formulario ANEXO III - Junta de Andalucía. Autorización para presentar la comunicación de puesta en funcionamiento de establecimientos o instalaciones industriales.',
  fileName: 'autorización-comunicación.pdf',
  route: '/autorizacion-comunicacion',
  pages: 3,
  fields: [
    // SECCIÓN 1: DATOS IDENTIFICATIVOS
    { name: 'apellidosNombre', label: 'Apellidos y Nombre', type: 'text', page: 1 },
    { name: 'nifCif', label: 'NIF/CIF', type: 'text', page: 1 },
    { name: 'nombreRepresentante', label: 'Nombre del Representante', type: 'text', page: 1 },
    { name: 'dniCifRepresentante', label: 'DNI/CIF del Representante', type: 'text', page: 1 },
    // SECCIÓN 2: LUGAR Y MEDIO DE NOTIFICACIÓN
    { name: 'tipoVia', label: 'Tipo de Vía', type: 'select', options: ['Calle', 'Avenida', 'Plaza', 'Paseo', 'Camino'], page: 1 },
    { name: 'nombreVia', label: 'Nombre de la Vía', type: 'text', page: 1 },
    { name: 'numero', label: 'Número', type: 'text', page: 1 },
    { name: 'letra', label: 'Letra', type: 'text', page: 1, optional: true },
    { name: 'KMEnLaVia', label: 'KM en la Vía', type: 'text', page: 1, optional: true },
    { name: 'bloque', label: 'Bloque', type: 'text', page: 1, optional: true },
    { name: 'portal', label: 'Portal', type: 'text', page: 1, optional: true },
    { name: 'escalera', label: 'Escalera', type: 'text', page: 1, optional: true },
    { name: 'planta', label: 'Planta', type: 'text', page: 1, optional: true },
    { name: 'puerta', label: 'Puerta', type: 'text', page: 1, optional: true },
    { name: 'codigoPostal', label: 'Código Postal', type: 'text', page: 1 },
    { name: 'entidad', label: 'Entidad', type: 'text', page: 1, optional: true },
    { name: 'municipio', label: 'Municipio', type: 'text', page: 1 },
    { name: 'provincia', label: 'Provincia', type: 'text', page: 1 },
    { name: 'pais', label: 'País', type: 'text', page: 1 },
    { name: 'telefonoFijo', label: 'Teléfono Fijo', type: 'tel', page: 1, optional: true },
    { name: 'telefonoMovil', label: 'Teléfono Móvil', type: 'tel', page: 1, optional: true },
    { name: 'correoElectronico', label: 'Correo Electrónico', type: 'email', page: 1 },
    // SECCIÓN 3: DATOS DEL ESTABLECIMIENTO E INSTALACIONES
    { name: 'denominacionEstablecimiento', label: 'Denominación del Establecimiento', type: 'text', page: 1 },
    { name: 'domicilioEstablecimiento', label: 'Domicilio del Establecimiento', type: 'text', page: 1 },
    { name: 'localidadEstablecimiento', label: 'Localidad del Establecimiento', type: 'text', page: 1 },
    { name: 'provinciaEstablecimiento', label: 'Provincia del Establecimiento', type: 'text', page: 1 },
    { name: 'codigoPostalEstablecimiento', label: 'Código Postal del Establecimiento', type: 'text', page: 1 },
    { name: 'instalacion1', label: 'Instalación 1', type: 'text', page: 1, optional: true },
    { name: 'instalacion2', label: 'Instalación 2', type: 'text', page: 1, optional: true },
    { name: 'instalacion3', label: 'Instalación 3', type: 'text', page: 1, optional: true },
    { name: 'instalacion4', label: 'Instalación 4', type: 'text', page: 1, optional: true },
    { name: 'instalacion5', label: 'Instalación 5', type: 'text', page: 1, optional: true },
    { name: 'instalacion6', label: 'Instalación 6', type: 'text', page: 1, optional: true },
    // SECCIÓN 4: DATOS DE LA PERSONA AUTORIZADA
    { name: 'figura', label: 'Figura', type: 'select', options: ['Técnico competente', 'Instalador habilitado', 'Responsable técnico'], page: 2 },
    { name: 'apellidosNombrePersona', label: 'Apellidos y Nombre de la Persona', type: 'text', page: 2 },
    { name: 'dniNiePersona', label: 'DNI/NIE de la Persona', type: 'text', page: 2 },
    // SECCIÓN 5: DECLARACIÓN Y FIRMA
    { name: 'lugarFirma', label: 'Lugar de Firma', type: 'text', page: 2 },
    { name: 'diaFirma', label: 'Día', type: 'text', page: 2 },
    { name: 'mesFirma', label: 'Mes', type: 'text', page: 2 },
    { name: 'anioFirma', label: 'Año', type: 'text', page: 2 },
    { name: 'representante', label: 'Representante/Autorizado', type: 'text', page: 2, optional: true },
    { name: 'codigoDirectorio', label: 'Código Directorio', type: 'text', page: 2, optional: true }
  ],
  defaultData: {
    apellidosNombre: '',
    nifCif: '',
    nombreRepresentante: '',
    dniCifRepresentante: '',
    tipoVia: '',
    nombreVia: '',
    numero: '',
    letra: '',
    KMEnLaVia: '',
    bloque: '',
    portal: '',
    escalera: '',
    planta: '',
    puerta: '',
    codigoPostal: '',
    entidad: '',
    municipio: '',
    provincia: '',
    pais: '',
    telefonoFijo: '',
    telefonoMovil: '',
    correoElectronico: '',
    denominacionEstablecimiento: '',
    domicilioEstablecimiento: '',
    localidadEstablecimiento: '',
    provinciaEstablecimiento: '',
    codigoPostalEstablecimiento: '',
    instalacion1: '',
    figura: 'X',
    apellidosNombrePersona: 'Eduardo Rivera Cabezas',
    dniNiePersona: 'B09848912',
    lugarFirma: '',
    diaFirma: '',
    mesFirma: '',
    anioFirma: '',
    representante: '',
    codigoDirectorio: ''
  },
  fieldMapping: {
    // Los campos mapean 1:1 - será necesario ajustar según masterFormFields
    apellidosNombre: 'apellidosNombre',
    nifCif: 'nifCif',
    razonSocial: 'razonSocial',
    calidad: 'calidad',
    tipoVia: 'tipoVia',
    nombreVia: 'emplazamientoCalle',
    numero: 'numero',
    letra: 'letra',
    KMEnLaVia: 'KMEnLaVia',
    bloque: 'bloque',
    portal: 'numero',
    escalera: 'escalera',
    planta: 'planta',
    puerta: 'puerta',
    codigoPostal: 'codigoPostalEmplazamiento',
    municipio: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    pais: 'pais',
    telefonoFijo: 'telefonoFijo',
    telefonoMovil: 'telefono',
    correoElectronico: 'correoElectronicoEmplazamiento',
    denominacionEstablecimiento: 'denominacionEstablecimiento',
    domicilioEstablecimiento: 'emplazamientoCalle',
    localidadEstablecimiento: 'localidadEmplazamiento',
    provinciaEstablecimiento: 'provinciaEmplazamiento',
    codigoPostalEstablecimiento: 'codigoPostalEmplazamiento',
    instalacion1: 'instalacion1',
    figura: '',
    apellidosNombrePersona: 'apellidosNombrePersona',
    dniNiePersona: 'dniNiePersona',
    lugarFirma: 'localidadEmplazamiento',
    diaFirma: 'dia',
    mesFirma: 'mes',
    anioFirma: 'anio',
    representante: 'representante',
    codigoDirectorio: 'codigoDirectorio'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true,
    multiPage: true
  },
  category: 'legalizacion'
}

/**
 * Objeto que contiene todas las configuraciones de documentos
 */
export const certificadoAdecuacionConfig = {
  id: 'certificado-adecuacion',
  title: 'Certificado de Adecuación al Real Decreto 1699/2011',
  description: 'Certificado de adecuación para instalaciones eléctricas según RD 1699/2011',
  fileName: 'certificado-adecuacion.pdf',
  route: '/certificado-adecuacion',
  fields: [
    { name: 'tipoInstalacion', label: 'Tipo de instalación', type: 'text', fullWidth: true },
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'localidad', label: 'Localidad', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'uso', label: 'Uso', type: 'text', fullWidth: true },
    { name: 'ciudadFirma', label: 'Ciudad de firma', type: 'text' },
    { name: 'dia', label: 'Día', type: 'text', width: 50 },
    { name: 'mes', label: 'Mes', type: 'text', width: 100 },
    { name: 'anio', label: 'Año', type: 'text', width: 70 }
  ],
  defaultData: {
    tipoInstalacion: 'con almacenamiento',
    direccion: 'AVENIDA DE MÁLAGA, Nº50',
    localidad: 'MONTILLA',
    provincia: 'SEVILLA',
    uso: 'doméstico o negocio',
    ciudadFirma: 'Bollullos de la Mitación',
    dia: '01',
    mes: 'JULIO',
    anio: '2024'
  },
  fieldMapping: {
    tipoInstalacion: '',
    direccion: 'emplazamientoCalle',
    localidad: 'localidadEmplazamiento',
    provincia: 'provinciaEmplazamiento',
    uso: 'usoDestino',
    ciudadFirma: 'ciudadFirma',
    dia: 'dia',
    mes: 'mes',
    anio: 'anio'
  },
  capabilities: {
    canPreview: true,
    canEdit: false,
    canGeneratePDF: true
  },
  category: 'legalizacion'
};

const documentConfigs = {
  'certificado-adecuacion': certificadoAdecuacionConfig,
  'autorizacion-representacion': autorizacionRepresentacionConfig,
  'declaracion-habilitacion-profesional': declaracionHabilitacionProfesionalConfig,
  'declaracion-no-generacion-rcds': declaracionNoGeneracionRcdsConfig,
  'certificado-coplanar-teja': certificadoCoplanarTejaConfig,
  'certificado-cubierta-plan-aaporticada': certificadoCubiertaPlanAaporticadaConfig,
  'certificado-aporticada-teja': certificadoAporticadaTejConfig,
  'certificado-paramento-vertical': certificadoParamentoVerticalConfig,
  'certificado-chapas-grecadas-aporticada': certificadoChapasGrecadasAporticadaConfig,
  'certificado-pergola-aporticada': certificadoPergolaAporticadaConfig,
  'mtd-instalacion-autoconsumo-monofasica-con-bateria': memoriaTecnicaConfig,
  'mtd-instalacion-aislada-con-bateria': memoriaInstalacionAisladaConBateriaConfig,
  'mtd-instalacion-autoconsumo-trifasica-con-bateria': memoriaTecnicaTrifasicaConBateriaConfig,
  'mtd-instalacion-autoconsumo-sin-bateria': memoriaTecnicaAutoconsumoSinBateriaConfig,
  'mtd-instalacion-puntos-recarga': memoriaTecnicaPuntoRecargaConfig,
  'planos-situacion-emplazamiento-cubierta': planosPlanosSituacionEmplazamientoCubiertaConfig,
  'z-certificado-br': zCertificadoBRConfig,
  'autorizacion-comunicacion': autorizacionComunicacionConfig
}

/**
 * Obtener configuración de un documento por ID
 */
export const getDocumentConfig = (documentId) => {
  // Primero intentar por clave directa (para compatibilidad con aliases)
  if (documentConfigs[documentId]) return documentConfigs[documentId]

  // Si no existe, buscar por el campo `id` dentro de las configuraciones
  const found = Object.values(documentConfigs).find(cfg => cfg.id === documentId)
  return found || null
}

/**
 * Obtener lista de todos los documentos disponibles
 * Devuelve una lista sin duplicados (se agrupan por `config.id`)
 */
export const getAllDocuments = () => {
  const seen = new Set()
  const list = []

  for (const cfg of Object.values(documentConfigs)) {
    const uniqueId = cfg.id || cfg.route || cfg.fileName
    if (seen.has(uniqueId)) continue
    seen.add(uniqueId)
    list.push({
      id: uniqueId,
      ...cfg,
      category: cfg.category || 'proyecto'
    })
  }

  return list
}
