export const autorizacionRepresentacionConfig = {
  id: 'autorizacion-representacion',
  title: 'Autorización de Representación',
  description: 'Documento válido para trámites administrativos',
  fileName: 'autorizacion-representacion.pdf',
  route: '/autorizacion-representacion',
  defaultData: {
    autorizante: '',
    dniAutorizante: '',
    domicilioAutorizante: '',
    representante: 'Solay Ingenieros, S.L.',
    dniRepresentante: 'B09848912',
    domicilioRepresentante: 'Calle Ebro, 35 – 41012, Sevilla, Sevilla',
    organismo: 'Ayuntamiento de Puerto Real (Cádiz)',
    gestiones: 'SOLICITUD DE LICENCIA DE OBRA MENOR CON DECLARACIÓN RESPONSABLE O AUTORIZACIÓN URBANÍSTICA',
    fecha: '18/11/2025'
  },
  fieldMapping: {
    autorizante: 'apellidosNombre',
    dniAutorizante: 'nifCif',
    domicilioAutorizante: 'domicilio'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const declaracionHabilitacionProfesionalConfig = {
  id: 'declaracion-habilitacion-profesional',
  title: 'Declaración Responsable de Habilitación Profesional',
  description: 'Documento de declaración de habilitación profesional para colegiados',
  fileName: 'declaracion-habilitacion-profesional.pdf',
  route: '/declaracion-habilitacion-profesional',
  defaultData: {
    nombreProfesional: 'Eduardo Rivera Cabezas',
    nifProfesional: '28.818.007-L',
    profesionTitulo: 'Ingeniero Industrial',
    numeroColegiado: '4654',
    nombreColegio: 'Colegio Oficial de Ingenieros Industriales de Andalucía Occidental',
    domicilioProfesional: 'Calle El Peñón 5',
    codigoPostalProfesional: '41940',
    localidadProfesional: 'Tomares',
    provinciaProfesional: 'Sevilla',
    ciudadFirma: 'Jerez de la Frontera',
    fecha: '16/10/2025'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoCoplanarTejaConfig = {
  id: 'certificado-coplanar-teja',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Coplanar Teja',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas en cubierta de teja coplanar',
  fileName: 'certificado-coplanar-teja.pdf',
  route: '/certificado-coplanar-teja',
  defaultData: {
    direccion: ' ',
    numero: '',
    otrosDatosDireccion: '',
    codigoPostal: '',
    localidad: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    modelo: '',
    ciudadFirma: '',
    fecha: '',
    imagen1: null,
    imagen4: null
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const certificadoCubiertaPlanAaporticadaConfig = {
  id: 'certificado-cubierta-plan-aaporticada',
  title: 'Certificado de Solidez y Seguridad de la Cubierta - Plana Aportícada',
  description: 'Documento de certificación de solidez y seguridad para instalaciones fotovoltaicas en cubierta plana con estructura aportícada',
  fileName: 'certificado-cubierta-plan-aaporticada.pdf',
  route: '/certificado-cubierta-plan-aaporticada',
  defaultData: {
    direccion: '',
    numero: '',
    otrosDatosDireccion: '',
    codigoPostal: '',
    localidad: '',
    referenciaCatastral: '',
    numModulos: '',
    potencia: '',
    peso: '',
    modelo: '',
    ciudadFirma: '',
    fecha: '',
    imagen1: null
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const memoriaTecnicaConfig = {
  id: 'mtd-instalacion-autoconsumo-monofasica-con-bateria',
  title: 'Memoria Técnica de Instalación de Autoconsumo Monofásica con Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas en baja tensión',
  fileName: '6-MTD-INSTALACION-AUTOCONSUMO-MONOFASICA-CON-BATERIA.pdf',
  route: '/mtd-instalacion-autoconsumo-monofasica-con-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Fotovoltaica conectada a red interior',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: 'Calle Ebro',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41.012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '',
    vccMaximaInversor: '',
    vccMinimaInversor: '',
    tipoConexionInversor: '',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: 'Litio-Hierro Fosfato (LiFePO4)',
    tensionNominalBateria: '200V',
    profundidadDescargaBateria: '100%',
    tensionMaximaBateria: '57,6V',
    tensionMinimaBateria: '44,8V',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '25',
    poderCorteInterruptor: '6',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'Interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: 'Descargador',
    parteInstalacionSobretensiones: 'CGMP',
    medidaPuntoCaliente: '3 Diodos bypass',
    parteInstalacionPuntoCaliente: 'Módulo FV',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    caidaTensionReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const memoriaInstalacionAisladaConBateriaConfig = {
  id: 'mtd-instalacion-aislada-con-bateria',
  title: 'Memoria Técnica de Instalación Aislada con Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas aisladas con almacenamiento',
  fileName: 'mtd-instalacion-aislada-con-bateria.pdf',
  route: '/mtd-instalacion-aislada-con-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Fotovoltaica aislada',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas ',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41.012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '20º',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '230 V',
    vccMaximaInversor: '425',
    vccMinimaInversor: '150',
    tipoConexionInversor: 'MONOFÁSICA',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: 'Litio-Hierro Fosfato (LiFePO4)',
    tensionNominalBateria: '200V',
    profundidadDescargaBateria: '100%',
    tensionMaximaBateria: '57,6V',
    tensionMinimaBateria: '44,8V',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '25',
    poderCorteInterruptor: '6',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'Interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: 'Descargador',
    parteInstalacionSobretensiones: 'Módulo FV',
    medidaPuntoCaliente: '3 Diodos bypass',
    parteInstalacionPuntoCaliente: 'Módulo FV',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const memoriaTecnicaTrifasicaConBateriaConfig = {
  id: 'mtd-instalacion-autoconsumo-trifasica-con-bateria',
  title: 'Memoria Técnica de Instalación de Autoconsumo Trifásica con Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas en baja tensión (trifásica con batería)',
  fileName: '6-MTD-INSTALACION-AUTOCONSUMO-TRIFASICA-CON-BATERIA.pdf',
  route: '/mtd-instalacion-autoconsumo-trifasica-con-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: 'aaaaaaaaaaa',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    memoriaTecnicaAisladaSinBateriaConfigcorreoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Fotovoltaica conectada a red interior',
    usoDestino: 'Autoconsumo para vivienda',
    memoriaTecnicaAisladaSinBateriaConfigtipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: 'Monocristalino -PERC- doble célula',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '45ºC',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '', 
    intensidadIpmpGenerador: '10,84',
    orientacionGenerador: '',
    inclinacionGenerador: '',
    totalModulos: '',
    modulosEnSerie: '',
    ramasEnParalelo: '1',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '400 V',
    vccMaximaInversor: '1100',
    vccMinimaInversor: '140',
    tipoConexionInversor: 'trifásica',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: 'Litio-Hierro Fosfato (LiFePO4)',
    tensionNominalBateria: '450V',
    profundidadDescargaBateria: '100%',
    tensionMaximaBateria: '980V',
    tensionMinimaBateria: '600V',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '',
    poderCorteInterruptor: '',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: 'Conductores aislados y canaletas',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: 'interruptor diferencial',
    parteInstalacionIndirectos: 'CGMP',
    medidaSobretensiones: '3 Diodos bypass',
    parteInstalacionSobretensiones: 'modulo FV',
    medidaPuntoCaliente: 'Descargador',
    parteInstalacionPuntoCaliente: 'CGMP',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    caidaTensionReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '5',
    materialBateriaInversor: '6',
    intensidadBateriaInversor: '49',
    caidaTensionBateriaInversor: '< 1,5 %',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '10',
    materialGeneradorInversorDirecto: '6',
    intensidadGeneradorInversorDirecto: '49',
    caidaTensionGeneradorInversorDirecto: '< 1,5 %',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '5',
    materialSalidaInversorRed: '6',
    intensidadSalidaInversorRed: '44',
    caidaTensionSalidaInversorRed: '< 1,5 %',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  capabilities: { ...memoriaTecnicaConfig.capabilities }
}

export const memoriaTecnicaAutoconsumoSinBateriaConfig = {
  id: 'mtd-instalacion-autoconsumo-sin-bateria',
  title: 'Memoria Técnica de Instalación Autoconsumo Sin Batería',
  description: 'Documento técnico para instalaciones fotovoltaicas en baja tensión (autoconsumo sin batería)',
  fileName: '6-MTD-INSTALACION-AUTOCONSUMO-SIN-BATERIA.pdf',
  route: '/mtd-instalacion-autoconsumo-sin-bateria',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Instalación Generadora Fotovoltaica',
    usoDestino: 'Autoconsumo para vivienda',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '35',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // E1: INSTALACIÓN GENERADORA FOTOVOLTAICA AISLADA
    // E1.1 Módulo Fotovoltaico
    e1_tecnologiaCelulaModulo: '',
    e1_marcaModeloModulo: '',
    e1_potenciaPicoModulo: '',
    e1_toncModulo: '',
    // E1.2 Generador Fotovoltaico
    e1_potenciaPicoGenerador: '',
    e1_intensidadIpmpGenerador: '',
    e1_tensionVpmpGenerador: '',
    e1_orientacionGenerador: '',
    e1_inclinacionGenerador: '',
    e1_totalModulos: '',
    e1_modulosEnSerie: '',
    e1_ramasEnParalelo: '',
    // E1.3 Baterías
    e1_marcaModeloBateria: '',
    e1_tipoBateria: '',
    e1_tipoPlacaBateria: '',
    e1_c10Bateria: '',
    e1_c100Bateria: '',
    e1_tensionNominalBateria: '',
    e1_profundidadDescargaBateria: '',
    e1_tensionMaximaBateria: '',
    e1_tensionMinimaBateria: '',
    e1_intensidadMaximaCargaBateria: '',
    // E1.4 Regulador
    e1_marcaModeloRegulador: '',
    e1_intensidadMaximaRegulador: '',
    e1_tensionCorteAltaRegulador: '',
    e1_tensionCorteBajaRegulador: '',
    // E1.5 Inversor
    e1_marcaModeloInversor: '',
    e1_potenciaNominalInversor: '',
    e1_rendimientoInversor10: '',
    e1_rendimientoInversor25: '',
    e1_rendimientoInversor50: '',
    e1_rendimientoInversor75: '',
    e1_rendimientoInversor100: '',
    e1_relacionTensionInversor: '',
    e1_formaOndaSalidaInversor: '',
    e1_frecuenciaNominalInversor: '',
    e1_tensionMaximaEntradaInversor: '',
    e1_tensionSalidaInversor: '',
    e1_consumoVacioInversor: '',
    e1_seguidorPuntoMaximaPotencia: '',
    // E1.6 Otros
    e1_convertidorCC_CC: '',
    e1_relacionTensionCC: '',
    e1_variadorFrecuencia: '',
    e1_grupoAuxiliarApoyo: '',
    e1_potenciaGrupoAuxiliar: '',
    e1_otrosEquipos: '',
    // E1.7 Información de la Demanda
    e1_potenciaMaximaDemanda: '',
    e1_periodicidadDemanda: '',
    e1_energiaDiariaEnero: '',
    e1_energiaDiariaFebrero: '',
    e1_energiaDiariaMarzo: '',
    e1_energiaDiariaAbril: '',
    e1_energiaDiariaMayo: '',
    e1_energiaDiariaJunio: '',
    e1_energiaDiariaJulio: '',
    e1_energiaDiariaAgosto: '',
    e1_energiaDiariaSeptiembre: '',
    e1_energiaDiariaOctubre: '',
    e1_energiaDiariaNoviembre: '',
    e1_energiaDiariaDiciembre: '',
    // E2: INSTALACIÓN GENERADORA FOTOVOLTAICA INTERCONECTADA CON ALMACENAMIENTO
    // E2.1 Conexión a la Red
    potenciaNominalInversores: '',
    tipoConexionRed: '',
    // E2.2 Módulo Fotovoltaico
    tecnologiaCelulaModulo: '',
    marcaModeloModulo: '',
    potenciaPicoModulo: '',
    toncModulo: '',
    // E2.3 Generador Fotovoltaico
    potenciaPicoGenerador: '',
    tensionVpmpGenerador: '',
    intensidadIpmpGenerador: '',
    orientacionGenerador: '',
    inclinacionGenerador: '',
    totalModulos: '',
    modulosEnSerie: '',
    ramrasEnParalelo: '',
    // E2.4 Inversor
    marcaModeloInversor: '',
    potenciaACInversor: '',
    tensionNominalInversor: '',
    vccMaximaInversor: '',
    vccMinimaInversor: '',
    tipoConexionInversor: '',
    // E2.5 Baterías
    marcaModeloBateria: '',
    tipoBateria: '',
    tensionNominalBateria: '',
    profundidadDescargaBateria: '',
    tensionMaximaBateria: '',
    tensionMinimaBateria: '',
    energiaTotalBateria: '',
    potenciaMaximaSalidaBateria: '',
    maximoPicoPotenciaBateria: '',
    // E2.5.1 Protecciones Externas
    intensidadInterruptorGeneral: '',
    poderCorteInterruptor: '',
    proteccionFrecuenciaTension: '',
    // Sección F - Medidas de Protección
    medidaContactosDirectos: '',
    parteInstalacionDirectos: '',
    medidaContactosIndirectos: '',
    parteInstalacionIndirectos: '',
    medidaSobretensiones: '',
    parteInstalacionSobretensiones: '',
    medidaPuntoCaliente: '',
    parteInstalacionPuntoCaliente: '',
    medidaExplosion: '',
    parteInstalacionExplosion: '',
    medidaCorrosion: '',
    parteInstalacionCorrosion: '',
    otrasProtecciones: '',
    // Sección G - Características de Líneas y Circuitos
    potenciaGeneradorRegulador: '',
    longitudGeneradorRegulador: '',
    materialGeneradorRegulador: '',
    intensidadGeneradorRegulador: '',
    caidaTensionGeneradorRegulador: '',
    potenciaReguladorBateria: '',
    longitudReguladorBateria: '',
    materialReguladorBateria: '',
    intensidadReguladorBateria: '',
    caidaTensionReguladorBateria: '',
    potenciaSalidaRegulador: '',
    longitudSalidaRegulador: '',
    materialSalidaRegulador: '',
    intensidadSalidaRegulador: '',
    caidaTensionSalidaRegulador: '',
    potenciaBateriaInversor: '',
    longitudBateriaInversor: '',
    materialBateriaInversor: '',
    intensidadBateriaInversor: '',
    caidaTensionBateriaInversor: '',
    potenciaGeneradorInversorDirecto: '',
    longitudGeneradorInversorDirecto: '',
    materialGeneradorInversorDirecto: '',
    intensidadGeneradorInversorDirecto: '',
    caidaTensionGeneradorInversorDirecto: '',
    potenciaSalidaInversorRed: '',
    longitudSalidaInversorRed: '',
    materialSalidaInversorRed: '',
    intensidadSalidaInversorRed: '',
    caidaTensionSalidaInversorRed: '',
    // Sección H - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección I - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  capabilities: { ...memoriaTecnicaConfig.capabilities }
}

export const memoriaTecnicaPuntoRecargaConfig = {
  id: 'mtd-instalacion-puntos-recarga',
  title: 'Memoria Técnica de Instalación de Puntos de Recarga para Vehículos Eléctricos',
  description: 'Documento técnico para instalaciones de recarga de vehículos eléctricos',
  fileName: '6-MTD-INSTALACION-PUNTOS-RECARGA.pdf',
  route: '/mtd-instalacion-puntos-recarga',
  defaultData: {
    // Expediente
    numeroExpediente: '',
    numeroRegistro: '',
    // Sección A - TITULAR
    apellidosNombre: '',
    nifCif: '',
    domicilio: '',
    codigoPostal: '',
    localidad: '',
    provincia: '',
    correoElectronico: '',
    telefono: '',
    representante: '',
    dniRepresentante: '',
    // Sección B - EMPLAZAMIENTO
    emplazamientoCalle: '',
    numero: '',
    bloque: '',
    escalera: '',
    piso: '',
    localidadEmplazamiento: '',
    provinciaEmplazamiento: '',
    correoElectronicoEmplazamiento: '',
    tipoInstalacion: 'Instalación con fines especiales',
    usoDestino: 'Infraestructura para la recarga de vehículos eléctricos',
    tipoInstalacionSeleccionada: '',
    // Sección C - PERSONA QUE FIRMA
    nombreTecnicoInstalador: 'Eduardo Rivera Cabezas',
    numeroCertificadoInstalador: '4654 COIIAOC',
    numeroInstaladorEmpresa: '41045500',
    domicilioTecnico: 'Calle Ebro',
    numeroTecnico: '45',
    localidadTecnico: 'Sevilla',
    codigoPostalTecnico: '41012',
    telefonoTecnico: '629 118 196',
    nombreTecnicoCompetente: '',
    domicilioTecnicoCompetente: '',
    numeroTecnicoCompetente: '',
    localidadTecnicoCompetente: '',
    codigoPostalTecnicoCompetente: '',
    telefonoTecnicoCompetente: '',
    colegioOficial: '',
    numeroColegiado: '',
    // Sección D - MODALIDADES
    modalidadBasicaM1: true,
    modalidadBasicaM2: true,
    modalidadBasicaM3: true,
    modalidadEspecialistaM4: true,
    modalidadEspecialistaM5: true,
    modalidadEspecialistaM6: true,
    modalidadEspecialistaM7: true,
    modalidadEspecialistaM8: true,
    modalidadEspecialistaM9: true,
    // Sección E - INSTALACIÓN PARA LA RECARGA DE VEHÍCULO ELÉCTRICO
    // E.1 CARGADOR
    cargadorMarca: 'SMA EV',
    cargadorModelo: 'CHARGER 22',
    cargadorNumeroCapacidad: '1/Trifásica',
    cargadorTipoCable: 'Manguera fija',
    // E.2 INFRAESTRUCTURA DE RECARGA
    numeroPuntosRecarga: '1',
    monofasica: false,
    trifasica: true,
    potenciaInstalada: '22',
    potenciaPrevisita: '22',
    tipoInstalacionRecarga: 'INTERIOR',
    modoCarga: 'Modo 3 (IEC 61851-)',
    tipoConector: '2',
    // E.3 CUADRO DE MANDO Y PROTECCIÓN
    interruptorGeneralAmperaje: '',
    interruptorDiferencialAmperaje: '',
    interruptorDiferencialSensibilidad: '',
    descargadorSobretensiones: 'Sí',
    puestaATierra: 'Según normas',
    // Sección F - CARACTERÍSTICAS DE LÍNEAS Y CIRCUITOS
    potenciaPrevistaCuadroPrincipal: '',
    longitudCuadroPrincipal: '10',
    materialConductor: '6',
    intensidadAdmisible: '49',
    caidaTension: '< 1,5 %',
    // Sección G - Esquema Unifilar
    esquemaUnifilar: '',
    // Sección H - Plano de Emplazamiento
    planoEmplazamiento: ''
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

export const declaracionNoGeneracionRcdsConfig = {
  id: 'declaracion-no-generacion-rcds',
  title: 'Declaración Responsable de No Generación de RCDs',
  description: 'Declaración de no generación de residuos de construcción y demolición',
  fileName: 'declaracion-no-generacion-rcds.pdf',
  route: '/declaracion-no-generacion-rcds',
  defaultData: {
    direccion: '',
    numero: '',
    otrosDatos: '',
    codigoPostal: '',
    referenciaCatastral: '',
    municipio: '',
    ciudadFirma: '',
    fecha: ''
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
}

/**
 * Objeto que contiene todas las configuraciones de documentos
 */
const documentConfigs = {
  'autorizacion-representacion': autorizacionRepresentacionConfig,
  'declaracion-habilitacion-profesional': declaracionHabilitacionProfesionalConfig,
  'declaracion-no-generacion-rcds': declaracionNoGeneracionRcdsConfig,
  'certificado-coplanar-teja': certificadoCoplanarTejaConfig,
  'certificado-cubierta-plan-aaporticada': certificadoCubiertaPlanAaporticadaConfig,
  'mtd-instalacion-autoconsumo-monofasica-con-bateria': memoriaTecnicaConfig,
  'mtd-instalacion-aislada-con-bateria': memoriaInstalacionAisladaConBateriaConfig,
  'mtd-instalacion-autoconsumo-trifasica-con-bateria': memoriaTecnicaTrifasicaConBateriaConfig,
  'mtd-instalacion-autoconsumo-sin-bateria': memoriaTecnicaAutoconsumoSinBateriaConfig,
  'mtd-instalacion-puntos-recarga': memoriaTecnicaPuntoRecargaConfig
}

/**
 * Obtener configuración de un documento por ID
 */
export const getDocumentConfig = (documentId) => {
  // Primero intentar por clave directa (para compatibilidad con aliases)
  if (documentConfigs[documentId]) return documentConfigs[documentId]

  // Si no existe, buscar por el campo `id` dentro de las configuraciones
  const found = Object.values(documentConfigs).find(cfg => cfg.id === documentId)
  return found || null
}

/**
 * Obtener lista de todos los documentos disponibles
 * Devuelve una lista sin duplicados (se agrupan por `config.id`)
 */
export const getAllDocuments = () => {
  const seen = new Set()
  const list = []

  for (const cfg of Object.values(documentConfigs)) {
    const uniqueId = cfg.id || cfg.route || cfg.fileName
    if (seen.has(uniqueId)) continue
    seen.add(uniqueId)
    list.push({ id: uniqueId, ...cfg })
  }

  return list
}
