export const justificacionPagoSubvencionConfigL3 = {
  id: 'justificacion-pago-subvencion',
  title: 'Justificación de Pago de Subvención',
  description: 'Documento para justificar el pago de una subvención',
  fileName: 'justificacion-pago-subvencion.pdf',
  route: '/justificaciones/justificacion-pago-subvencion',
  fields: [
    { name: 'expediente', label: 'Expediente', type: 'text' },
    { name: 'apellidosNombre', label: 'Nombre y Apellidos', type: 'text', fullWidth: true },
    { name: 'dni', label: 'DNI', type: 'text' },
    { name: 'telefono', label: 'Teléfono', type: 'text' },
    { name: 'correoElectronico', label: 'Correo Electrónico', type: 'text' },
    { name: 'apellidosNombreRepresentante', label: 'Nombre del Representante', type: 'text', fullWidth: true },
    { name: 'dniRepresentante', label: 'DNI Representante', type: 'text' },
    { name: 'actuaCalidad', label: 'Actúa en calidad de', type: 'text' },
    { name: 'telefonoRepresentante', label: 'Teléfono Representante', type: 'text' },
    { name: 'correoElectronicoRepresentante', label: 'Correo Electrónico Representante', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'dia', label: 'Día', type: 'text' },
    { name: 'mes', label: 'Mes', type: 'text' },
    { name: 'anio', label: 'Año', type: 'text' },
    { name: 'personaFirma', label: 'Persona que firma', type: 'text' },
    { name: 'firma', label: 'Firma (Imagen)', type: 'file', accept: 'image/*' }
  ],
  defaultData: {
    expediente: '',
    apellidosNombre: '',
    dni: '',
    telefono: '',
    correoElectronico: '',
    apellidosNombreRepresentante: '',
    dniRepresentante: '',
    actuaCalidad: '',
    telefonoRepresentante: '',
    correoElectronicoRepresentante: '',
    provincia: '',
    dia: '',
    mes: '',
    anio: '',
    personaFirma: '',
    firma: ''
  },
  fieldMapping: {
    expediente: 'expediente',
    apellidosNombre: 'apellidosNombre',
    dni: 'dni',
    telefono: 'telefono',
    correoElectronico: 'correoElectronico',
    apellidosNombreRepresentante: 'apellidosNombreRepresentante',
    dniRepresentante: 'dniRepresentante',
    actuaCalidad: 'actuaCalidad',
    telefonoRepresentante: 'telefonoRepresentante',
    correoElectronicoRepresentante: 'correoElectronicoRepresentante',
    provincia: 'provincia',
    dia: 'dia',
    mes: 'mes',
    anio: 'anio',
    personaFirma: 'personaFirma',
    firma: 'firma'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificaciones'
}
