// Auto-generado por scripts/generar_municipios.js
// Fuente: INE (via github.com/frontid/ComunidadesProvinciasPoblaciones)
// Fecha: 2026-09-16T07:57:47.853Z
// Nombres normalizados: artículos movidos al inicio (ej: "Barrios, Los" → "Los Barrios")
//
// Mapa: código provincia INE -> array de nombres de municipios

export const municipiosPorProvincia = {
  // CÁDIZ (45 municipios)
  '11': [
    'Alcalá de los Gazules',
    'Alcalá del Valle',
    'Algar',
    'Algeciras',
    'Algodonales',
    'Arcos de la Frontera',
    'Barbate',
    'Benalup-Casas Viejas',
    'Benaocaz',
    'Bornos',
    'Cádiz',
    'Castellar de la Frontera',
    'Chiclana de la Frontera',
    'Chipiona',
    'Conil de la Frontera',
    'El Bosque',
    'El Gastor',
    'El Puerto de Santa María',
    'Espera',
    'Grazalema',
    'Jerez de la Frontera',
    'Jimena de la Frontera',
    'La Línea de la Concepción',
    'Los Barrios',
    'Medina Sidonia',
    'Olvera',
    'Paterna de Rivera',
    'Prado del Rey',
    'Puerto Real',
    'Puerto Serrano',
    'Rota',
    'San Fernando',
    'San José del Valle',
    'San Martín del Tesorillo',
    'San Roque',
    'Sanlúcar de Barrameda',
    'Setenil de las Bodegas',
    'Tarifa',
    'Torre Alháquime',
    'Trebujena',
    'Ubrique',
    'Vejer de la Frontera',
    'Villaluenga del Rosario',
    'Villamartín',
    'Zahara',
  ],

  // CÓRDOBA (77 municipios)
  '14': [
    'Adamuz',
    'Aguilar de la Frontera',
    'Alcaracejos',
    'Almedinilla',
    'Almodóvar del Río',
    'Añora',
    'Baena',
    'Belalcázar',
    'Belmez',
    'Benamejí',
    'Bujalance',
    'Cabra',
    'Cañete de las Torres',
    'Carcabuey',
    'Cardeña',
    'Castro del Río',
    'Conquista',
    'Córdoba',
    'Doña Mencía',
    'Dos Torres',
    'El Carpio',
    'El Guijo',
    'El Viso',
    'Encinas Reales',
    'Espejo',
    'Espiel',
    'Fernán-Núñez',
    'Fuente Carreteros',
    'Fuente la Lancha',
    'Fuente Obejuna',
    'Fuente Palmera',
    'Fuente-Tójar',
    'Guadalcázar',
    'Hinojosa del Duque',
    'Hornachuelos',
    'Iznájar',
    'La Carlota',
    'La Granjuela',
    'La Guijarrosa',
    'La Rambla',
    'La Victoria',
    'Los Blázquez',
    'Lucena',
    'Luque',
    'Montalbán de Córdoba',
    'Montemayor',
    'Montilla',
    'Montoro',
    'Monturque',
    'Moriles',
    'Nueva Carteya',
    'Obejo',
    'Palenciana',
    'Palma del Río',
    'Pedro Abad',
    'Pedroche',
    'Peñarroya-Pueblonuevo',
    'Posadas',
    'Pozoblanco',
    'Priego de Córdoba',
    'Puente Genil',
    'Rute',
    'San Sebastián de los Ballesteros',
    'Santa Eufemia',
    'Santaella',
    'Torrecampo',
    'Valenzuela',
    'Valsequillo',
    'Villa del Río',
    'Villafranca de Córdoba',
    'Villaharta',
    'Villanueva de Córdoba',
    'Villanueva del Duque',
    'Villanueva del Rey',
    'Villaralto',
    'Villaviciosa de Córdoba',
    'Zuheros',
  ],

  // GRANADA (174 municipios)
  '18': [
    'Agrón',
    'Alamedilla',
    'Albolote',
    'Albondón',
    'Albuñán',
    'Albuñol',
    'Albuñuelas',
    'Aldeire',
    'Alfacar',
    'Algarinejo',
    'Alhama de Granada',
    'Alhendín',
    'Alicún de Ortega',
    'Almegíjar',
    'Almuñécar',
    'Alpujarra de la Sierra',
    'Alquife',
    'Arenas del Rey',
    'Armilla',
    'Atarfe',
    'Baza',
    'Beas de Granada',
    'Beas de Guadix',
    'Benalúa',
    'Benalúa de las Villas',
    'Benamaurel',
    'Bérchules',
    'Bubión',
    'Busquístar',
    'Cacín',
    'Cádiar',
    'Cájar',
    'Calicasas',
    'Campotéjar',
    'Caniles',
    'Cáñar',
    'Capileira',
    'Carataunas',
    'Cástaras',
    'Castilléjar',
    'Castril',
    'Cenes de la Vega',
    'Chauchina',
    'Chimeneas',
    'Churriana de la Vega',
    'Cijuela',
    'Cogollos de Guadix',
    'Cogollos de la Vega',
    'Colomera',
    'Cortes de Baza',
    'Cortes y Graena',
    'Cuevas del Campo',
    'Cúllar',
    'Cúllar Vega',
    'Darro',
    'Dehesas de Guadix',
    'Dehesas Viejas',
    'Deifontes',
    'Diezma',
    'Dílar',
    'Dólar',
    'Domingo Pérez de Granada',
    'Dúdar',
    'Dúrcal',
    'El Pinar',
    'El Valle',
    'Escúzar',
    'Ferreira',
    'Fonelas',
    'Fornes',
    'Freila',
    'Fuente Vaqueros',
    'Galera',
    'Gobernador',
    'Gójar',
    'Gor',
    'Gorafe',
    'Granada',
    'Guadahortuna',
    'Guadix',
    'Gualchos',
    'Güéjar Sierra',
    'Güevéjar',
    'Huélago',
    'Huéneja',
    'Huéscar',
    'Huétor de Santillán',
    'Huétor Tájar',
    'Huétor Vega',
    'Íllora',
    'Ítrabo',
    'Iznalloz',
    'Játar',
    'Jayena',
    'Jérez del Marquesado',
    'Jete',
    'Jun',
    'Juviles',
    'La Calahorra',
    'La Malahá',
    'La Peza',
    'La Taha',
    'La Zubia',
    'Láchar',
    'Lanjarón',
    'Lanteira',
    'Las Gabias',
    'Lecrín',
    'Lentegí',
    'Lobras',
    'Loja',
    'Los Guájares',
    'Lugros',
    'Lújar',
    'Maracena',
    'Marchal',
    'Moclín',
    'Molvízar',
    'Monachil',
    'Montefrío',
    'Montejícar',
    'Montillana',
    'Moraleda de Zafayona',
    'Morelábor',
    'Motril',
    'Murtas',
    'Nevada',
    'Nigüelas',
    'Nívar',
    'Ogíjares',
    'Orce',
    'Órgiva',
    'Otívar',
    'Padul',
    'Pampaneira',
    'Pedro Martínez',
    'Peligros',
    'Pinos Genil',
    'Pinos Puente',
    'Píñar',
    'Polícar',
    'Polopos',
    'Pórtugos',
    'Puebla de Don Fadrique',
    'Pulianas',
    'Purullena',
    'Quéntar',
    'Rubite',
    'Salar',
    'Salobreña',
    'Santa Cruz del Comercio',
    'Santa Fe',
    'Soportújar',
    'Sorvilán',
    'Torre-Cardela',
    'Torrenueva Costa',
    'Torvizcón',
    'Trevélez',
    'Turón',
    'Ugíjar',
    'Valderrubio',
    'Valle del Zalabí',
    'Válor',
    'Vegas del Genil',
    'Vélez de Benaudalla',
    'Ventas de Huelma',
    'Villa de Otura',
    'Villamena',
    'Villanueva de las Torres',
    'Villanueva Mesía',
    'Víznar',
    'Zafarraya',
    'Zagra',
    'Zújar',
  ],

  // HUELVA (80 municipios)
  '21': [
    'Alájar',
    'Aljaraque',
    'Almonaster la Real',
    'Almonte',
    'Alosno',
    'Aracena',
    'Aroche',
    'Arroyomolinos de León',
    'Ayamonte',
    'Beas',
    'Berrocal',
    'Bollullos Par del Condado',
    'Bonares',
    'Cabezas Rubias',
    'Cala',
    'Calañas',
    'Campofrío',
    'Cañaveral de León',
    'Cartaya',
    'Castaño del Robledo',
    'Chucena',
    'Corteconcepción',
    'Cortegana',
    'Cortelazor',
    'Cumbres de Enmedio',
    'Cumbres de San Bartolomé',
    'Cumbres Mayores',
    'El Almendro',
    'El Campillo',
    'El Cerro de Andévalo',
    'El Granado',
    'Encinasola',
    'Escacena del Campo',
    'Fuenteheridos',
    'Galaroza',
    'Gibraleón',
    'Higuera de la Sierra',
    'Hinojales',
    'Hinojos',
    'Huelva',
    'Isla Cristina',
    'Jabugo',
    'La Granada de Río-Tinto',
    'La Nava',
    'La Palma del Condado',
    'La Zarza-Perrunal',
    'Lepe',
    'Linares de la Sierra',
    'Los Marines',
    'Lucena del Puerto',
    'Manzanilla',
    'Minas de Riotinto',
    'Moguer',
    'Nerva',
    'Niebla',
    'Palos de la Frontera',
    'Paterna del Campo',
    'Paymogo',
    'Puebla de Guzmán',
    'Puerto Moral',
    'Punta Umbría',
    'Rociana del Condado',
    'Rosal de la Frontera',
    'San Bartolomé de la Torre',
    'San Juan del Puerto',
    'San Silvestre de Guzmán',
    'Sanlúcar de Guadiana',
    'Santa Ana la Real',
    'Santa Bárbara de Casa',
    'Santa Olalla del Cala',
    'Trigueros',
    'Valdelarco',
    'Valverde del Camino',
    'Villablanca',
    'Villalba del Alcor',
    'Villanueva de las Cruces',
    'Villanueva de los Castillejos',
    'Villarrasa',
    'Zalamea la Real',
    'Zufre',
  ],

  // JAÉN (97 municipios)
  '23': [
    'Albanchez de Mágina',
    'Alcalá la Real',
    'Alcaudete',
    'Aldeaquemada',
    'Andújar',
    'Arjona',
    'Arjonilla',
    'Arquillos',
    'Arroyo del Ojanco',
    'Baeza',
    'Bailén',
    'Baños de la Encina',
    'Beas de Segura',
    'Bedmar y Garcíez',
    'Begíjar',
    'Bélmez de la Moraleda',
    'Benatae',
    'Cabra del Santo Cristo',
    'Cambil',
    'Campillo de Arenas',
    'Canena',
    'Carboneros',
    'Cárcheles',
    'Castellar',
    'Castillo de Locubín',
    'Cazalilla',
    'Cazorla',
    'Chiclana de Segura',
    'Chilluévar',
    'Escañuela',
    'Espeluy',
    'Frailes',
    'Fuensanta de Martos',
    'Fuerte del Rey',
    'Génave',
    'Guarromán',
    'Higuera de Calatrava',
    'Hinojares',
    'Hornos',
    'Huelma',
    'Huesa',
    'Ibros',
    'Iznatoraf',
    'Jabalquinto',
    'Jaén',
    'Jamilena',
    'Jimena',
    'Jódar',
    'La Carolina',
    'La Guardia de Jaén',
    'La Iruela',
    'La Puerta de Segura',
    'Lahiguera',
    'Larva',
    'Linares',
    'Lopera',
    'Los Villares',
    'Lupión',
    'Mancha Real',
    'Marmolejo',
    'Martos',
    'Mengíbar',
    'Montizón',
    'Navas de San Juan',
    'Noalejo',
    'Orcera',
    'Peal de Becerro',
    'Pegalajar',
    'Porcuna',
    'Pozo Alcón',
    'Puente de Génave',
    'Quesada',
    'Rus',
    'Sabiote',
    'Santa Elena',
    'Santiago de Calatrava',
    'Santiago-Pontones',
    'Santisteban del Puerto',
    'Santo Tomé',
    'Segura de la Sierra',
    'Siles',
    'Sorihuela del Guadalimar',
    'Torreblascopedro',
    'Torredelcampo',
    'Torredonjimeno',
    'Torreperogil',
    'Torres',
    'Torres de Albánchez',
    'Úbeda',
    'Valdepeñas de Jaén',
    'Vilches',
    'Villacarrillo',
    'Villanueva de la Reina',
    'Villanueva del Arzobispo',
    'Villardompardo',
    'Villarrodrigo',
    'Villatorres',
  ],

  // MÁLAGA (103 municipios)
  '29': [
    'Alameda',
    'Alcaucín',
    'Alfarnate',
    'Alfarnatejo',
    'Algarrobo',
    'Algatocín',
    'Alhaurín de la Torre',
    'Alhaurín el Grande',
    'Almáchar',
    'Almargen',
    'Almogía',
    'Álora',
    'Alozaina',
    'Alpandeire',
    'Antequera',
    'Árchez',
    'Archidona',
    'Ardales',
    'Arenas',
    'Arriate',
    'Atajate',
    'Benadalid',
    'Benahavís',
    'Benalauría',
    'Benalmádena',
    'Benamargosa',
    'Benamocarra',
    'Benaoján',
    'Benarrabá',
    'Campillos',
    'Canillas de Aceituno',
    'Canillas de Albaida',
    'Cañete la Real',
    'Carratraca',
    'Cartajima',
    'Cártama',
    'Casabermeja',
    'Casarabonela',
    'Casares',
    'Coín',
    'Colmenar',
    'Comares',
    'Cómpeta',
    'Cortes de la Frontera',
    'Cuevas Bajas',
    'Cuevas de San Marcos',
    'Cuevas del Becerro',
    'Cútar',
    'El Borge',
    'El Burgo',
    'Estepona',
    'Faraján',
    'Frigiliana',
    'Fuengirola',
    'Fuente de Piedra',
    'Gaucín',
    'Genalguacil',
    'Guaro',
    'Humilladero',
    'Igualeja',
    'Istán',
    'Iznate',
    'Jimera de Líbar',
    'Jubrique',
    'Júzcar',
    'Macharaviaya',
    'Málaga',
    'Manilva',
    'Marbella',
    'Mijas',
    'Moclinejo',
    'Mollina',
    'Monda',
    'Montecorto',
    'Montejaque',
    'Nerja',
    'Ojén',
    'Parauta',
    'Periana',
    'Pizarra',
    'Pujerra',
    'Rincón de la Victoria',
    'Riogordo',
    'Ronda',
    'Salares',
    'Sayalonga',
    'Sedella',
    'Serrato',
    'Sierra de Yeguas',
    'Teba',
    'Tolox',
    'Torremolinos',
    'Torrox',
    'Totalán',
    'Valle de Abdalajís',
    'Vélez-Málaga',
    'Villanueva de Algaidas',
    'Villanueva de la Concepción',
    'Villanueva de Tapia',
    'Villanueva del Rosario',
    'Villanueva del Trabuco',
    'Viñuela',
    'Yunquera',
  ],

  // SEVILLA (106 municipios)
  '41': [
    'Aguadulce',
    'Alanís',
    'Albaida del Aljarafe',
    'Alcalá de Guadaíra',
    'Alcalá del Río',
    'Alcolea del Río',
    'Algámitas',
    'Almadén de la Plata',
    'Almensilla',
    'Arahal',
    'Aznalcázar',
    'Aznalcóllar',
    'Badolatosa',
    'Benacazón',
    'Bollullos de la Mitación',
    'Bormujos',
    'Brenes',
    'Burguillos',
    'Camas',
    'Cantillana',
    'Cañada Rosal',
    'Carmona',
    'Carrión de los Céspedes',
    'Casariche',
    'Castilblanco de los Arroyos',
    'Castilleja de Guzmán',
    'Castilleja de la Cuesta',
    'Castilleja del Campo',
    'Cazalla de la Sierra',
    'Constantina',
    'Coria del Río',
    'Coripe',
    'Dos Hermanas',
    'Écija',
    'El Castillo de las Guardas',
    'El Coronil',
    'El Cuervo de Sevilla',
    'El Garrobo',
    'El Madroño',
    'El Palmar de Troya',
    'El Pedroso',
    'El Real de la Jara',
    'El Ronquillo',
    'El Rubio',
    'El Saucejo',
    'El Viso del Alcor',
    'Espartinas',
    'Estepa',
    'Fuentes de Andalucía',
    'Gelves',
    'Gerena',
    'Gilena',
    'Gines',
    'Guadalcanal',
    'Guillena',
    'Herrera',
    'Huévar del Aljarafe',
    'Isla Mayor',
    'La Algaba',
    'La Campana',
    'La Luisiana',
    'La Puebla de Cazalla',
    'La Puebla de los Infantes',
    'La Puebla del Río',
    'La Rinconada',
    'La Roda de Andalucía',
    'Lantejuela',
    'Las Cabezas de San Juan',
    'Las Navas de la Concepción',
    'Lebrija',
    'Lora de Estepa',
    'Lora del Río',
    'Los Corrales',
    'Los Molares',
    'Los Palacios y Villafranca',
    'Mairena del Alcor',
    'Mairena del Aljarafe',
    'Marchena',
    'Marinaleda',
    'Martín de la Jara',
    'Montellano',
    'Morón de la Frontera',
    'Olivares',
    'Osuna',
    'Palomares del Río',
    'Paradas',
    'Pedrera',
    'Peñaflor',
    'Pilas',
    'Pruna',
    'Salteras',
    'San Juan de Aznalfarache',
    'San Nicolás del Puerto',
    'Sanlúcar la Mayor',
    'Santiponce',
    'Sevilla',
    'Tocina',
    'Tomares',
    'Umbrete',
    'Utrera',
    'Valencina de la Concepción',
    'Villamanrique de la Condesa',
    'Villanueva de San Juan',
    'Villanueva del Ariscal',
    'Villanueva del Río y Minas',
    'Villaverde del Río',
  ],

  // ALMERÍA (103 municipios)
  '04': [
    'Abla',
    'Abrucena',
    'Adra',
    'Albanchez',
    'Alboloduy',
    'Albox',
    'Alcolea',
    'Alcóntar',
    'Alcudia de Monteagud',
    'Alhabia',
    'Alhama de Almería',
    'Alicún',
    'Almería',
    'Almócita',
    'Alsodux',
    'Antas',
    'Arboleas',
    'Armuña de Almanzora',
    'Bacares',
    'Balanegra',
    'Bayárcal',
    'Bayarque',
    'Bédar',
    'Beires',
    'Benahadux',
    'Benitagla',
    'Benizalón',
    'Bentarique',
    'Berja',
    'Canjáyar',
    'Cantoria',
    'Carboneras',
    'Castro de Filabres',
    'Chercos',
    'Chirivel',
    'Cóbdar',
    'Cuevas del Almanzora',
    'Dalías',
    'El Ejido',
    'Enix',
    'Felix',
    'Fines',
    'Fiñana',
    'Fondón',
    'Gádor',
    'Garrucha',
    'Gérgal',
    'Huécija',
    'Huércal de Almería',
    'Huércal-Overa',
    'Íllar',
    'Instinción',
    'La Mojonera',
    'Laroya',
    'Las Tres Villas',
    'Láujar de Andarax',
    'Líjar',
    'Los Gallardos',
    'Lubrín',
    'Lucainena de las Torres',
    'Lúcar',
    'Macael',
    'María',
    'Mojácar',
    'Nacimiento',
    'Níjar',
    'Ohanes',
    'Olula de Castro',
    'Olula del Río',
    'Oria',
    'Padules',
    'Partaloa',
    'Paterna del Río',
    'Pechina',
    'Pulpí',
    'Purchena',
    'Rágol',
    'Rioja',
    'Roquetas de Mar',
    'Santa Cruz de Marchena',
    'Santa Fe de Mondújar',
    'Senés',
    'Serón',
    'Sierro',
    'Somontín',
    'Sorbas',
    'Suflí',
    'Tabernas',
    'Taberno',
    'Tahal',
    'Terque',
    'Tíjola',
    'Turre',
    'Turrillas',
    'Uleila del Campo',
    'Urrácal',
    'Velefique',
    'Vélez-Blanco',
    'Vélez-Rubio',
    'Vera',
    'Viator',
    'Vícar',
    'Zurgena',
  ],

};
