export const certificadoPedidosContratosConfig = {
  id: 'certificado-pedidos-contratos',
  title: 'Certificado de Pedidos y/o Contratos',
  description: 'Relación certificada de pedidos y/o contratos relativos a las actuaciones realizadas',
  fileName: 'Certificado_Pedidos_Contratos.pdf',
  route: '/justificaciones/certificado-pedidos-contratos',
  
  fields: [
    // Datos principales
    { name: 'personaBeneficiaria', label: 'Persona beneficiaria', type: 'text' },
    { name: 'nif', label: 'NIF', type: 'text' },
    { name: 'direccion', label: 'Dirección', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'expediente', label: 'Nº Expediente', type: 'text' },
    { name: 'ordenAnio', label: 'Año de la Orden', type: 'text' },
    
    // Fecha firma
    { name: 'diaFirma', label: 'Día de firma', type: 'text' },
    { name: 'mesFirma', label: 'Mes de firma', type: 'text' },
    { name: 'anioFirma', label: 'Año de firma', type: 'text' },
    
    // Firma
    { name: 'firma', label: 'Firma', type: 'file' },
    
    // Pedido 1
    { name: 'pedido1Concepto', label: 'Pedido 1 - Concepto', type: 'text' },
    { name: 'pedido1Proveedor', label: 'Pedido 1 - Proveedor', type: 'text' },
    { name: 'pedido1IdOferta', label: 'Pedido 1 - Id. Oferta', type: 'text' },
    { name: 'pedido1FechaOferta', label: 'Pedido 1 - Fecha Oferta', type: 'text' },
    { name: 'pedido1ImporteOferta', label: 'Pedido 1 - Importe Oferta', type: 'text' },
    { name: 'pedido1IdPedido', label: 'Pedido 1 - Id. Pedido', type: 'text' },
    { name: 'pedido1FechaPedido', label: 'Pedido 1 - Fecha Pedido', type: 'text' },
    { name: 'pedido1ImportePedido', label: 'Pedido 1 - Importe Pedido', type: 'text' },
    
    // Pedido 2
    { name: 'pedido2Concepto', label: 'Pedido 2 - Concepto', type: 'text' },
    { name: 'pedido2Proveedor', label: 'Pedido 2 - Proveedor', type: 'text' },
    { name: 'pedido2IdOferta', label: 'Pedido 2 - Id. Oferta', type: 'text' },
    { name: 'pedido2FechaOferta', label: 'Pedido 2 - Fecha Oferta', type: 'text' },
    { name: 'pedido2ImporteOferta', label: 'Pedido 2 - Importe Oferta', type: 'text' },
    { name: 'pedido2IdPedido', label: 'Pedido 2 - Id. Pedido', type: 'text' },
    { name: 'pedido2FechaPedido', label: 'Pedido 2 - Fecha Pedido', type: 'text' },
    { name: 'pedido2ImportePedido', label: 'Pedido 2 - Importe Pedido', type: 'text' },
    
    // Pedido 3
    { name: 'pedido3Concepto', label: 'Pedido 3 - Concepto', type: 'text' },
    { name: 'pedido3Proveedor', label: 'Pedido 3 - Proveedor', type: 'text' },
    { name: 'pedido3IdOferta', label: 'Pedido 3 - Id. Oferta', type: 'text' },
    { name: 'pedido3FechaOferta', label: 'Pedido 3 - Fecha Oferta', type: 'text' },
    { name: 'pedido3ImporteOferta', label: 'Pedido 3 - Importe Oferta', type: 'text' },
    { name: 'pedido3IdPedido', label: 'Pedido 3 - Id. Pedido', type: 'text' },
    { name: 'pedido3FechaPedido', label: 'Pedido 3 - Fecha Pedido', type: 'text' },
    { name: 'pedido3ImportePedido', label: 'Pedido 3 - Importe Pedido', type: 'text' },
    
    // Pedido 4
    { name: 'pedido4Concepto', label: 'Pedido 4 - Concepto', type: 'text' },
    { name: 'pedido4Proveedor', label: 'Pedido 4 - Proveedor', type: 'text' },
    { name: 'pedido4IdOferta', label: 'Pedido 4 - Id. Oferta', type: 'text' },
    { name: 'pedido4FechaOferta', label: 'Pedido 4 - Fecha Oferta', type: 'text' },
    { name: 'pedido4ImporteOferta', label: 'Pedido 4 - Importe Oferta', type: 'text' },
    { name: 'pedido4IdPedido', label: 'Pedido 4 - Id. Pedido', type: 'text' },
    { name: 'pedido4FechaPedido', label: 'Pedido 4 - Fecha Pedido', type: 'text' },
    { name: 'pedido4ImportePedido', label: 'Pedido 4 - Importe Pedido', type: 'text' },
    
    // Pedido 5
    { name: 'pedido5Concepto', label: 'Pedido 5 - Concepto', type: 'text' },
    { name: 'pedido5Proveedor', label: 'Pedido 5 - Proveedor', type: 'text' },
    { name: 'pedido5IdOferta', label: 'Pedido 5 - Id. Oferta', type: 'text' },
    { name: 'pedido5FechaOferta', label: 'Pedido 5 - Fecha Oferta', type: 'text' },
    { name: 'pedido5ImporteOferta', label: 'Pedido 5 - Importe Oferta', type: 'text' },
    { name: 'pedido5IdPedido', label: 'Pedido 5 - Id. Pedido', type: 'text' },
    { name: 'pedido5FechaPedido', label: 'Pedido 5 - Fecha Pedido', type: 'text' },
    { name: 'pedido5ImportePedido', label: 'Pedido 5 - Importe Pedido', type: 'text' },
  ],

  defaultData: {
    personaBeneficiaria: '',
    nif: '',
    direccion: '',
    provincia: '',
    expediente: '',
    ordenAnio: '',
    diaFirma: '',
    mesFirma: '',
    anioFirma: '',
    firma: '',
    pedido1Concepto: '',
    pedido1Proveedor: '',
    pedido1IdOferta: '',
    pedido1FechaOferta: '',
    pedido1ImporteOferta: '',
    pedido1IdPedido: '',
    pedido1FechaPedido: '',
    pedido1ImportePedido: '',
    pedido2Concepto: '',
    pedido2Proveedor: '',
    pedido2IdOferta: '',
    pedido2FechaOferta: '',
    pedido2ImporteOferta: '',
    pedido2IdPedido: '',
    pedido2FechaPedido: '',
    pedido2ImportePedido: '',
    pedido3Concepto: '',
    pedido3Proveedor: '',
    pedido3IdOferta: '',
    pedido3FechaOferta: '',
    pedido3ImporteOferta: '',
    pedido3IdPedido: '',
    pedido3FechaPedido: '',
    pedido3ImportePedido: '',
    pedido4Concepto: '',
    pedido4Proveedor: '',
    pedido4IdOferta: '',
    pedido4FechaOferta: '',
    pedido4ImporteOferta: '',
    pedido4IdPedido: '',
    pedido4FechaPedido: '',
    pedido4ImportePedido: '',
    pedido5Concepto: '',
    pedido5Proveedor: '',
    pedido5IdOferta: '',
    pedido5FechaOferta: '',
    pedido5ImporteOferta: '',
    pedido5IdPedido: '',
    pedido5FechaPedido: '',
    pedido5ImportePedido: '',
  },

  fieldMapping: {
    personaBeneficiaria: 'apellidosNombre',
    nif: 'nifCif',
    direccion: 'direccionCompleta',
    provincia: 'provinciaEmplazamiento',
    expediente: 'expedienteEco',
    diaFirma: 'diaFirmaJustificacion',
    mesFirma: 'mesFirmaJustificacion',
    anioFirma: 'anioFirmaJustificacion',
    firma: 'firma',
    pedido1Concepto: 'pedido1Concepto',
    pedido1Proveedor: 'pedido1Proveedor',
    pedido1IdOferta: 'pedido1IdOferta',
    pedido1FechaOferta: 'pedido1FechaOferta',
    pedido1ImporteOferta: 'pedido1ImporteOferta',
    pedido1IdPedido: 'pedido1IdPedido',
    pedido1FechaPedido: 'pedido1FechaPedido',
    pedido1ImportePedido: 'pedido1ImportePedido',
    pedido2Concepto: 'pedido2Concepto',
    pedido2Proveedor: 'pedido2Proveedor',
    pedido2IdOferta: 'pedido2IdOferta',
    pedido2FechaOferta: 'pedido2FechaOferta',
    pedido2ImporteOferta: 'pedido2ImporteOferta',
    pedido2IdPedido: 'pedido2IdPedido',
    pedido2FechaPedido: 'pedido2FechaPedido',
    pedido2ImportePedido: 'pedido2ImportePedido',
    pedido3Concepto: 'pedido3Concepto',
    pedido3Proveedor: 'pedido3Proveedor',
    pedido3IdOferta: 'pedido3IdOferta',
    pedido3FechaOferta: 'pedido3FechaOferta',
    pedido3ImporteOferta: 'pedido3ImporteOferta',
    pedido3IdPedido: 'pedido3IdPedido',
    pedido3FechaPedido: 'pedido3FechaPedido',
    pedido3ImportePedido: 'pedido3ImportePedido',
    pedido4Concepto: 'pedido4Concepto',
    pedido4Proveedor: 'pedido4Proveedor',
    pedido4IdOferta: 'pedido4IdOferta',
    pedido4FechaOferta: 'pedido4FechaOferta',
    pedido4ImporteOferta: 'pedido4ImporteOferta',
    pedido4IdPedido: 'pedido4IdPedido',
    pedido4FechaPedido: 'pedido4FechaPedido',
    pedido4ImportePedido: 'pedido4ImportePedido',
    pedido5Concepto: 'pedido5Concepto',
    pedido5Proveedor: 'pedido5Proveedor',
    pedido5IdOferta: 'pedido5IdOferta',
    pedido5FechaOferta: 'pedido5FechaOferta',
    pedido5ImporteOferta: 'pedido5ImporteOferta',
    pedido5IdPedido: 'pedido5IdPedido',
    pedido5FechaPedido: 'pedido5FechaPedido',
    pedido5ImportePedido: 'pedido5ImportePedido',
  },

  capabilities: {
    pdf: true,
    print: true,
    download: true,
  },

  category: 'justificaciones',
}
