export const certificadoPedidosConfig = {
  id: 'certificado-pedidos',
  title: 'Certificado de Pedidos y Contratos',
  description: 'Relación certificada y copia de los pedidos y/o contratos relativos a las actuaciones realizadas.',
  fileName: 'certificado-pedidos.pdf',
  route: '/justificaciones/certificado-pedidos',
  fields: [
    { name: 'personaBeneficiaria', label: 'Persona beneficiaria', type: 'text', fullWidth: true },
    { name: 'nif', label: 'NIF', type: 'text' },
    { name: 'direccion', label: 'Dirección', type: 'text', fullWidth: true },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'expediente', label: 'N.º Expediente', type: 'text' },
    { name: 'concepto', label: 'Concepto', type: 'text' },
    { name: 'proveedor', label: 'Proveedor', type: 'text', fullWidth: true },
    { name: 'idOferta', label: 'Id. Oferta', type: 'text' },
    { name: 'fechaOferta', label: 'Fecha Oferta', type: 'date' },
    { name: 'importeOferta', label: 'Importe Oferta (€)', type: 'text' },
    { name: 'idPedido', label: 'Id Pedido', type: 'text' },
    { name: 'fechaPedido', label: 'Fecha Pedido', type: 'date' },
    { name: 'importePedido', label: 'Importe Pedido (€)', type: 'text' },
    { name: 'diaPedido', label: 'Día de pedido', type: 'text' },
    { name: 'mesPedido', label: 'Mes de pedido', type: 'text' },
    { name: 'anioPedido', label: 'Año de pedido', type: 'text' },
    { name: 'firmaImagen', label: 'Imagen de Firma', type: 'image' }
  ],
  defaultData: {
    personaBeneficiaria: '',
    nif: '',
    direccion: '',
    provincia: '',
    expediente: '',
    concepto: '',
    proveedor: '',
    idOferta: '',
    fechaOferta: '',
    importeOferta: '',
    idPedido: '',
    fechaPedido: '',
    importePedido: '',
    diaPedido: '',
    mesPedido: '',
    anioPedido: '',
    firmaImagen: ''
  },
  fieldMapping: {
    personaBeneficiaria: 'apellidosNombre',
    nif: 'nifCif',
    direccion: 'emplazamientoCalle',
    provincia: 'provinciaEmplazamiento',
    expediente: 'expediente',
    concepto: 'concepto',
    proveedor: 'proveedor',
    idOferta: 'idOferta',
    fechaOferta: 'fechaOferta',
    importeOferta: 'importeOferta',
    idPedido: 'idPedido',
    fechaPedido: 'fechaPedido',
    importePedido: 'importePedido',
    diaPedido: 'diaPedido',
    mesPedido: 'mesPedido',
    anioPedido: 'anioPedido',
    firmaImagen: 'firma'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificaciones',
  component: 'CertificadoPedidos'
}
