export const l3PagoAnticipado50Config = {
  id: 'l3-pago-anticipado-50',
  title: 'L3.- Pago Anticipado (50%)',
  description: 'Documento para el anticipo del 50% en la línea 3',
  fileName: 'L3.- Pago Anticipado (50%).pdf',
  route: '/justificaciones/l3-pago-anticipado-50',
  fields: [
    { name: 'expediente', label: 'Expediente', type: 'text' },
    { name: 'apellidosNombre', label: 'Nombre y Apellidos', type: 'text', fullWidth: true },
    { name: 'dni', label: 'DNI', type: 'text' },
    { name: 'telefono', label: 'Teléfono', type: 'text' },
    { name: 'correoElectronico', label: 'Correo Electrónico', type: 'text' },
    { name: 'apellidosNombreRepresentante', label: 'Nombre del Representante', type: 'text', fullWidth: true },
    { name: 'dniRepresentante', label: 'DNI Representante', type: 'text' },
    { name: 'actuaCalidad', label: 'Actúa en calidad de', type: 'text' },
    { name: 'telefonoRepresentante', label: 'Teléfono Representante', type: 'text' },
    { name: 'correoElectronicoRepresentante', label: 'Correo Electrónico Representante', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'dia', label: 'Día', type: 'text' },
    { name: 'mes', label: 'Mes', type: 'text' },
    { name: 'anio', label: 'Año', type: 'text' },
    { name: 'personaFirma', label: 'Persona que firma', type: 'text' },
    { name: 'firma', label: 'Firma (Imagen)', type: 'file', accept: 'image/*' },
    { name: 'check_1', label: 'Check 1 (Documentación)', type: 'checkbox' },
    { name: 'check_2', label: 'Check 2 (Documentación)', type: 'checkbox' },
    { name: 'check_3', label: 'Check 3 (Documentación)', type: 'checkbox' },
    { name: 'check_4', label: 'Check 4 (Documentación)', type: 'checkbox' },
    { name: 'check_5', label: 'Check 5 (Documentación)', type: 'checkbox' },
    { name: 'check_6', label: 'Check 6 (Documentación)', type: 'checkbox' }
  ],
  defaultData: {
    expediente: '',
    apellidosNombre: '',
    dni: '',
    telefono: '',
    correoElectronico: '',
    apellidosNombreRepresentante: '',
    dniRepresentante: '',
    actuaCalidad: '',
    telefonoRepresentante: '',
    correoElectronicoRepresentante: '',
    provincia: '',
    dia: '',
    mes: '',
    anio: '',
    personaFirma: '',
    firma: '',
    check_1: false,
    check_2: false,
    check_3: false,
    check_4: false,
    check_5: false,
    check_6: false
  },
  fieldMapping: {
    expediente: 'expedienteEco',
    apellidosNombre: 'apellidosNombre',
    dni: 'nifCif',
    telefono: 'telefono',
    correoElectronico: 'correoElectronicoEmplazamiento',
    apellidosNombreRepresentante: 'nombreRepresentanteEntidad',
    dniRepresentante: 'dniRepresentanteEntidad',
    actuaCalidad: 'tipoActuacion',
    telefonoRepresentante: 'telefonoRepresentanteEntidad',
    correoElectronicoRepresentante: 'correoElectronicoRepresentanteEntidad',
    provincia: 'provinciaEmplazamiento',
    dia: 'diaFirmaJustificacion',
    mes: 'mesFirmaJustificacion',
    anio: 'anioFirmaJustificacion',
    personaFirma: 'apellidosNombre',
    firma: 'firma',
    check_1: 'check_1',
    check_2: 'check_2',
    check_3: 'check_3',
    check_4: 'check_4',
    check_5: 'check_5',
    check_6: 'check_6'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificacion50'
}
