export const l3PagoAnticipado50Config = {
  id: 'l3-pago-anticipado-50',
  title: 'L3.- Pago Anticipado (50%)',
  description: 'Documento para el anticipo del 50% en la línea 3',
  fileName: 'L3.- Pago Anticipado (50%).pdf',
  route: '/justificaciones/l3-pago-anticipado-50',
  fields: [
    { name: 'expediente', label: 'Expediente', type: 'text' },
    { name: 'apellidosNombre', label: 'Nombre y Apellidos', type: 'text', fullWidth: true },
    { name: 'dni', label: 'DNI', type: 'text' },
    { name: 'telefono', label: 'Teléfono', type: 'text' },
    { name: 'correoElectronico', label: 'Correo Electrónico', type: 'text' },
    { name: 'apellidosNombreRepresentante', label: 'Nombre del Representante', type: 'text', fullWidth: true },
    { name: 'dniRepresentante', label: 'DNI Representante', type: 'text' },
    { name: 'actuaCalidad', label: 'Actúa en calidad de', type: 'text' },
    { name: 'telefonoRepresentante', label: 'Teléfono Representante', type: 'text' },
    { name: 'correoElectronicoRepresentante', label: 'Correo Electrónico Representante', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'dia', label: 'Día', type: 'text' },
    { name: 'mes', label: 'Mes', type: 'text' },
    { name: 'anio', label: 'Año', type: 'text' },
    { name: 'personaFirma', label: 'Persona que firma', type: 'text' },
    { name: 'firma', label: 'Firma (Imagen)', type: 'file', accept: 'image/*' }
  ],
  defaultData: {
    expediente: '2024/001-L3-ANT',
    apellidosNombre: 'JUAN PEREZ GARCIA',
    dni: '12345678X',
    telefono: '600111222',
    correoElectronico: 'juan.perez@example.com',
    apellidosNombreRepresentante: 'REPRESENTANTE S.L.',
    dniRepresentante: 'B12345678',
    actuaCalidad: 'Administrador Unico',
    telefonoRepresentante: '600333444',
    correoElectronicoRepresentante: 'rep@example.com',
    provincia: 'SEVILLA',
    dia: '10',
    mes: 'Abril',
    anio: '2024',
    personaFirma: 'JUAN PEREZ GARCIA',
    firma: '/firma-solay-miguel.jpeg'
  },
  fieldMapping: {
    expediente: 'expedienteEco',
    apellidosNombre: 'apellidosNombre',
    dni: 'nifCif',
    telefono: 'telefono',
    correoElectronico: 'correoElectronicoEmplazamiento',
    apellidosNombreRepresentante: 'nombreRepresentanteEntidad',
    dniRepresentante: 'dniRepresentanteEntidad',
    actuaCalidad: 'tipoActuacion',
    telefonoRepresentante: 'telefonoRepresentanteEntidad',
    correoElectronicoRepresentante: 'correoElectronicoRepresentanteEntidad',
    provincia: 'provinciaEmplazamiento',
    dia: 'diaFirmaJustificacion',
    mes: 'mesFirmaJustificacion',
    anio: 'anioFirmaJustificacion',
    personaFirma: 'apellidosNombre',
    firma: 'firma'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificacion50'
}
