export const l4PagoAnticipado100Config = {
  id: 'l4-pago-anticipado-100',
  title: 'L4.- Pago Anticipado (100%)',
  description: 'Documento para el anticipo del 100% en la línea 4',
  fileName: 'L4.- Pago Anticipado (100%).pdf',
  route: '/justificaciones/l4-pago-anticipado-100',
  fields: [
    { name: 'expediente', label: 'Expediente', type: 'text' },
    { name: 'apellidosNombre', label: 'Nombre y Apellidos', type: 'text', fullWidth: true },
    { name: 'dni', label: 'DNI', type: 'text' },
    { name: 'telefono', label: 'Teléfono', type: 'text' },
    { name: 'correoElectronico', label: 'Correo Electrónico', type: 'text' },
    { name: 'apellidosNombreRepresentante', label: 'Nombre del Representante', type: 'text', fullWidth: true },
    { name: 'dniRepresentante', label: 'DNI Representante', type: 'text' },
    { name: 'actuaCalidad', label: 'Actúa en calidad de', type: 'text' },
    { name: 'telefonoRepresentante', label: 'Teléfono Representante', type: 'text' },
    { name: 'correoElectronicoRepresentante', label: 'Correo Electrónico Representante', type: 'text' },
    { name: 'provincia', label: 'Provincia', type: 'text' },
    { name: 'dia', label: 'Día', type: 'text' },
    { name: 'mes', label: 'Mes', type: 'text' },
    { name: 'anio', label: 'Año', type: 'text' },
    { name: 'personaFirma', label: 'Persona que firma', type: 'text' },
    { name: 'firma', label: 'Firma (Imagen)', type: 'file', accept: 'image/*' }
  ],
  defaultData: {
    expediente: '',
    apellidosNombre: '',
    dni: '',
    telefono: '',
    correoElectronico: '',
    apellidosNombreRepresentante: '',
    dniRepresentante: '',
    actuaCalidad: '',
    telefonoRepresentante: '',
    correoElectronicoRepresentante: '',
    provincia: '',
    dia: '',
    mes: '',
    anio: '',
    personaFirma: '',
    firma: '',
    check_1: true,
    check_2: true,
    check_3: true,
    check_4: true,
    check_5: true,
    check_6: true
  },
  fieldMapping: {
    expediente: 'expedienteEco',
    apellidosNombre: 'apellidosNombre',
    dni: 'nifCif',
    telefono: 'telefono',
    correoElectronico: 'correoElectronicoEmplazamiento',
    apellidosNombreRepresentante: 'nombreRepresentanteEntidad',
    dniRepresentante: 'dniRepresentanteEntidad',
    actuaCalidad: 'tipoActuacion',
    telefonoRepresentante: 'telefonoRepresentanteEntidad',
    correoElectronicoRepresentante: 'correoElectronicoRepresentanteEntidad',
    provincia: 'provinciaEmplazamiento',
    dia: 'diaFirmaJustificacion',
    mes: 'mesFirmaJustificacion',
    anio: 'anioFirmaJustificacion',
    personaFirma: 'apellidosNombre',
    firma: 'firma'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificacion50'
}
