export const memoriaJustificativaActuacionConfig = {
  id: 'memoria-justificativa-actuacion',
  title: 'Memoria Justificativa de Actuación',
  description: 'Documento de memoria técnica justificativa de la actuación energética realizada',
  fileName: 'memoria-justificativa-actuacion.pdf',
  route: '/justificaciones/memoria-justificativa-actuacion',
  fields: [
    { type: 'subsection', label: 'Datos Generales', name: 'datosGenerales', description: 'Información básica del inmueble y proyecto' },
    { name: 'expediente', label: 'Expediente', type: 'text', fullWidth: true },
    { name: 'nif', label: 'NIF', type: 'text' },
    { name: 'tipoEdificio', label: 'Tipo de Edificio', type: 'text', fullWidth: true },
    { name: 'domicilio', label: 'Domicilio', type: 'text', fullWidth: true },
    { name: 'zaharilla', label: 'Zaharilla', type: 'text', fullWidth: true },
    { name: 'tecnicoRedactor', label: 'Técnico Redactor', type: 'text', fullWidth: true },
    
    { type: 'subsection', label: 'Especificaciones Técnicas', name: 'especificacionesTecnicas', description: 'Datos de rendimiento energético' },
    { name: 'potenciaTermica', label: 'Potencia Térmica (kW)', type: 'text' },
    { name: 'resistenciaElectrica', label: 'Resistencia Eléctrica (kW)', type: 'text' },
    { name: 'potenciaTotal', label: 'Potencia Total (kW)', type: 'text' },
    { name: 'tipoSoporte', label: 'Tipo de Soporte', type: 'select', options: ['PLANA', 'INCLINADA', 'AMBAS'] },
    
    { type: 'subsection', label: 'Fechas y Costes', name: 'fechasYCostes', description: 'Información temporal y económica' },
    { name: 'fechaConclusionDia', label: 'Día Conclusión', type: 'text' },
    { name: 'fechaConclusionMes', label: 'Mes Conclusión', type: 'text' },
    { name: 'fechaConclusionAnio', label: 'Año Conclusión', type: 'text' },
    { name: 'mesNombre', label: 'Mes (Nombre)', type: 'text' },
    { name: 'importeCertificacion', label: 'Importe Certificación', type: 'text' },
    { name: 'importeOtrosCostes', label: 'Importe Otros Costes', type: 'text' },
    { name: 'importeTotal', label: 'Importe Total', type: 'text' },
    
    { type: 'subsection', label: 'Firma y Documentación', name: 'firmaYDocumentacion', description: 'Datos del firmante' },
    { name: 'fechaFirmaJustificacion', label: 'Fecha Firma', type: 'date' },
    { name: 'nombreFirma', label: 'Nombre del Firmante', type: 'text', fullWidth: true },
    { name: 'firmaImagen', label: 'Imagen de Firma', type: 'image' },
    
    { type: 'subsection', label: 'Opciones Especiales', name: 'opcionesEspeciales', description: 'Configuración adicional' },
    { name: 'aerotermia', label: 'Incluir sección de Aerotermia', type: 'checkbox' }
  ],
  defaultData: {
    expediente: '',
    nif: '',
    tipoEdificio: 'Vivienda',
    domicilio: '',
    zaharilla: '',
    tecnicoRedactor: '',
    potenciaTermica: '',
    resistenciaElectrica: '',
    potenciaTotal: '',
    tipoSoporte: 'PLANA',
    fechaConclusionDia: '',
    fechaConclusionMes: '',
    fechaConclusionAnio: '',
    mesNombre: '',
    importeCertificacion: '0,00',
    importeOtrosCostes: '0,00',
    importeTotal: '0,00',
    fechaFirmaJustificacion: new Date().toISOString().split('T')[0],
    nombreFirma: '',
    firmaImagen: '',
    aerotermia: false
  },
  fieldMapping: {
    expediente: 'expediente',
    nif: 'nif',
    tipoEdificio: 'tipoEdificio',
    domicilio: 'emplazamientoCalle',
    zaharilla: 'zaharilla',
    tecnicoRedactor: 'tecnicoRedactor',
    potenciaTermica: 'potenciaTermica',
    resistenciaElectrica: 'resistenciaElectrica',
    potenciaTotal: 'potenciaTotal',
    tipoSoporte: 'tipoSoporte',
    fechaConclusionDia: 'fechaConclusionDia',
    fechaConclusionMes: 'fechaConclusionMes',
    fechaConclusionAnio: 'fechaConclusionAnio',
    mesNombre: 'mesNombre',
    importeCertificacion: 'importeCertificacion',
    importeOtrosCostes: 'importeOtrosCostes',
    importeTotal: 'importeTotal',
    fechaFirmaJustificacion: 'fechaFirmaJustificacion',
    nombreFirma: 'apellidosNombre',
    firmaImagen: 'firma',
    aerotermia: 'aerotermia'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  }
};
