export const memoriaEconomicaConfig = {
  id: 'memoria-economica',
  title: '2.- Memoria Económica',
  description: 'Documento de memoria económica con aportación de justificantes de gasto de subvención',
  fileName: 'memoria-economica.pdf',
  route: '/justificaciones/memoria-economica',
  fields: [
    { name: 'expediente', label: 'Expediente', type: 'text', fullWidth: true },
    { name: 'nif', label: 'NIF', type: 'text' },
    { name: 'edificioVivienda', label: 'Tipo de Edificio', type: 'text', placeholder: 'ej: vivienda' },
    { name: 'l3l4', label: 'Línea de Subvención', type: 'text', placeholder: 'ej: Línea 3' },
    { name: 'parrafoTexto', label: 'Párrafo Introducción', type: 'textarea', fullWidth: true },
    // Campos fila 1
    { name: 'numeroFactura1', label: 'Nº Factura 1', type: 'text' },
    { name: 'fechaFactura1', label: 'Fecha Factura 1', type: 'date' },
    { name: 'cf1', label: 'CF 1', type: 'text' },
    { name: 'acreedor1', label: 'Acreedor 1', type: 'text' },
    { name: 'concepto1', label: 'Concepto 1', type: 'text' },
    { name: 'fechaPago1', label: 'Fecha Pago 1', type: 'date' },
    { name: 'importe1', label: 'Importe 1', type: 'text' },
    // Campos fila 2
    { name: 'numeroFactura2', label: 'Nº Factura 2', type: 'text' },
    { name: 'fechaFactura2', label: 'Fecha Factura 2', type: 'date' },
    { name: 'cf2', label: 'CF 2', type: 'text' },
    { name: 'acreedor2', label: 'Acreedor 2', type: 'text' },
    { name: 'concepto2', label: 'Concepto 2', type: 'text' },
    { name: 'fechaPago2', label: 'Fecha Pago 2', type: 'date' },
    { name: 'importe2', label: 'Importe 2', type: 'text' },
    // Campos fila 3
    { name: 'numeroFactura3', label: 'Nº Factura 3', type: 'text' },
    { name: 'fechaFactura3', label: 'Fecha Factura 3', type: 'date' },
    { name: 'cf3', label: 'CF 3', type: 'text' },
    { name: 'acreedor3', label: 'Acreedor 3', type: 'text' },
    { name: 'concepto3', label: 'Concepto 3', type: 'text' },
    { name: 'fechaPago3', label: 'Fecha Pago 3', type: 'date' },
    { name: 'importe3', label: 'Importe 3', type: 'text' },
    // Campos fila 4
    { name: 'numeroFactura4', label: 'Nº Factura 4', type: 'text' },
    { name: 'fechaFactura4', label: 'Fecha Factura 4', type: 'date' },
    { name: 'cf4', label: 'CF 4', type: 'text' },
    { name: 'acreedor4', label: 'Acreedor 4', type: 'text' },
    { name: 'concepto4', label: 'Concepto 4', type: 'text' },
    { name: 'fechaPago4', label: 'Fecha Pago 4', type: 'date' },
    { name: 'importe4', label: 'Importe 4', type: 'text' },
    // Campos fila 5
    { name: 'numeroFactura5', label: 'Nº Factura 5', type: 'text' },
    { name: 'fechaFactura5', label: 'Fecha Factura 5', type: 'date' },
    { name: 'cf5', label: 'CF 5', type: 'text' },
    { name: 'acreedor5', label: 'Acreedor 5', type: 'text' },
    { name: 'concepto5', label: 'Concepto 5', type: 'text' },
    { name: 'fechaPago5', label: 'Fecha Pago 5', type: 'date' },
    { name: 'importe5', label: 'Importe 5', type: 'text' },
    // Campos totales
    { name: 'totalCantidadJustificada', label: 'Total Cantidad Justificada', type: 'text' },
    { name: 'presupuestoInicial', label: 'Presupuesto Inicial', type: 'text' },
    { name: 'inversionRealizada', label: 'Inversión Realizada', type: 'text' },
    { name: 'desviacion', label: 'Desviación (con IVA si es subvencionable)', type: 'text' },
    { name: 'diaFirmaJustificacion', label: 'Día Firma', type: 'text' },
    { name: 'mesFirmaJustificacion', label: 'Mes Firma', type: 'text' },
    { name: 'anioFirmaJustificacion', label: 'Año Firma', type: 'text' },
    { name: 'nombreFirma', label: 'Nombre Firma', type: 'text', fullWidth: true },
    { name: 'firmaImagen', label: 'Imagen de Firma', type: 'image' }
  ],
  defaultData: {
    expediente: '',
    nif: '',
    edificioVivienda: '',
    l3l4: '',
    parrafoTexto: '',
    numeroFactura1: '',
    fechaFactura1: '',
    cf1: '',
    acreedor1: '',
    concepto1: '',
    fechaPago1: '',
    importe1: '',
    numeroFactura2: '',
    fechaFactura2: '',
    cf2: '',
    acreedor2: '',
    concepto2: '',
    fechaPago2: '',
    importe2: '',
    numeroFactura3: '',
    fechaFactura3: '',
    cf3: '',
    acreedor3: '',
    concepto3: '',
    fechaPago3: '',
    importe3: '',
    numeroFactura4: '',
    fechaFactura4: '',
    cf4: '',
    acreedor4: '',
    concepto4: '',
    fechaPago4: '',
    importe4: '',
    numeroFactura5: '',
    fechaFactura5: '',
    cf5: '',
    acreedor5: '',
    concepto5: '',
    fechaPago5: '',
    importe5: '',
    totalCantidadJustificada: '',
    presupuestoInicial: '',
    inversionRealizada: '',
    desviacion: '',
    diaFirmaJustificacion: '',
    mesFirmaJustificacion: '',
    anioFirmaJustificacion: '',
    nombreFirma: '',
    firmaImagen: ''
  },
  fieldMapping: {
    expediente: 'expedienteEco',
    nif: 'nifCif',
    edificioVivienda: 'edificioViviendaJUS',
    l3l4: 'l3l4',
    parrafoTexto: 'parrafoTexto',
    numeroFactura1: 'numeroFactura1',
    fechaFactura1: 'fechaFactura1',
    cf1: 'cf1',
    acreedor1: 'acreedor1',
    concepto1: 'concepto1',
    fechaPago1: 'fechaPago1',
    importe1: 'importe1',
    numeroFactura2: 'numeroFactura2',
    fechaFactura2: 'fechaFactura2',
    cf2: 'cf2',
    acreedor2: 'acreedor2',
    concepto2: 'concepto2',
    fechaPago2: 'fechaPago2',
    importe2: 'importe2',
    numeroFactura3: 'numeroFactura3',
    fechaFactura3: 'fechaFactura3',
    cf3: 'cf3',
    acreedor3: 'acreedor3',
    concepto3: 'concepto3',
    fechaPago3: 'fechaPago3',
    importe3: 'importe3',
    numeroFactura4: 'numeroFactura4',
    fechaFactura4: 'fechaFactura4',
    cf4: 'cf4',
    acreedor4: 'acreedor4',
    concepto4: 'concepto4',
    fechaPago4: 'fechaPago4',
    importe4: 'importe4',
    numeroFactura5: 'numeroFactura5',
    fechaFactura5: 'fechaFactura5',
    cf5: 'cf5',
    acreedor5: 'acreedor5',
    concepto5: 'concepto5',
    fechaPago5: 'fechaPago5',
    importe5: 'importe5',
    totalCantidadJustificada: 'totalCantidadJustificada',
    presupuestoInicial: 'presupuestoInicial',
    inversionRealizada: 'inversionRealizada',
    desviacion: 'desviacion',
    diaFirmaJustificacion: 'diaFirmaJustificacion',
    mesFirmaJustificacion: 'mesFirmaJustificacion',
    anioFirmaJustificacion: 'anioFirmaJustificacion',
    nombreFirma: 'nombreFirma',
    firmaImagen: 'firma'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificaciones',
  component: 'MemoriaEconomica'
}
