export const memoriaEconomicaConfig = {
  id: 'memoria-economica',
  title: 'Memoria Económica Justificativa',
  description: 'Documento de memoria económica justificativa con aportación de justificantes de gasto de subvención',
  fileName: 'memoria-economica.pdf',
  route: '/justificaciones/memoria-economica',
  fields: [
    { name: 'expediente', label: 'Expediente', type: 'text', fullWidth: true },
    { name: 'nif', label: 'NIF', type: 'text' },
    { name: 'edificioVivienda', label: 'Tipo de Edificio', type: 'text', placeholder: 'ej: vivienda' },
    { name: 'l3l4', label: 'Línea de Subvención', type: 'text', placeholder: 'ej: Línea 3' },
    { name: 'parrafoTexto', label: 'Párrafo Introducción', type: 'textarea', fullWidth: true },
    { name: 'numeroFactura', label: 'Nº Factura', type: 'text' },
    { name: 'fechaFactura', label: 'Fecha Factura', type: 'date' },
    { name: 'cf', label: 'CF', type: 'text' },
    { name: 'acreedor', label: 'Acreedor', type: 'text' },
    { name: 'concepto', label: 'Concepto', type: 'text' },
    { name: 'fechaPago', label: 'Fecha Pago', type: 'date' },
    { name: 'importe', label: 'Importe', type: 'text' },
    { name: 'totalCantidadJustificada', label: 'Total Cantidad Justificada', type: 'text' },
    { name: 'presupuestoInicial', label: 'Presupuesto Inicial', type: 'text' },
    { name: 'inversionRealizada', label: 'Inversión Realizada', type: 'text' },
    { name: 'desviacion', label: 'Desviación (con IVA si es subvencionable)', type: 'text' },
    { name: 'fechaFirma', label: 'Fecha Firma', type: 'date' },
    { name: 'nombreFirma', label: 'Nombre Firma', type: 'text', fullWidth: true },
    { name: 'firmaImagen', label: 'Imagen de Firma', type: 'image' }
  ],
  defaultData: {
    expediente: '',
    nif: '',
    edificioVivienda: '',
    l3l4: '',
    parrafoTexto: '',
    numeroFactura: '',
    fechaFactura: '',
    cf: '',
    acreedor: '',
    concepto: '',
    fechaPago: '',
    importe: '',
    totalCantidadJustificada: '',
    presupuestoInicial: '',
    inversionRealizada: '',
    desviacion: '',
    fechaFirma: '',
    nombreFirma: '',
    firmaImagen: ''
  },
  fieldMapping: {
    expediente: 'expediente',
    nif: 'nifCif',
    edificioVivienda: 'edificioVivienda',
    l3l4: 'l3l4',
    parrafoTexto: 'parrafoTexto',
    numeroFactura: 'numeroFactura',
    fechaFactura: 'fechaFactura',
    cf: 'cf',
    acreedor: 'acreedor',
    concepto: 'concepto',
    fechaPago: 'fechaPago',
    importe: 'importe',
    totalCantidadJustificada: 'totalCantidadJustificada',
    presupuestoInicial: 'presupuestoInicial',
    inversionRealizada: 'inversionRealizada',
    desviacion: 'desviacion',
    fechaFirma: 'fechaFirmaJustificacion',
    nombreFirma: 'apellidosNombre',
    firmaImagen: 'firma'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificaciones',
  component: 'MemoriaEconomica'
}
