
export const memoriaFvAerConfig = {
  id: '1memoria-fv-aer',
  title: 'Memoria Justificativa FV + Aerotermia',
  description: 'Documento de memoria técnica justificativa de la actuación de fotovoltaica con aerotermia',
  fileName: 'memoria-fv-aer',
  route: '/justificaciones/memoria-fv-aer',
  fields: [
    { type: 'subsection', label: 'Datos Generales', name: 'datosGenerales', description: 'Información básica del inmueble y proyecto' },
    { name: 'expedienteEco', label: 'Expediente Económico', type: 'text', fullWidth: true },
    { name: 'nif', label: 'NIF', type: 'text' },
    { name: 'l3l4', label: 'Línea 3 o Línea 4', type: 'select', options: ['Línea 3', 'Línea 4'] },
    { name: 'tipoEdificio', label: 'Tipo de Edificio', type: 'text', fullWidth: true },
    { name: 'domicilio', label: 'Domicilio', type: 'text', fullWidth: true },
    { name: 'tipoSoporte', label: 'Tipo de Soporte', type: 'select', options: ['PLANA', 'INCLINADA', 'AMBAS'] },
    
    { type: 'subsection', label: 'Textos Condicionales', name: 'textosCondicionales', description: 'Textos opcionales según actuación' },
    { name: 'textoOpcional1', label: 'Texto Opcional (Sección 1)', type: 'textarea', rows: 2, fullWidth: true },
    { name: 'textoAerotermia1', label: 'Texto Aerotermia (Sección 1)', type: 'textarea', rows: 2, fullWidth: true },
    { name: 'textoAerotermia2', label: 'Texto Aerotermia (Sección 3)', type: 'textarea', rows: 2, fullWidth: true },
    { name: 'textoAerotermia3', label: 'Texto Aerotermia (Sección 6)', type: 'textarea', rows: 2, fullWidth: true },
    { name: 'potenciaBomba', label: 'Potencia Bomba (kW)', type: 'text' },
    { name: 'depositoLitros', label: 'Depósito (L)', type: 'text' },
    { name: 'resistenciaElectrica', label: 'Resistencia Eléctrica (kW)', type: 'text' },
    { name: 'potenciaTotalInstalada', label: 'Potencia Total (kW)', type: 'text' },
    { name: 'coincidencia', label: 'Texto de Coincidencia de Costes', type: 'text', fullWidth: true },
    
    { type: 'subsection', label: 'Desglose de Costes SIN IVA', name: 'costosSinIva', description: 'Importes sin IVA' },
    { name: 'importeActuacionesSinIva', label: 'Actuaciones sin Retirada de Amianto (Sin IVA)', type: 'text' },
    { name: 'importeTotalSinIva', label: 'Importe Total (Sin IVA)', type: 'text' },
    
    { type: 'subsection', label: 'Desglose de Costes CON IVA', name: 'costosConIva', description: 'Importes con IVA' },
    { name: 'importeActuacionesConIva', label: 'Actuaciones sin Retirada de Amianto (Con IVA)', type: 'text' },
    { name: 'importeTotalConIva', label: 'Importe Total (Con IVA)', type: 'text' },
    
    { type: 'subsection', label: 'Acreditación de Subvención', name: 'acreditacionSubvencion', description: 'Datos de mejora energética y subvención' },
    { name: 'porcentajeMejoraEnergeticaAcreditado', label: 'Porcentaje de Mejora Energética Acreditado', type: 'text' },
    { name: 'porcentajeSubvencionable', label: 'Porcentaje Subvencionable a Aplicar', type: 'text' },
    { name: 'importeSubvencionResultante', label: 'Importe de la Subvención Resultante', type: 'text' },
    
    { type: 'subsection', label: 'Fechas', name: 'fechas', description: 'Información temporal' },
    { name: 'fechaConclusionDia', label: 'Día Conclusión', type: 'text' },
    { name: 'fechaConclusionMes', label: 'Mes Conclusión', type: 'text' },
    { name: 'fechaConclusionAnio', label: 'Año Conclusión', type: 'text' },
    { name: 'dia', label: 'Día (Firma)', type: 'text' },
    { name: 'mes', label: 'Mes (Firma)', type: 'text' },
    { name: 'anio', label: 'Año (Firma)', type: 'text' },
    
    { type: 'subsection', label: 'Firma y Documentación', name: 'firmaYDocumentacion', description: 'Datos del firmante' },
    { name: 'firmaImagen', label: 'Imagen de Firma', type: 'image' },
    
    { type: 'subsection', label: 'Opciones', name: 'opciones', description: 'Configuración adicional' },
    { name: 'aerotermia', label: 'Incluir sección de Aerotermia', type: 'checkbox' }
  ],
  defaultData: {
    expedienteEco: '',
    nif: '',
    tipoEdificio: '',
    domicilio: '',
    l3l4: '',
    tipoSoporte: '',
    textoOpcional1: '',
    textoAerotermia1: '',
    textoAerotermia2: '',
    textoAerotermia3: '',
    potenciaBomba: '1,8',
    depositoLitros: '200',
    resistenciaElectrica: '1,5',
    potenciaTotalInstalada: '3,3',
    caracteristicasAerotermia: '',
    coincidencia: '',
    importeActuacionesSinIva: '0,00 €',
    importeActuacionesConIva: '0,00 €',
    importeTotalSinIva: '0,00 €',
    importeTotalConIva: '0,00 €',
    porcentajeMejoraEnergeticaAcreditado: '64,22%',
    porcentajeSubvencionable: '80,00%',
    importeSubvencionResultante: '9.920,00 €',
    fechaConclusionDia: '',
    fechaConclusionMes: '',
    fechaConclusionAnio: '',
    dia: '',
    mes: '',
    anio: '',
    firmaImagen: '',
    aerotermia: false
  },
  fieldMapping: {
    expedienteEco: 'expedienteEco',
    nif: 'nifCif',
    tipoEdificio: 'tipoEdificio',
    domicilio: (formData) => `${formData.direccionCompleta} - ${formData.codigoPostalEmplazamiento} - ${formData.localidadEmplazamiento} - ${formData.provinciaEmplazamiento}`,
    l3l4: 'l3l4',
    tipoSoporte: 'tipoSoporte',
    textoOpcional1: 'textoOpcional1',
    textoAerotermia1: 'textoAerotermia1',
    textoAerotermia2: 'textoAerotermia2',
    textoAerotermia3: 'textoAerotermia3',
    potenciaBomba: 'potenciaBomba',
    depositoLitros: 'depositoLitros',
    resistenciaElectrica: 'resistenciaElectrica',
    potenciaTotalInstalada: 'potenciaTotalInstalada',
    caracteristicasAerotermia: (formData) => `• Las características técnicas del equipo aerotérmico son las siguientes:\n• Potencia térmica de la bomba de calor: ${formData.potenciaBomba} 1,8 kW\n• Resistencia eléctrica auxiliar: ${formData.resistenciaElectrica} 1,5 kW\n• Potencia total instalada: ≈ ${formData.potenciaTotalInstalada} 3,3 kW`,
    coincidencia: 'coincidencia',
    importeActuacionesSinIva: 'importeActuacionesSinIva',
    importeActuacionesConIva: 'importeActuacionesConIva',
    importeTotalSinIva: 'importeTotalSinIva',
    importeTotalConIva: 'importeTotalConIva',
    porcentajeMejoraEnergeticaAcreditado: 'porcentajeMejoraEnergeticaAcreditado',
    porcentajeSubvencionable: 'porcentajeSubvencionable',
    importeSubvencionResultante: 'importeSubvencionResultante',
    fechaConclusionDia: 'fechaConclusionDia',
    fechaConclusionMes: 'fechaConclusionMes',
    fechaConclusionAnio: 'fechaConclusionAnio',
    dia: 'dia',
    mes: 'mes',
    anio: 'anio',
    firmaImagen: 'firma',
    aerotermia: 'aerotermia'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificaciones'
};
