export const memoriaEconomicaConfig = {
  id: 'memoria-economica',
  title: 'Memoria Económica Justificativa',
  description: 'Documento de memoria económica justificativa con aportación de justificantes de gasto de subvención',
  fileName: 'memoria-economica.pdf',
  route: '/justificaciones/memoria-economica',
  fields: [
    { name: 'expediente', label: 'Expediente', type: 'text', fullWidth: true },
    { name: 'nif', label: 'NIF', type: 'text' },
    { name: 'edificioVivienda', label: 'Tipo de Edificio', type: 'text', placeholder: 'ej: vivienda' },
    { name: 'l3l4', label: 'Línea de Subvención', type: 'text', placeholder: 'ej: Línea 3' },
    { name: 'parrafoTexto', label: 'Párrafo Introducción', type: 'textarea', fullWidth: true },
    { name: 'numeroFactura', label: 'Nº Factura', type: 'text' },
    { name: 'fechaFactura', label: 'Fecha Factura', type: 'date' },
    { name: 'cf', label: 'CF', type: 'text' },
    { name: 'acreedor', label: 'Acreedor', type: 'text' },
    { name: 'concepto', label: 'Concepto', type: 'text' },
    { name: 'fechaPago', label: 'Fecha Pago', type: 'date' },
    { name: 'importe', label: 'Importe', type: 'text' },
    { name: 'totalCantidadJustificada', label: 'Total Cantidad Justificada', type: 'text' },
    { name: 'presupuestoInicial', label: 'Presupuesto Inicial', type: 'text' },
    { name: 'inversionRealizada', label: 'Inversión Realizada', type: 'text' },
    { name: 'desviacion', label: 'Desviación (con IVA si es subvencionable)', type: 'text' },
    { name: 'diaFirmaJustificacion', label: 'Día Firma', type: 'text' },
    { name: 'mesFirmaJustificacion', label: 'Mes Firma', type: 'text' },
    { name: 'anioFirmaJustificacion', label: 'Año Firma', type: 'text' },
    { name: 'nombreFirma', label: 'Nombre Firma', type: 'text', fullWidth: true },
    { name: 'firmaImagen', label: 'Imagen de Firma', type: 'image' }
  ],
  defaultData: {
    expediente: '0034',
    nif: 'B-003637D',
    edificioVivienda: 'vivienda',
    l3l4: 'Línea 3',
    parrafoTexto: 'Estas ayudas tienen por objeto la financiación de obras o actuaciones en los edificios de uso predominante residencial en las que se obtenga una mejora acreditada de la eficiencia energética, con especial atención a la envolvente edificatoria en edificios de tipología residencial colectiva, incluyendo sus viviendas, y en las viviendas unifamiliares.',
    numeroFactura: '003832',
    fechaFactura: '06/10/23',
    cf: 'B-003637D',
    acreedor: 'MAS SOL ENERGIA 15 S.L.U',
    concepto: '',
    fechaPago: '24/07/2023',
    importe: '8.400,00',
    totalCantidadJustificada: '0,00',
    presupuestoInicial: '0,00',
    inversionRealizada: '0,00',
    desviacion: '0,00',
    diaFirmaJustificacion: 'diaFirmaJustificacion',
    mesFirmaJustificacion: 'mesFirmaJustificacion',
    anioFirmaJustificacion: 'anioFirmaJustificacion',
    nombreFirma: 'nombreFirma',
    firmaImagen: ''
  },
  fieldMapping: {
    expediente: 'expedienteEco',
    nif: 'nif',
    edificioVivienda: 'edificioViviendaJUS',
    l3l4: 'l3l4',
    parrafoTexto: 'parrafoTexto',
    numeroFactura: 'numeroFactura',
    fechaFactura: 'fechaFactura',
    cf: 'cf',
    acreedor: 'acreedor',
    concepto: 'concepto',
    fechaPago: 'fechaPago',
    importe: 'importe',
    totalCantidadJustificada: 'totalCantidadJustificada',
    presupuestoInicial: 'presupuestoInicial',
    inversionRealizada: 'inversionRealizada',
    desviacion: 'desviacion',
    diaFirmaJustificacion: 'diaFirmaJustificacion',
    mesFirmaJustificacion: 'mesFirmaJustificacion',
    anioFirmaJustificacion: 'anioFirmaJustificacion',
    nombreFirma: 'nombreFirma',
    firmaImagen: 'firma'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificaciones',
  component: 'MemoriaEconomica'
}
