export const obraMassolConfig = {
  id: 'obra-massol',
  title: 'Declaración inicio de obra - Massol',
  description: 'Formulario para declarar el inicio de obra según el modelo de Massol.',
  fileName: 'obra-massol.pdf',
  route: '/justificaciones/obra-massol',
  fields: [
    { name: 'potenciaInstalacion', label: 'Potencia Instalación (ej: 5)', type: 'text' },
    { name: 'emplazamientoCalle', label: 'Calle Emplazamiento', type: 'text', fullWidth: true },
    { name: 'numeroEmplazamiento', label: 'Número', type: 'text' },
    { name: 'codigoPostalEmplazamiento', label: 'Código Postal', type: 'text' },
    { name: 'ciudadEmplazamiento', label: 'Ciudad', type: 'text' },
    { name: 'provinciaEmplazamiento', label: 'Provincia', type: 'text' },
    { name: 'referenciaCatastral', label: 'Referencia Catastral', type: 'text', fullWidth: true },
    { name: 'diaInicio', label: 'Día Inicio', type: 'text' },
    { name: 'mesInicio', label: 'Mes Inicio', type: 'text' },
    { name: 'anioInicio', label: 'Año Inicio', type: 'text' },
    { name: 'diaFirma', label: 'Día Firma', type: 'text' },
    { name: 'mesFirma', label: 'Mes Firma', type: 'text' },
    { name: 'anioFirma', label: 'Año Firma', type: 'text' },
    { name: 'firma', label: 'Imagen de Firma', type: 'image' }
  ],
  defaultData: {
    potenciaInstalacion: '',
    emplazamientoCalle: '',
    numeroEmplazamiento: '',
    codigoPostalEmplazamiento: '',
    ciudadEmplazamiento: '',
    provinciaEmplazamiento: '',
    referenciaCatastral: '',
    diaInicio: '',
    mesInicio: '',
    anioInicio: '',
    diaFirma: '',
    mesFirma: '',
    anioFirma: '',
    firma: ''
  },
  fieldMapping: {
    potenciaInstalacion: 'e2_potenciaNominalInversores',
    emplazamientoCalle: 'emplazamientoCalle',
    numeroEmplazamiento: 'numero',
    codigoPostalEmplazamiento: 'codigoPostalEmplazamiento',
    ciudadEmplazamiento: 'localidadEmplazamiento',
    provinciaEmplazamiento: 'provinciaEmplazamiento',
    referenciaCatastral: 'referenciaCatastral',
    diaInicio: 'diaInicio',
    mesInicio: 'mesInicio',
    anioInicio: 'anioInicio',
    diaFirma: 'diaFirmaJustificacion',
    mesFirma: 'mesFirmaJustificacion',
    anioFirma: 'anioFirmaJustificacion',
    firma: 'firma'
  },
  capabilities: {
    canPreview: true,
    canEdit: true,
    canGeneratePDF: true
  },
  category: 'justificaciones',
}
